### PR TITLE
[DEVOPS-203] Convert travis jobs to use Nix instead of stack

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by domenkozar** [comment]
Needs changes to `.travis.yaml` to replace run this on macos as well and to require all Nix builds (and disable others).

**Comment by domenkozar** [comment]
- [ ] comment out haddock and open an issue on stack2nix to support that
- [ ] remove the line passing `--test` and use recent stack2nix to pass `--test` to it

**Comment by cleverca22** [comment]
i think the travis failure is from master, i'll rebase tonight

**Comment by cleverca22** [comment]
https://hydra.iohk.io/build/12189/nixlog/9
i can confirm the problem is still happening on master

**Comment by domenkozar** [comment]
@cleverca22 this needs to modify `.travis.yaml` to remove the test Nix base build and to require stack2nix build to pass.

**Pull request merged**
