### PR TITLE
Relays can use subscription instead of static routing

### PR DESCRIPTION
**Pull request by dcoutts**
Extend relay topology to allow subscribing to other relays, like
normal edge nodes do, as an alternative to static routing.

This means we can use topologies like
```
  relay-unpriv0:
    type: relay
    region: eu-central-1
    dynamic-subscribe: [[{"host": "relay-priv1"},{"host": "relay-priv2"}]]
    valency:   2 # optional
    fallbacks: 1 # optional
    host: relay-node0.local
```
The point of this is that it means we can have lots of extra relays but
do so with fairly simple configuration. The config for relays of this
form can all be the same (apart from hostname), and we don't have to
chagne the static routes of the other node when we add new relays.

This works because these nodes will subscribe at runtime to the given
other relays, so they don't need to have them as routes statically. The
downside is that we cannot express such complex routing, but for the use
case of creating (auto) sclable groups of extra relays this is fine.

### CODE REVIEW

**Comment by dcoutts** [comment]
> If the current definition is still correct then I think we should add a comment explaining why.

Ok, so your point is that the existing relays (using static routing) will still consider all subscribers to be edge nodes, and that includes the new relays we might add that work via subscription. Basically, is it ok for privileged relays to consider unprivileged relays to be edge nodes or do they need to also consider them to be relays.

The expected topology for unprivileged relays is to only be connected to other privileged or unprivileged relays, and they are not needed to to support the core nodes or privileged relays by providing any connectivity. They are only intended to proxy large numbers of edge nodes.

So by intuition, a privileged should not need to know the difference between a single edge node subscribing and an unprivileged relay that has 100 edge nodes behind it. They should be treated the same (as an edge node).

The privileged relay will consider the unprivileged relay as an edge node, so that part of the policy is:
```
 * header announce: to Edge,  P3, to all,        max ahead 0, fallback drop
 * header request : to Edge not sent!
 * block  request : to Edge not sent!
 * transaction    : to Edge not sent!
 * mpc            : to Edge not sent!
```
So basically it will announce headers, and as normal it will accept requests for block headers and blocks. But it will never ask those unprivileged relays for block headers or blocks.

The unprivileged relay will consider the privileged relay as an relay node, so that part of the policy is:
```
 * header announce: to Relay, P1, 3 route lists, max ahead 0, fallback drop
 * header request : to Relay, P2, 3 route lists, max ahead 2, fallback drop
 * block  request : to Relay+Core, P2, one of,   max ahead 3, fallback drop
 * transaction    : to Relay, P4, 3 route lists max ahead 20, fallback drop
 * mpc            : to Relay not sent!
```
So it can send header announcements, but this is benign. It will also of course request headers and blocks from the privileged relay, and it will forward transactions to the privileged relay.

**Comment by dcoutts** [comment]
@edsko updated the network policy doc. Does this sufficiently address your concerns?

**Comment by edsko** [comment]
I still think it would be useful to have a small comment above `topologySubscribers`, if only with a reference to the markdown file.

**Comment by adinapoli-iohk** [comment]
Ok, this is working as intended, we just need to wait for the CI's final approval and this is good to go.

**Pull request merged**
