### PR TITLE
[CSL-1638] Allow updates w/o software change

### PR DESCRIPTION
**Pull request by int-index**

### CODE REVIEW

**Comment by int-index** [comment]
Some of the additions here are still valuable.

**Comment by int-index** [comment]
I removed the unnecessary bits after our call, and here are the remaining ones:

1. I added a `propose-unlock-stake-epoch` command to `auxx` that sends an update proposal with a new value of `unlockStakeEpoch`
2. I added a `print-bvd` command `auxx` in order to monitor the current `BlockVersionData`
3. I fixed the name of `puIdx` (there was a TODO about it)
4. I fixed the `Buildable BlockVersionData` instance
5. Most important (why it should be merged before mainnet): I relaxed the check on update proposals that prevented me from creating a proposal without software changes.

**Comment by int-index** [comment]
@dcoutts This PR must be merged before mainnet (justification above), please review.

**Comment by georgeee** [comment]
So yes, as stated above:

> The real reason is that we indeed always want to change software version, but for some applications we don't have installers, so update data just doesn't make sense and they should be updated manually somehow.

Good example is our server installation `cardano-sl`, which doesn't have any installer for any platform (don't mix with `csl-daedalus` which we deliver to MacOS, Windows) but still we may want to register it's version because:

1. Registering version of some software is only way to propose protocol update (block version)
2. To explicitly publish our application has up-to-date version X (though some platform users might need to update their nodes manually, e.g. by recompilation of master)

**Comment by dcoutts** [comment]
It's not yet clear to me that this is critical for mainnet. Requires further discussion. Does this have to be in mainnet from launch or can it be introduced in a later update?

**Comment by georgeee** [comment]
Will be merged to master as part of cardano-sl-1.0 branch

**Pull request closed without merging**
