### PR TITLE
[CSL-2009] Remove wallet purescript bridge.

### PR DESCRIPTION
**Pull request by ksaric**
https://iohk.myjetbrains.com/youtrack/issue/CSL-2009

TBH, I removed this because I found that not being able to run `stack ghci` (globally) is annoying. 
But it's something that needs to be done anyway.

This should make the CI faster as well.

### CODE REVIEW

**Comment by ksaric** [comment]
@akegalj You know the most about `wallet-bridge`, I removed what I found to be important, but there would likely be much more in the project, please take a look.

**Comment by StephenCharles** [comment]
Nice! I guess I wasn't fast enough ahah. I would also remove all of the references to it in the documentation.

**Comment by ksaric** [comment]
@StephenCharles You can improve this PR if you see something that needs fixing, I don't mind. 
Thanks for your time in any case :bowing_man:

**Comment by StephenCharles** [comment]
I would like to but I do not have access rights to this repo. I would have to create a fork of your branch and then open a pr for it.

**Comment by ksaric** [comment]
Rebased onto `feature/new-wallet` - https://github.com/input-output-hk/cardano-sl/pull/2022

**Comment by gromakovsky** [comment]
FYI: you can change base branch in PR instead of creating another PR.

**Comment by ksaric** [comment]
@gromakovsky Tried that, the result is a bunch of commits from `alfredo/wallet-new`. 
Also tried using `git rebase --onto master alfredo/wallet-new ksaric/CSL-2009`, same result :man_shrugging:

**Pull request closed without merging**
