### PR TITLE
[CSL-1412] Check length when deserialising AsBinary instances

### PR DESCRIPTION
**Pull request by adinapoli-iohk**
This PR fixes the concerns expressed in [CSL-1412](https://issues.serokell.io/issue/CSL-1412), by passing explicitly the number of BYTES in the macro and performing the length check in the decoding site.

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
Oh, looks like the CI timed out here, for no good reasons.

**Comment by adinapoli-iohk** [comment]
> LGTM, please rebase over master and remove my FIXME note (I merged #1250).

haha yes, I've lost the race 😁  ok, will do asap!

**Comment by adinapoli-iohk** [comment]
@gromakovsky as soon as the CI approves, we should be good to go!

**Comment by adinapoli-iohk** [comment]
Sigh, the CI failed again due to the timeout limit exceeded 😭

**Comment by gromakovsky** [comment]
_restarted_

**Pull request merged**
