### PR TITLE
[CSL-987] Get rid of SafeCopy in most places

### PR DESCRIPTION
**Pull request by ksaric**
I moved everything to `Pos/SafeCopy.hs`, removed unused modules.

### CODE REVIEW

**Comment by gromakovsky** [comment]
```
gromak ~/Work/cardano-sl (feature/CSL-987-get-rid-of-SafeCopy|✔) % grep -r Data.SafeCopy core/Pos                                                                                                                                                                         0 :)
core/Pos/Binary/Class.hs:import           Data.SafeCopy               (Contained, SafeCopy (..), contain,
core/Pos/Binary/Class.hs:-- | A helper for "Data.SafeCopy" that creates 'putCopy' given a 'Bi'
core/Pos/Binary/Class.hs:-- | A helper for "Data.SafeCopy" that creates 'getCopy' given a 'Bi'
core/Pos/Binary/Crypto.hs:import           Data.SafeCopy            (SafeCopy (..))
core/Pos/Crypto/Hashing.hs:import           Data.SafeCopy        (SafeCopy (..))
core/Pos/Crypto/RedeemSigning.hs:import           Data.SafeCopy        (SafeCopy (..), base, contain, deriveSafeCopySimple,
core/Pos/Crypto/Signing.hs:import           Data.SafeCopy                   (SafeCopy (..), base, contain,
core/Pos/Crypto/SafeSigning.hs:import           Data.SafeCopy         (base, deriveSafeCopySimple)
core/Pos/Merkle.hs:import           Data.SafeCopy        (SafeCopy (..))
core/Pos/Data/Attributes.hs:import           Data.SafeCopy       (SafeCopy (..), contain, safeGet, safePut)
core/Pos/Core/Types.hs:import           Data.SafeCopy              (base, deriveSafeCopySimple)
core/Pos/Core/Script.hs:import           Data.SafeCopy      (SafeCopy (..))
```

There is also some `SafeCopy` stuff in subprojects like `cardano-sl-core`. Probably it makes sense to move it to `Pos.SafeCopy` too. I didn't grep other subprojects.

**Comment by neongreen** [comment]
@rockbmb 

> @ksaric Can you tell me what the purpose of this change is? I agree with it, but I can't quite find a reason that would warrant it.

The purpose was to get rid of extraneous instances which were slowing down compilation. It looks like here instances are merely moved – but anyway, now removing them later will be easier :)

**Comment by neongreen** [comment]
> is it possible to write some Template Haskell to automatically generate safecopy identity testing like what autoexporter does with re-exporting modules?

`autoexporter` doesn't use TH, it's implemented as a preprocessor. I don't think implementing automatic SafeCopy testing will be easy.

**Comment by ksaric** [comment]
I moved the remaining instances from _core_.
@neongreen I tried removing them, but they are required for the compilation of wallet instances, at least from what I could find. Seems like this is a huge tree of dependency starting up from wallet.

**Comment by neongreen** [comment]
@ksaric 

There are instances left in:

[ ] `Pos.Merkle`
[ ] `Pos.Data.Attributes`
[ ] `Pos.Core.Types`
[ ] `Pos.Core.Script` (but those can be left there, I guess)
[ ] `Pos.Crypto.Hashing`
[ ] `Pos.Crypto.Signing` (again, those can be left in place)
[ ] `Pos.Crypto.RedeemSigning` (ditto)
[ ] `Pos.Crypto.SafeSigning` (ditto)

**Pull request merged**
