### PR TITLE
[CSL-1198] Turn off the -N RTS option

### PR DESCRIPTION
**Pull request by arybczak**

### CODE REVIEW

**Comment by kantp** [comment]
@arybczak It seems that the CI is hung on this one, preventing us from merging. Could you please remove the `-N` option from `daedalus/daedalus/installers/cardano-installer.cabal` and push again, triggering a rebuild by the CI?

**Comment by domenkozar** [comment]
@kantp I think that's another repository, not part of cardano-sl

**Comment by kantp** [comment]
You're right, thanks!
@arybczak in that case, could you just do a git amend and re-push to trigger the CI?

**Comment by arybczak** [comment]
Done.

**Comment by domenkozar** [comment]
Same issue, I have contacted travis-ci support. I've seen this kind of CI issues before, but I haven't been able to find the culprit.

**Comment by domenkozar** [comment]
Ah! Now I understand. It's reporting the PR builds as successful because the branch build it not part of IOHK organization. Let me fix what checks are required.

**Comment by domenkozar** [comment]
@kantp @arybczak fixed.

**Comment by kantp** [comment]
@domenkozar Thank you!

**Comment by domenkozar** [comment]
Note that you have to create a separate PR for `cardano-sl-0.5` for fixes to be in 0.5 testnet update.

**Comment by kantp** [comment]
@domenkozar Thanks. Just to clarify: do you mean the branch `cardano-sl-0.5-rc`?

**Comment by domenkozar** [comment]
Yes :)

**Pull request merged**
