### PR TITLE
[CSL-2133] Simple application optimizations for txp/dlg

### PR DESCRIPTION
**Pull request by volhovm**
This is not significant optimization (maybe <5% of application time), but still counts when we get rid of the main bottleneck (CSL-2132).

### CODE REVIEW

**Comment by h4ck3rm1k3** [comment]
optimiations -> optimizations

**Comment by gromakovsky** [comment]
There's the same typo in the commit message.

**Comment by gromakovsky** [comment]
Also `continuous-integration/travis-ci/push` failed :(

**Comment by gromakovsky** [comment]
`pkgs/default.nix` was regenerated in `release/1.0.4` (`utf8-string` package), so you can instead rebase to make the PR a bit smaller 😉

**Comment by volhovm** [comment]
Rebased. Needs @dcoutts approve to be merged.

**Comment by volhovm** [comment]
I guess it won't be ever merged because we're working on 1.1 already. If we'll need these optimizations in 1.0.4, it's still not complex to cherry-pick them later. Closing this PR.

**Comment by domenkozar** [comment]
These optimizations should target master as a hotfix.

**Comment by dcoutts** [comment]
@volhovm could you rebase against master. Thanks.

**Pull request closed without merging**
