### PR TITLE
[CSL-849] remove MessageName, MessagePart

### PR DESCRIPTION
**Pull request by avieth**
Bumped the time-warp-nt revision to one which doesn't have `MessageName`. It's replaced with `MessageCode ~ Word16`. This means the `MessagePart` motif that was used to get a whack of `Message` instances for free no longer applies, so that was removed. I could have updated it to use some similar scheme, like using the top 8 bits for the relay message constructor and the bottom eight for the particular content type. But I think it's better to have the message codes stated explicitly. I don't believe all of the codes listed in `src/Pos/Communication/Message.hs` are actually necessary. They were needed in order to compile, but surely some of the relay message instances don't need to be there.

So the length-prefixed `MessageName` is no longer used, which is the point of the ticket CSL-849, but `VerInfo` still contains arbitrarily-long `HashMap`s so the problem isn't yet solved.

### CODE REVIEW

**Comment by neongreen** [comment]
I think that the [`HandlerSpec` encoding table](https://github.com/input-output-hk/cardano-sl/pull/1288/files#diff-5a22153eaebb1927ba5f9b5b1df6104fR63) should be removed completely, as it's a) outdated and b) not necessary since the current encoding is much simpler than what we had before.

**Comment by neongreen** [comment]
(Otherwise, LGTM.)

**Comment by neongreen** [comment]
```
[ 70 of 205] Compiling Pos.Communication.Message ( src\Pos\Communication\Message.hs, .w\dist\ca59d0ab\build\Pos\Communication\Message.o )
C:\w\src\Pos\Communication\Message.hs:87:10: error:
    * No instance for (Buildable (InvOrData key TxMsgContents))
        arising from a use of `Node.Message.Class.$dmformatMessage'
    * In the expression:
        Node.Message.Class.$dmformatMessage @InvOrData key TxMsgContents
      In an equation for `formatMessage':
          formatMessage
            = Node.Message.Class.$dmformatMessage @InvOrData key TxMsgContents
      In the instance declaration for
        `Message (InvOrData key TxMsgContents)'
--  While building package cardano-sl-0.5.1
```

**Comment by avieth** [comment]
https://github.com/input-output-hk/cardano-sl/pull/1288/commits/736b4318fb2f598a886c4468f96e48f37d047b40

Includes a `formatMessage` definition for `TxMsgContents` that I had forgotten. Strange that my local build, and one of the travis builds, passed.

**Comment by avieth** [comment]
CI has failed because of this test: `Richmen with stake distribution [0.24, 0.25, 0.26, 0.29] to test validity of @computeSharesDistr`. I've seen this before, but it's nothing to do with these changes.

**Comment by gromakovsky** [comment]
@avieth I've restarted the build. This failure in tests should fully disappear after #1275 is polished and merged.

**Comment by gromakovsky** [comment]
There is a conflict now.

**Comment by adinapoli-iohk** [comment]
I have no idea what happened here -- if I click on the `Details` link Travis shows everything as green, but yet we get this (stale?) yellow dot here 🙉

**Comment by gromakovsky** [comment]
Strange, I restarted one build, maybe it will help.

**Comment by avieth** [comment]
No clue why one of the travis builds failed. Can't see an error in the logs.

**Comment by adinapoli-iohk** [comment]
If I've untangled everything corretly I swear I have seen a timeout lurking at some point in the logs 🙊

**Comment by neongreen** [comment]
@avieth there's a conflict already :(

**Comment by avieth** [comment]
> there's a conflict already :(

I did the stack2nix thing but while it was going there must have been a commit of `pkgs/default.nix` to master. Rebased and ran it again and now CI is going.

**Pull request merged**
