### PR TITLE
[CSL-1843] Merge cardano-sl-1.0 (Nov 7) to master.

### PR DESCRIPTION
**Pull request by ksaric**
https://issues.serokell.io/issue/CSL-1843

Merging changes from `cardano-sl-1.0` back to `master`.
There were a lot of changes, it would be helpful if you could approve the parts you wrote.

`BListenerSpec` is removed, will integrate it back once we merge the testing branch so I don't have to do the same work twice - https://github.com/input-output-hk/cardano-sl/pull/1526

### CODE REVIEW

**Comment by gromakovsky** [comment]
@ksaric sorry, I don't get it, where is **merge** commit?
I wanted you to literally **merge** `7c65f17b4` into master :/

**Comment by gromakovsky** [comment]
What exactly did you do?

**Comment by ksaric** [comment]
@gromakovsky Ah, I did merge it but committed it with my own commit.
Let me see if the nix file is correct and and I can try to make it explicit.

**Comment by ksaric** [comment]
@gromakovsky I did the following:
```
git checkout master
git merge 7c65f17b4c6505eeee491d9f711849c8a073a9bc
-- merged conflicts and moved BListenerSpec to explorer/
git add --all
git checkout ksaric/CSL-1843
git commit -a -S -m "[CSL-1843] Merge cardano-sl-1.0 (Nov 7) to master."
git push origin ksaric/CSL-1843 
```

I would need to change the files again manually if you want to see the merge. Is this necessary?

**Comment by gromakovsky** [comment]
@ksaric do you know which exactly commit from master was used (i. e. was HEAD) when you were doing merge?

**Comment by ksaric** [comment]
@gromakovsky I will close this PR and re-open a new one with the merge commit.

**Comment by gromakovsky** [comment]
@ksaric so yes, I want to have merge commit and note that it's not necessary to resolve all conflicts again.
You can do something like:
```
git checkout master
git checkout -b ksaric/csl1843-fix
git merge 7c65f17b4c6505eeee491d9f711849c8a073a9bc
git add . # pretend that you resolved all conflicts even though you didn't
git diff ksaric/CSL-1843 > patch
git apply patch
git commit -a --amend
```

**Comment by ksaric** [comment]
Closing this in favor of https://github.com/input-output-hk/cardano-sl/pull/1876 since that PR explicitly contains the merge commit and the changes after it.
I did the changes manually.

**Pull request closed without merging**
