### PR TITLE
[CSL-1821] Add hash-installer script

### PR DESCRIPTION
**Pull request by hithroc**
Added `hash-installer.sh`

Usage: `./scripts/hash-installer.sh [filename]`

https://github.com/input-output-hk/cardano-sl/commit/c24db2a739d1215101c5038a12968db476d8684d#commitcomment-25630215

### CODE REVIEW

**Comment by gromakovsky** [comment]
cc @cleverca22

**Comment by cleverca22** [comment]
stack would trigger a full rebuild of nearly everything in cardano, and ignore the pre-built copy on hydra

**Comment by gromakovsky** [comment]
Ok, @hithroc please drop `stack exec` part.

**Comment by hithroc** [comment]
Alright, now `hash-installer.sh` just assumes that `cardano-auxx` is in PATH

**Pull request merged**
