### PR TITLE
[CSL-1296] Migrate serialisation layer from Store to Cborg

### PR DESCRIPTION
**Pull request by adinapoli-iohk**
bomb

## What

This quite beefy-PR migrates the serialisation layer from `store` to `cborg`.

## Why

This was necessary as `Store` was not suitable for `cardano-sl` as it was subject to DDoS attacks (it assumes a non-hostile environment) and it's not based on a well-defined protocol, making it complicated to build customer-end infrastructure on top of it.

## Linked Issue

https://issues.serokell.io/issue/CSL-1296

## How

The 10.000ft overview is the following:

* I have migrated all the instances from the old `Bi` to the respective `cborg` implementation. I have tried to keep the old logic intact.

* I have added a bunch of specs in a module call `CborSpec` which deals explicitly with the `cborg` implementation. You might notice a bit of overlap with these tests from the ones already scattered across the codebase in the `BinarySpec`(s), but I preferred to keep everything in one module initially, for ease of testing.

* I have run the `scripts/launch/demo.sh` (after getting green specs) and it seems to not blow up, but it's far from a definitive proof this is working.

## What's left and caveat

* Most types living in `Pos.Binary.Class.Numbers` feels somewhat redundant now, as we are always piggybacking on `cborg` for those (See my note on `TinyVarInt` & Co to see what I'm talking about);
* I would like special review on the `Pos.Communication.BiP` module, as I'm not sure the porting I have done is sound;
* There are a couple of minor outstanding issues with the CBOR-based serialisation, like making sure the `Generic` derived instances are stripped from the version tag (which was needed for the `serialise` package), but this can happen later.

### CODE REVIEW

**Comment by neongreen** [comment]
Aargh, more conflicts.

**Comment by adinapoli-iohk** [comment]
@neongreen leave those to me!

**Comment by neongreen** [comment]
Well, I already fixed those, now let's hope that nobody pushes anything else until the build passes

**Comment by neongreen** [comment]
Going to restart the macOS build.

**Comment by adinapoli-iohk** [comment]
@neongreen @dcoutts @kantp I think this PR is now as good as it gets and should rather be merged than kept hanging. We reviewed the code and we think it's sensible enough, at least as a first pass, and I have spent the last few days trying to dig deeper into some `NoParse` errors Philipp was seeing when running the benchmarks against the local cluster.

It turned out that those `NoParse` errors were coming from `timewarp-nt`, which was allowing empty `ByteString`(s) to be passed downstream to the `BiP` decoder, which was thus interpreting them as `end of input`. This explains [my last commit](https://github.com/input-output-hk/cardano-sl/pull/1203/commits/933ec0061c1c589c80aa4970a6020a3cc299215b) which bumps `timewarp-nt` to a revision which fixes that (don't worry, this is all part of the work Alex & Edsko's are doing on the outbound queue).

Once that was fixed I couldn't see any serialization-related errors in the logs anymore. Specs are all passing (module one which is broken here *and* on master, so no regression was introduced).

As soon as this gets merged, I think the natural next step is to tackle https://issues.serokell.io/issue/CSL-1393, so we can kick `store` out of the build plan (currently it still being built as trans-dep of `kademlia`)

**Comment by gromakovsky** [comment]
@adinapoli-iohk we are trying to merge it for few days already. Unfortunately, we have some problems with CI which delay the merge currently :(

**Comment by adinapoli-iohk** [comment]
> we are trying to merge it for few days already. Unfortunately, we have some problems with CI which delay the merge currently :(

Yea, I've noticed! I just wanted to give you guys the final mark of approval that things seems to work in the benchmark land as well 😉

**Comment by gromakovsky** [comment]
I think MacOS builds timed out approximately 10 times out of 10. I don't know what to do with it.
Previously the chances of failure were about 60% (my empirical observation) and it seems that with this PR they became close to 100% :(

**Comment by adinapoli-iohk** [comment]
> Previously the chances of failure were about 60% (my empirical observation) and it seems that with this PR they became close to 100% :(

Weird -- I remember that up until recently the CI passed (check for example commit https://github.com/input-output-hk/cardano-sl/pull/1203/commits/6270c76a39c5717ec65a0a7075df44cde1992e3d), so I might be tempted to say it's not related to the PR but in general to the CI shenanigans we have been observing lately 😞

**Comment by gromakovsky** [comment]
@adinapoli-iohk builds for 6270c76 passed because at that point MacOS checks were optional. See here: https://travis-ci.org/input-output-hk/cardano-sl/builds/256111567?utm_source=github_status&utm_medium=notification

Anyway, doesn't matter now.

**Pull request merged**
