### PR TITLE
networking benchmarks compile

### PR DESCRIPTION
**Pull request by avieth**
## Description

Building cardano-sl-networking with benchmarks will pass.

There's meant to be no significant semantic changes in here. What had to be done:

- Get rid of dodgy uses of state transformers (don't use `StateT` to express a simple fold).
- Get rid of log-warper transformed-based logging in favour of the `Trace` interface.
- Get rid of uses of mockable.

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by avieth** [comment]
@erikd I'll let you merge this (base is your branch) if/when you want it.

**Comment by avieth** [comment]
#2883

**Comment by avieth** [comment]
It seems the dependencies of benchmarks are not included by `pkgs/generate.sh`. `cardano-sl` configuration fails due to missing `criterion`. It's there in the cabal file but not in the `libraryHaskellDepends` found in `pkgs/default.nix`. Any nix masters know how to fix this? I'll bet there's some option we have to set but these things are sadly underdocumented. @iohk-devops @erikd

**Comment by erikd** [comment]
@avieth If you pull in the two commits from @disassembler on the `benchmarks-enable` branch that should fix that.

**Comment by erikd** [comment]
I've rebase my `erikd/fix-bench` branch onto `avieth/fix-bench`. Just making sure it builds locally.

**Comment by erikd** [comment]
I've pulled two commits from @avieth into my `erikd/fix-bench` branch (PR #2883 ) which is currently building.

**Comment by erikd** [comment]
Still some issues with the `stack2nix` and `cabal2nix` tools which are in the process of being fixed.

**Comment by erikd** [comment]
@avieth Don't think this PR is needed any more as the last commit in PR #2883 shows that benchmarks are indeed being built in CI. Closing it.

**Pull request closed without merging**
