### PR TITLE
Make WorkMode def more concise

### PR DESCRIPTION
**Pull request by Pastafarianist**

### CODE REVIEW

**Comment by neongreen** [comment]
needs approval from Duncan and George :peka:

**Comment by gromakovsky** [comment]
Probably doesn't deserve going to master.

**Comment by dcoutts** [comment]
> верай гут пиар

Right. This PR is "obviously" correct because `type HasLens' s a = HasLens a s a` but for the same reason it is unnecessary code churn at this stage. So I'm not going to childishly demand this be reverted but this is a waste of our time. I'm sure there are more useful things we can do at this stage.

**Comment by georgeee** [comment]
I just don't see a problem to merge such tiny changes. It's easier than keep them as PR, distracting attention of people to valuable PRs

**Pull request merged**
