### PR TITLE
[SRK-53] Bump up universum from 0.3 to 0.4.1

### PR DESCRIPTION
**Pull request by ChShersh**
New changes are written in [`universum` CHANGELOG](https://github.com/serokell/universum/blob/master/CHANGES.md#04). Probably some HLint rules should be upgraded to respect new features.

### CODE REVIEW

**Comment by neongreen** [comment]
I will bump HLint rules in this branch.

**Comment by neongreen** [comment]
> So we are waiting for updated hlint rules from @neongreen, right?

Yes, and before pushing updated hlint rules I want to push rules I already wrote to master, and _that_ requires CSL-50 to be merged. _Mda_

**Comment by neongreen** [comment]
(Well, not “requires” but it's much easier for me this way)

**Comment by gromakovsky** [comment]
@neongreen you can do it 😉 
@ChShersh conflicts appeared.

**Comment by ChShersh** [comment]
@gromakovsky I'm waiting for HLint rules update from @neongreen to fix conflicts :)

**Comment by neongreen** [comment]
^ HLint rules

**Pull request merged**
