### PR TITLE
[DEVOPS-964] Windows Cross Compilation with LTS-12.2

### PR DESCRIPTION
**Pull request by angerman**
## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🛠 New feature (non-breaking change which adds functionality)
- [x] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [x] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by parsonsmatt** [comment]
When this is not WIP, tag me and I'll leave a review, though if it's this large, a small self-review would be helpful too :smile:

**Comment by angerman** [comment]
@parsonsmatt There is #3299, which deals with most of the non-nix-infra, but cardano-sl part. If that was merged, this one would be much smaller.

**Comment by disassembler** [comment]
hydra evaluation is broken: https://hydra.iohk.io/jobset/serokell/cardano-sl-pr-3291#tabs-errors

**Comment by angerman** [comment]
@disassembler that’s on my radar. Wanted to get the rest working, prior to looking into tests and the integration part.

**Comment by jcmincke** [comment]
@angerman What do we do with this PR? Wait or close?

**Comment by angerman** [comment]
@jcmincke as mentioned else where, this can only be merged once #3459 is merged. As such it's still ongoing work.

**Comment by parsonsmatt** [comment]
I am un-requesting myself for review until this PR is in less of a WIP-state. Please feel free to request a review after :)

**Comment by erikd** [comment]
@angerman Looking forward to seeing this merged, but it needs to be rebased first, and we need to make sure the Stackage LTS version we choose uses ghc-8.4.4 (lts-12.5 and later I think).

**Comment by angerman** [comment]
This is superseded by #3868.

**Pull request closed without merging**
