### PR TITLE
network-transport-tcp connection establish error reporting

### PR DESCRIPTION
**Pull request by avieth**
## Description

Use a build of `network-transport-tcp` which uses the configured error handler in case of errors on connection establish. This means that, for instance, a failed reverse DNS lookup will be logged.

https://github.com/avieth/network-transport-tcp/commit/2634e5e32178bb0456d800d133f8664321daa2ef

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## How to merge

Send the message `bors r+` to merge this PR. For more information, see
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/bors.md).

### CODE REVIEW

**Comment by avieth** [comment]
> # Build failed
>
>    * [ci/hydra:serokell:cardano-sl:required](https://hydra.iohk.io/build/608030)

```
Building library for cardano-sl-generator-2.0.0..
[ 1 of 14] Compiling Pos.Generator.Block.Error ( src/Pos/Generator/Block/Error.hs, dist/build/Pos/Generator/Block/Error.o )
[ 2 of 14] Compiling Pos.Generator.Block.Orphans ( src/Pos/Generator/Block/Orphans.hs, dist/build/Pos/Generator/Block/Orphans.o )
[ 3 of 14] Compiling Pos.Generator.Block.Param ( src/Pos/Generator/Block/Param.hs, dist/build/Pos/Generator/Block/Param.o )
[ 4 of 14] Compiling Pos.Generator.Block.Mode ( src/Pos/Generator/Block/Mode.hs, dist/build/Pos/Generator/Block/Mode.o )
[ 5 of 14] Compiling Pos.Generator.Block.Payload ( src/Pos/Generator/Block/Payload.hs, dist/build/Pos/Generator/Block/Payload.o )
[ 6 of 14] Compiling Pos.Generator.Block.Logic ( src/Pos/Generator/Block/Logic.hs, dist/build/Pos/Generator/Block/Logic.o )
/nix/store/1m13ybazlw70srqjfv4b3wq65zjq3am2-cctools-binutils-darwin-wrapper/nix-support/add-flags.sh: fork: retry: Resource temporarily unavailable
clang-5.0: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable

<no location info>: error:
    `cc' failed in phase `Assembler'. (Exit code: 1)
[11 of 14] Compiling Test.Pos.Block.Logic.Emulation ( src/Test/Pos/Block/Logic/Emulation.hs, dist/build/Test/Pos/Block/Logic/Emulation.o )
time.setupCompilerEnvironmentPhase 14
time.unpackPhase 0
time.patchPhase 0
time.compileBuildDriverPhase 10
time.configurePhase.user 5.504
time.configurePhase.system 1.764
time.configurePhase.real 7.454
time.configurePhase 8
time.buildPhase.user 31.952
time.buildPhase.system 15.439
time.buildPhase.real 34.196
builder for '/nix/store/7rfjyz53q06snfwflfx11hvy6hi10y34-cardano-sl-generator-2.0.0.drv' failed with exit code 1
```

**Comment by avieth** [comment]
Same failure again. Issue with the bors machine?

**Comment by cleverca22** [comment]
bors clearly said it was a problem with hydra

**Pull request merged**
