### PR TITLE
[CBR-421] Remove gathering, compression and submission of log files.

### PR DESCRIPTION
**Pull request by 365andreas**
## Description

This functionality is now done in Daedalus. Consequently, we have to remove the unused code in cardano-sl.
A bug existed in this part of removed code due to the misuse of `(</>) ` operator:
https://github.com/input-output-hk/cardano-sl/blob/c1c3729b8152e99e8832128d7292429fd616e5ed/infra/src/Pos/Infra/Reporting/Wlog.hs#L68

## Linked issue
CBR-421

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [~] 🛠 New feature (non-breaking change which adds functionality)
- [~] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [~] 🔨 New or improved tests for existing code
- [~] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [~] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## How to merge

Send the message `bors r+` to merge this PR. For more information, see
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/bors.md).

### CODE REVIEW

**Comment by CodiePP** [comment]
Please, we need a review on this.

**Comment by KtorZ** [comment]
@CodiePP Is this still relevant?

**Comment by CodiePP** [comment]
> @CodiePP Is this still relevant?

yes, very much. We probably have to rebase it first.

**Comment by CodiePP** [comment]
This PR is not essential anymore. Will close it.

**Pull request closed without merging**
