### PR TITLE
Additions to the spec

### PR DESCRIPTION
**Pull request by edsko**
See commit messages for details.

### CODE REVIEW

**Comment by edsko** [comment]
Started work on minimum balance computation. Very much WIP at the moment.

@adinapoli-iohk Will rename the commits before declaring this ready to merge :)

**Comment by edsko** [comment]
Rebased on `develop`.

**Comment by edsko** [comment]
@dcoutts I think this is ready to be merged now, pending your review obviously. @adinapoli-iohk you'll be happy to know I squished all the comments and renamed the single "final boss" commit to include the name of the YouTrack issue.

**Comment by adinapoli-iohk** [comment]
> you'll be happy to know I squished all the comments and renamed the single "final boss" commit to include the name of the YouTrack issue.

@edsko Very proud of you, son! :trollface:

**Pull request merged**
