### PR TITLE
[TW-160] Reset failure state from listeners eagerly

### PR DESCRIPTION
**Pull request by adinapoli-iohk**
@dcoutts @avieth We should be on the right track now! 🙏 

Full context: https://issues.serokell.io/issue/TW-160

### CODE REVIEW

**Comment by avieth** [comment]
CI fails saying `ERROR: you need to run ./pkgs/generate.sh and commit the changes`. It's a surprise to me. I thought that was only necessary when something in the stack/cabal files changes.

**Comment by adinapoli-iohk** [comment]
> CI fails saying

😞  Lately the CI have been acting quite unpredictably. There was a discussion going on in the devops channel. @domenkozar and @cleverca22 explained (I'm summarising) that this can happen due to the interaction between `stack2nix`, stack, and the fact that upper bounds in a cabal manifest can change retroactively with _revisions_, which might make build non-reproducible. 

What I can try to do is merge the current master into this branch and pray the CI gods, as I cannot generate `pkgs/generate.sh` myself due to https://github.com/input-output-hk/stack2nix/issues/56 (I'm on darwin 😭  )

**Comment by avieth** [comment]
> What I can try to do is merge the current master into this branch and pray the CI gods, as I cannot generate pkgs/generate.sh myself due to input-output-hk/stack2nix#56 (I'm on darwin :sob: )

Ok let's see what happens with CI now and if it still fails, I'll `pkgs/generate.sh` and push if there's any change.

**Comment by gromakovsky** [comment]
The fix arrived to master recently, you can merge/rebase https://github.com/input-output-hk/cardano-sl/commit/924278fa44c4d4903273e1b5af4ae63dda16918f

**Comment by adinapoli-iohk** [comment]
Done! No clue if regenerating the packages set is necessary, but I guess Travis will soon tell us.

**Comment by dcoutts** [comment]
OSX build timing out :-(

**Pull request merged**
