### PR TITLE
drop test.hs

### PR DESCRIPTION
**Pull request by angerman**
## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by erikd** [comment]
@angerman Why are we dropping that? Thats the `main` function of the tests for that module.

**Comment by avieth** [comment]
> @angerman Why are we dropping that? Thats the main function of the tests for that module.

Oh right, we should have checked the cabal file first.

I'm for changing it to `Test.hs`. Capitalised file names seem to be the norm in Haskell projects.

**Comment by erikd** [comment]
I used to a convention where module names are capitalized but file like this which contain a `main` function are not.

**Comment by erikd** [comment]
Hmm, so it was doing the right thing (running tests I added and the ones @coot) added, but the file name case thing mean that it all worked sort of by accident.

**Comment by erikd** [comment]
#2861 supercedes this.

**Pull request closed without merging**
