### PR TITLE
added documentation to direct people towards the new gitter.im channel

### PR DESCRIPTION
**Pull request by CaptJakk**
Created a gitter channel for the cardano project in general, and added a cardano-sl room. I just added documentation to the CONTRIBUTING.md to point people towards this. I want to get to a point where myself and other aspiring open source developers have a place to go to talk about the tech in a close to real time environment. Most discussion media are either reasonably slow, one-way, or too heavily focused on price movements and not enough on tech. By adding this medium I hope to exclude most price discussion in favor of tech development in a medium that can get close to real time communication for developers that otherwise wouldn't really know where to start.

### CODE REVIEW

**Comment by CaptJakk** [comment]
fixes #2245

**Comment by denisshevchenko** [comment]
@CaptJakk Thanks. Actually we already have a chat: https://chat.cardanohub.org/. What's your opinion: do we need another one?

**Comment by CaptJakk** [comment]
I don't believe we need another one but I think we should direct people towards that chat in the contributing section. The idea is that the chat should only be about technology and development. Not anything about news stories or price movements. If the chat you showed above exhibits those properties I see no need for an additional one. That said, gitter is more or less the standard for github based chat. It's up to you. let me know

**Comment by CaptJakk** [comment]
After talking with various others in the community it seems that there is demand for keeping this channel around as a way to teach newcomers about the codebase. There seems to be an opinion of some of the newcomers that the one that exists on chat.cardanohub.org hasn't been helpful and that they prefer one in gitter. So I'm thinking having a gitter channel we can point people to is a good idea. I'd like to get this pulled in although for reasons I can't explain the build is failing lol. I didn't change any code. I'll see if I can rebase off of development and get a better build story.

**Comment by denisshevchenko** [comment]
> The idea is that the chat should only be about technology and development. If the chat you showed above exhibits those properties I see no need for an additional one.

That chat (https://chat.cardanohub.org/) contains a list of channels, including `developers`. So I don't see why should we use another chat.

But I totally agree with you - this chat should be mentioned in the `CONTRIBUTING.md`. Probably you can change it right in this PR? Common chat is https://chat.cardanohub.org/, developers channel is https://chat.cardanohub.org/channel/developers.

**Comment by CaptJakk** [comment]
I updated to PR to reflect the existence of the officially sanctioned chat. However, I wanted to continue to include the section about the gitter so at least people know about it. Gitter was designed as a tool to allow developers to chat about things on github and as such, I think fostering a good gitter community is a good idea. However, I did mention that it is not official in the way that chat.cardanohub.org is. I'd like to get this in as is, but I can remove the reference to the gitter chat if strictly necessary.

**Comment by SebastienGllmt** [comment]
Just an FYI I'm pretty sure http://chat.cardanohub.org is deprecated (although maybe not officially).

Now everything is migrated to Telegram in a bunch of chatrooms run by the Cardano Foundation.
Cardano developers: https://t.me/CardanoDevelopersOfficial
Cardano general: https://t.me/CardanoGeneral
(etc)

**Comment by CaptJakk** [comment]
I can make that change for sure, I just need to know what the actual consensus is on chat.

**Comment by SebastienGllmt** [comment]
I would say remove the gitter and the rocket chat. The dev community is not that large so let's congregate on the Telegram for now and if we ever feel the need to expand to a better system in the future we will tackle it then.

**Comment by CaptJakk** [comment]
@erikd , since it looks like you're the new code owner for this, can we get this merged. I've been trying to get this small documentation update merged for 2 months now.

**Comment by CaptJakk** [comment]
I think it'd be cool, it would encourage community devs to be able to help.

**Comment by CaptJakk** [comment]
That said, @parsonsmatt, if you're saying that you use slack internally. It may be better to use the gitter channel (https://gitter.im/cardano-dev). Since that actually has the option for multiple discussions in multiple channels. Which is something that telegram is not great at. I personally prefer the gitter channel, and was actually the original version of this commit. This is what the ethereum project uses and it has been highly successful since it ties into github etc.

**Comment by CaptJakk** [comment]
I feel like a broken record...But can someone tell me either why this hasn't been merged. Either I need to make adjustments or it fundamentally isn't wanted, but I'd kind of like to put this to rest finally. What's the deal?

**Comment by CaptJakk** [comment]
Committed a rebase with develop and repushed. It should pass all the checks that are passing on the develop branch, if they aren't then I have no idea what is wrong with the CI, it has not ever completed for me, at least one fails to start usually. We'll see what happens this time.

**Comment by parsonsmatt** [comment]
Ah, we actually do need an empty commit here to this branch -- it appears that the rebase commits were recognized by our CI and not rebuilt :\

**Comment by CaptJakk** [comment]
Just submitted it. We'll see what happens but I have never gotten the buildkite things to run even when I was doing regular commits.

**Comment by parsonsmatt** [comment]
I've pinged our devops folks to take a look at that issue

**Comment by parsonsmatt** [comment]
Merged in #3025

**Pull request closed without merging**
