### PR TITLE
Faucet rebased and squashed against develop

### PR DESCRIPTION
**Pull request by boothead**
See #3513 and #2939 which contain the same work but are hard to impossible to merge back to develop

cc @erikd

### CODE REVIEW

**Comment by jcmincke** [comment]
Not sure this code should go into develop. It should go into release/1.3.1.
Don't merge, I am checking it with Ben

**Comment by erikd** [comment]
@jcmincke The faucet code is already in the release/1.3.1 release. This is simply the port of that code into the develop branch. Porting it separately is a cleaner more reliable way of moving code between branches than the huge, potentially unreliable "git merge"s we have been doing.

**Comment by jcmincke** [comment]
@erikd Thanks, when do you think it can be merged?

**Comment by erikd** [comment]
Well it obviously cannot be merged until it passes CI.

**Comment by rvl** [comment]
This is PR missing my commit ce421d82c44510bc8c74abbadd654ef54cad2651 from release/1.3.1. That change helps with local manual testing of faucet.

**Comment by boothead** [comment]
@rvl - Yes I think that commit should be included

**Pull request merged**
