### PR TITLE
Remove docs/monads.md

### PR DESCRIPTION
**Pull request by erikd**
This document is out-of-date and does not reflect out current position
on some of these issues, particularly in relation to the use of typeclass
constraints. We therefore think its better to remove it than keep
something that no longer reflects what we consider best practice.

Going to leave this open for at least a week for discussion.

### CODE REVIEW

**Comment by avieth** [comment]
> Going to leave this open for at least a week for discussion.

And probably at least 2 weeks for CI to pass! It's amazing that it failed for this patch.

**Comment by avieth** [comment]
> I'd like to see a detailed analysis of what's wrong with this, what is okay, and how we can do the wrong things differently. I think this would be especially helpful for our newer team members. Anyone have some free time and strong opinions?

https://www.reddit.com/r/haskell/comments/8p6rjv/guidelines_for_effect_handling_in_cardano_sl/e09l4ee/?context=2

https://www.reddit.com/r/haskell/comments/8m9y91/how_does_one_do_dependency_injection_manually_in/dzmk8wl/

Also see the original pull request https://github.com/input-output-hk/cardano-sl/pull/1894

**Comment by KtorZ** [comment]
_up_ 
Should we trigger a new build somehow?

**Comment by adinapoli-iohk** [comment]
> Should we trigger a new build somehow?

I don't think that's necessary -- recently we changed the AppVeyor builds to be "optional" (i.e. not mandatory for a PR to be mergeable), so once happy we can merge as-it-is, methinks :)

**Comment by erikd** [comment]
Going to merge this in about 24 hours time.

**Pull request merged**
