### PR TITLE
Switch to time-warp-nt/master

### PR DESCRIPTION
**Pull request by int-index**
prosti @gromakovsky

### CODE REVIEW

**Comment by gromakovsky** [comment]
Timeouts are back :(

**Comment by int-index** [comment]
> Timeouts are back :(

Haddock causes them, notice that `travis-ci/push` doesn't time out, but `travis-ci/pr` does — the difference between them is whether `--haddock` is used.

**Comment by gromakovsky** [comment]
Maybe we can separate haddock as we did it for hlint? Does haddock need anything to be compiled?

**Comment by int-index** [comment]
As far as I know, Haddock needs the entire project (and deps) to be built with `--haddock`.

**Comment by gromakovsky** [comment]
I merged it because currently all travis builds fail because of time limit because of haddock. Everything else is correct.

**Pull request merged**
