### PR TITLE
[CSL-1635] Read own UTXO from DB with streaming in 'auxx'

### PR DESCRIPTION
**Pull request by int-index**

### CODE REVIEW

**Comment by georgeee** [comment]
Agree, let's not affect benchmarks

**Comment by gromakovsky** [comment]
Tbh, I have no idea what to do with this PR now. Let's wait until things settle down.

**Comment by georgeee** [comment]
Required for delegation testing (before proper lwallet is established)

Not necessary to be merged to mainnet and maybe even `master` (eventually)

**Comment by int-index** [comment]
Good idea, I'll make the necessary changes after I deal with Nix failing (the script is taking its time).

**Pull request merged**
