### PR TITLE
Merge cardano-0.5

### PR DESCRIPTION
**Pull request by Martoon-00**
Contains changes which modify logging in wallet

### CODE REVIEW

**Comment by Martoon-00** [comment]
Ahah, I tut postiral polovinu izmennii sdelannyh do menya, no who cares :peka:

**Comment by neongreen** [comment]
nu vot tak ya i dumal, chto nastanes odnazhdy tot den, kogda ya skazhu “naverno ok”, a kto-to takoy “ahaha ya narochno sdelal ne ok, POPALSYA”

**Comment by Martoon-00** [comment]
Ahahaha bliin, fail

**Comment by neongreen** [comment]
spat idi

**Comment by Martoon-00** [comment]
@pva701 Please take a look, I overwrote some changes you made here

**Pull request merged**
