### PR TITLE
[CSE-232] Allow CORS request by `cardano-mainnet`

### PR DESCRIPTION
**Pull request by sectore**
See https://issues.serokell.io/issue/CSE-232

### CODE REVIEW

**Comment by ksaric** [comment]
@sectore Testnet too. 
`*` doesn't look that bad now, does it? :smile:

**Comment by akegalj** [comment]
@domenkozar websocket connection is failing if we don't specify correct CORS (alternatively we can make it less restrictive - but lets not do that).

Can you confirm that the list of domain names for explorer is complete here.

**Comment by domenkozar** [comment]
@akegalj looks good to me now, we should update this later on.

**Comment by domenkozar** [comment]
There is now a separate PR for 1.0

**Pull request closed without merging**
