### PR TITLE
[CSL-2135] hotfix for #2239

### PR DESCRIPTION
**Pull request by ksaric**
https://iohk.myjetbrains.com/youtrack/issue/CSL-2135

Original PR - https://github.com/input-output-hk/cardano-sl/pull/2239

I hope this is ok, I added the parameter `walletTxCreationDisabled` as discussed with @adinapoli-iohk .

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
@ksaric Probably a good idea to wait for [this other PR](https://github.com/input-output-hk/cardano-sl/pull/2256) to get merged first if we want to get a smaller diff which doesn't mention `walletTxCreationDisabled`. Will review after the meeting!

**Comment by ksaric** [comment]
Rebased on top of `master`, added comment.

**Comment by ksaric** [comment]
I can remove my last commit with nix file regeneration since something weird is happening here and I have no clue what.

**Comment by adinapoli-iohk** [comment]
Superseded by https://github.com/input-output-hk/cardano-sl/pull/2301

**Pull request closed without merging**
