### PR TITLE
[CSL-1890] Implement update pass endpoint

### PR DESCRIPTION
**Pull request by Martoon-00**
Rebased #1957

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
@Martoon-00 Don't be mad at me, but we now have a proper feature branch called `feature/new-wallet`. Would you open the PR there? 😁

**Comment by Martoon-00** [comment]
Loool I don't understand how it happened that I rebased against master :man_facepalming:

**Comment by Martoon-00** [comment]
Ah okay, I just forgot to change base :smile: 
Is it ok now @adinapoli-iohk ?

**Comment by Martoon-00** [comment]
Oh no, it's not ok, sorry /

**Pull request closed without merging**
