### PR TITLE
Remove useless 'void' [blocked: build failed, investigation pending]

### PR DESCRIPTION
**Pull request by gromakovsky**

### CODE REVIEW

**Comment by neongreen** [comment]
Tests have failed: https://buildkite.com/input-output-hk/cardano-sl/builds/1312#9c1b53b1-4292-464e-887b-6b3d52d9ed07/254-961

Somebody should investigate this. Has it been noticed already? Is there an issue?

**Comment by gromakovsky** [comment]
Yes: https://iohk.myjetbrains.com/youtrack/issue/CSL-2240

**Comment by gromakovsky** [comment]
Let's keep this PR open for a while. I don't know which builds are stored in BK history, so I think it's safer (we don't want to lose that output).
This PR is not important and hopefully CSL-2240 will be addressed within this sprint.

**Comment by neongreen** [comment]
[cardano-sl_build_1312_cardano-x86-64-darwin.log](https://github.com/input-output-hk/cardano-sl/files/1690396/cardano-sl_build_1312_cardano-x86-64-darwin.log)

commit: 6ed79a372e7044eb36f417dbb6c0f002595c566a

**Comment by jcmincke** [comment]
Closed because this PR is just too old.

**Pull request closed without merging**
