### PR TITLE
[CSL-1633] Remove recoveryCommGuard from reportRollback

### PR DESCRIPTION
**Pull request by volhovM**

### CODE REVIEW

**Comment by dcoutts** [comment]
@volhovM @gromakovsky Can you explain this change? Previously we only reported this misbehaviour when not in recovery mode. Now we report it always. It sounds plausible but I'd like some more detailed reason.

**Comment by volhovM** [comment]
@dcoutts this code became unreachable after last recovery mode refactoring (took place in june i suppose). Main idea was to assume that any amount of blocks greater than one triggers recovery mode. So whenever we rollback, we're in recovery mode. So this reporting wasn't ever triggered. Now it's triggered unconditionally because we still need to report rollbacks and we actually don't distinguish between deep (>k) and shalow recovery.

**Comment by dcoutts** [comment]
Ok, so this is a change that is plausible on the face of it, but is not strictly necessary for mainnet. We should decide if things like this are OK for mainnet if we include them into an RC update first.

**Comment by georgeee** [comment]
Necessary for mainnet and much desirable for testnet update b/c it's only way block rollbacks are reported
Otherwise we would need to reverse-engineer logs to get info about rollbacks

**Comment by georgeee** [comment]
Duncan:
>  Ok you commented on the ticket. But what is the argument in full? That rollbacks only occur in recovery mode, and so the previous code where it would only report when not in recovery mode would mask all such reports. Right?


George:
> Recovery mode is active since we're at least 1 block out-of sync with network latest known tip (this is not well, but how it is for now)
Typical rollback would be that you have weaker chain which will have tip say `(0, 5)` and stronger chain with `(0, 10)`, one not being continuation of other. Weaker chain node will be in recovery

**Comment by dcoutts** [comment]
So the overall argument here is this:

This change is needed for reporting of block rollback via the reporting server. That is because to be in a situation where block rollback occurs the node must already be in recovery mode. The current code masks the reporting when in recovery mode and so the report is never generated. The change removes the check for recovery mode so that the report is generated.

However this change is not strictly necessary for mainnet because our devops team get the information on block rollbacks automatically from the log files of the nodes we run, and not from the edge nodes via the reporting server. This is a sensible fix but it would be fine to include in a later update.

**Pull request merged**
