### PR TITLE
[CSL-1079] Switch to LTS-8.12

### PR DESCRIPTION
**Pull request by gromakovsky**
It allowed to do some clean-up in stack.yaml.

@domenkozar allowed me to do it as long as CI passes. This PR will show it :)

### CODE REVIEW

**Comment by volhovM** [comment]
Latest is 8.12. What's the motivation to go with 8.10?

**Comment by gromakovsky** [comment]
Just random number which supports necessary version of unordered-containers and derive.

**Comment by gromakovsky** [comment]
Windows build fails with
```
[00:26:40]     ghc.EXE: unable to load package `foundation-0.0.6'
[00:26:40]     ghc.EXE: C:\s\snapshots\cf31b79a\lib\x86_64-windows-ghc-8.0.2\foundation-0.0.6-6X64i8i17nuLDNnFMlu4tb\HSfoundation-0.0.6-6X64i8i17nuLDNnFMlu4tb.o: unknown symbol `gethostbyname2'
```
And I have no idea how to fix it.

**Comment by vincenthz** [comment]
lts-8.12 fixes it.

**Pull request merged**
