### PR TITLE
[CO-354] Fix SafeCopy instance for `AddrAttributes`

### PR DESCRIPTION
**Pull request by mhuesch**
## Description
    
    Until now, the instance was derived, and thus was broken when we
    modified `AddrAttributes` in earlier release/1.3.1 commits by adding
    the `aaNetworkMagic` field.
    
    In order to make future modifications to the instance easier in the
    future, we simply de/serialize a ByteString from the `Bi` instance
    for `Attributes AddrAttributes`.
    
    Since there is a very low probability of collisions between the old
    SafeCopy binary format and the new CBOR/Bi binary format, we attempt
    to decode via `Bi` first, and if that fails (either an invalid length
    ByteString, or a CBOR failure), then we do a "legacy" decode, where
    we only look for 2 fields (`AddrAttributes` had 2 before we added
    `aaNetworkMagic`) and fill in `NMNothing` so that the existing
    mainnet/staging databases are correctly read.

## Linked issue

https://iohk.myjetbrains.com/youtrack/issue/CO-354

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [~] 🛠 New feature (non-breaking change which adds functionality)
- [~] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [~] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [x] 🔨 New or improved tests for existing code
- [~] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist
- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [~] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## QA Steps
```
$ stack test
$ EXISTING_WALLET_PATH=<path>
$ stack exec cardano-node -- --topology=docs/network/example-topologies/mainnet-staging.yaml --configuration-key mainnet_dryrun_full  --db-path ../staging-db --tlscert ../tls-certs/server.crt --tlskey ../tls-certs/server.key --tlsca ../tls-certs/ca.crt --no-client-auth --wallet-db-path $EXISTING_WALLET_PATH
```

### CODE REVIEW

**Comment by mhuesch** [comment]
@adinapoli-iohk I think you're preference lines up with my intention when I was writing the code, can you elaborate on the differences between the implementation and what you were imagining?

In [`getLegacy`](https://github.com/input-output-hk/cardano-sl/blob/036f1b9405ce35d0462cc0d6f4033119597b082b/lib/src/Pos/SafeCopy.hs#L153-L156) I define the backwards compatible decode, but don't invoke it. Then we [read in bytes without consuming input](https://github.com/input-output-hk/cardano-sl/blob/036f1b9405ce35d0462cc0d6f4033119597b082b/lib/src/Pos/SafeCopy.hs#L163-L166), so that we do not commit to one parsing path. We check that [the CBOR length is valid](https://github.com/input-output-hk/cardano-sl/blob/036f1b9405ce35d0462cc0d6f4033119597b082b/lib/src/Pos/SafeCopy.hs#L167) and that [we can decode CBOR](https://github.com/input-output-hk/cardano-sl/blob/036f1b9405ce35d0462cc0d6f4033119597b082b/lib/src/Pos/SafeCopy.hs#L169) before we return the "migrated format" result. So even though it occurs as the bottom-most code block, the CBOR function can be thought of as running first, I think.

**Comment by adinapoli-iohk** [comment]
@mhuesch As said it's a minor (and probably debatable) alternative implementation, which would have been along the lines of:

```haskell
getCopy = contain $ do
  resE <- Bi.deserialise' ...
  case resE of
      Left e -> ... getLegacy ..
      Right x -> return x
```

I.e. attempting the deserialisation first thing, skipping the look-ahead check, and then only if we fail we try the legacy one. But let me repeat that I was just playing the devil's advocate here, I think your implementation is an excellent one. 😉

**Comment by dcoutts** [comment]
Otherwise, looks good.

**Comment by mhuesch** [comment]
@dcoutts After digging into your suggestion a bit, my conclusion is that it's better/safe, but `ensure` is problematic, because it returns the full remaining input. Thus we consume too much and the fields that come "after" the one our SafeCopy instance is parsing get consumed as well, so they fail with a `demandInput` error. I think we want something like `ensureAndTake` which ensures there are `n` bytes available, but only takes those `n` bytes.

**Comment by dcoutts** [comment]
I think we can actually go simpler still. We don't need to parse the encoding of the bytestring manually. We can just use a normal `safeGet` inside a `lookAheadE` to get the bytestring and try to decode that.

```
getCopy = contain $ do
    -- Try decoding as a BSL.ByteString containing the new format, but if that
    -- fails go for the legacy format.
    tryNonLegacy <- Cereal.lookAheadE (Bi.decodeFull <$> safeGet)
    label $ case tryNonLegacy of
      Left  _             -> getLegacy
      Right attrAddrAttrs -> pure (attrData attrAddrAttrs)
  where
    label     = Cereal.label "Pos.Core.Common.AddrAttributes.AddrAttributes:"
    getLegacy = AddrAttributes <$> safeGet
                               <*> safeGet
                               <*> pure NMNothing
```

**Comment by mhuesch** [comment]
@dcoutts I'm still mystified by `lookAheadE`'s behavior, as it is described to do (I think) what we want it to do, yet it behaves differently.

I figured out how to use `Alternative` to run the non-legacy parser first, and if that fails, to then run the legacy parser. This seems fairly clean & safe. Just updated the PR.

**Pull request merged**
