### PR TITLE
[DO NOT MERGE] Cardano sl 0.6 exchanges

### PR DESCRIPTION
**Pull request by akegalj**
Don't merge.

This PR contains cherry picked:
 * [x] https://github.com/input-output-hk/cardano-sl/pull/1610

This PR are going to be merged to this branch after CI passes:
 * [x] https://github.com/input-output-hk/cardano-sl/pull/1592

### CODE REVIEW

**Comment by akegalj** [comment]
@Martoon-00 please verify did I cherry pick correctly #1610 . I run into a conflict so there was some work required to merge it

**Comment by akegalj** [comment]
@Martoon-00 would you mind editing this PR with to explain the changes you made in https://github.com/input-output-hk/cardano-sl/pull/1610 so that clients know how to use them.

**Comment by gromakovsky** [comment]
@akegalj @Martoon-00 is this PR (and branch) still needed?

**Comment by Martoon-00** [comment]
I believe it's not, thanks for reminder

**Pull request closed without merging**
