### PR TITLE
Add core support for protocol level MultiSig

### PR DESCRIPTION
**Pull request by vincenthz**
## Description

* Extend AddressSpendingData to support having multiple parties computing
  an address using the hash of the participants' public key.
* Extend TxWitness to take a list of MultisigWitness which are either the public key
  hash if not participating or as a signatory the public key and it's associated signature.

The multisig signature is valid if the number of signatures is equal or above
to the expected threshold. if any present signature is also invalid, the
overall multisig signature is considered invalid too even if the expected
number of valid signatures is met.

While the order of participants is not enforced, it is necessary to specify the
same order between the witnesses and how the address has been generated, since
the order is required to compute the expected address.

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [~] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by erikd** [comment]
The code here looks fine, but shouldn't there be tests as well?

**Comment by vincenthz** [comment]
@erikd yes it should ideally, but I couldn't find any existing tests for AddressSpendingData/Witnessing

**Comment by erikd** [comment]
None of this code has enough tests, and I'd really like to avoid adding still more code without tests. As it is, my team is having to write tests in order to some of the refactorings this code so badly needs.

**Comment by jcmincke** [comment]
Closed because this PR is just too old.
Does not seem relevant at the moment

**Pull request closed without merging**
