### PR TITLE
[CSL-1172] Port "join Kademlia after node is up" to cardano-sl-0.5-rc

### PR DESCRIPTION
**Pull request by arybczak**
Port of d574a7a48c671e202eda1d0f591769561aa721df.

### CODE REVIEW

**Comment by arybczak** [comment]
I'm not sure if second commit is correct, please have a closer look.

**Comment by avieth** [comment]
> I'm not sure if second commit is correct, please have a closer look.

I think it's ok.

**Comment by neongreen** [comment]
Is this still needed?

**Comment by gromakovsky** [comment]
@avieth can I close it? I guess it's completely outdated.

**Comment by avieth** [comment]
> @avieth can I close it? I guess it's completely outdated.

Indeed

**Pull request closed without merging**
