### PR TITLE
[DAE-106] refactor util-scripts for frontend usage

### PR DESCRIPTION
**Pull request by DominikGuzei**
Moves the `clean.sh` and `build-daedalus-bridge.sh` scripts from `./scripts/` to `./util-scripts` folder and adds a new simplified `build-mac-production.sh` which includes all necessary commands for building prod on mac.

### CODE REVIEW

**Comment by ChShersh** [comment]
[`clean_db.sh`](https://github.com/input-output-hk/cardano-sl/blob/15b8b777fde5a8ab4a85af71affeffdf31ad219c/util-scripts/clean_db.sh) script can be removed because same cleaning is done in `util-scripts/clean-local-data.sh` now.

**Comment by DominikGuzei** [comment]
@ChShersh hmm … i don't see the `./util-scripts/clean_db.sh` file on my branch, maybe this has already been removed in latest `cardano-sl-0.2` branch?

**Comment by DominikGuzei** [comment]
Ah i think you added it on `master` but that has not made it into this release …

**Comment by ChShersh** [comment]
Yes, I also just noticed this commit only for release. Anyway, those scripts are useful even in `master` for developers. So my script should be obsolete if favor of those from `./scripts/`. Probably this commit can be cherry-picked in `master`.

**Comment by akegalj** [comment]
I see `./util-scripts/build-mac.sh ` already has some cleaning functionality with `-c` flag https://github.com/input-output-hk/cardano-sl/blob/cardano-sl-0.2/util-scripts/build-mac.sh#L61 ?

**Comment by DominikGuzei** [comment]
@akegalj that's correct but it's useful to keep a separate (full blown) clean script at hand here.

**Comment by DominikGuzei** [comment]
@darko-mijic @akegalj or @jagajaga please merge 😉

**Pull request merged**
