### PR TITLE
Update CODEOWNERS file

### PR DESCRIPTION
**Pull request by erikd**
As a first pass, replace Serokell people with my name.

I am also looking for others to share the load, either for particular components (whether they are currently listed or not) or globally. If people want to be added let me know and I'll add them in this PR.

Update: I'll collect all the volunteers and distribute them as per their wishes on Tuesday of next week to give people time to look at this.

Update II: People should volunteer for things that they work on, are closely related to what they work on or things they are specifically interested in.

### CODE REVIEW

**Comment by denisshevchenko** [comment]
@erikd Could you remove me from **Documentation** please? I don't work with documentation anymore. And please add me in the **Wallet** team.

**Comment by erikd** [comment]
Note to self: Replace Domen's name with Jake's.

**Comment by domenkozar** [comment]
Could you remove me from the CODEOWNERS file please? Thanks!

**Comment by domenkozar** [comment]
Thanks! :)

**Comment by erikd** [comment]
@adinapoli-iohk added you to `update` along with @parsonsmatt .

Will merge this when CI lets me.

**Pull request merged**
