### PR TITLE
fix wrong order of last transactions

### PR DESCRIPTION
**Pull request by kissinter**
## Description

The 'getLastTxs' function may always get wrong order of last transactions

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [~] 🛠 New feature (non-breaking change which adds functionality)
- [~] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [~] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [~] 🔨 New or improved tests for existing code
- [~] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [~] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [~] I have added tests to cover my changes.
- [~] All new and existing tests passed.

## How to merge

Send the message `bors r+` to merge this PR. For more information, see
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/bors.md).

### CODE REVIEW

**Comment by disassembler** [comment]
@kissinter can you check if this is a problem still with the https://github.com/input-output-hk/cardano-wallet repo and if so, submit a PR there instead?

**Comment by kissinter** [comment]
> @kissinter can you check if this is a problem still with the https://github.com/input-output-hk/cardano-wallet repo and if so, submit a PR there instead?
Thanks for your reply, i don't understand why you tell me to check the cardano-wallet repo. 
The 'getLastTxs' i mentioned above is in the explorer module. I may misunderstand something, this is my first PR with  github. @disassembler

**Comment by disassembler** [comment]
oh sorry, thanks for the clarification. I should have looked at the diff!

**Comment by disassembler** [comment]
@kissinter can you provide screenshots of the problem before the change and after so I can see what it's fixing?

**Comment by kissinter** [comment]
Sorry, too busy recently.
I launched a cluster built on release/3.0.1 and created some transactions.
Then i requested "api/txs/last" api provided by explorer. 
And i got results below (It was already in the wrong order):


After new block was created, i requested again and got a reversed version of last request :


If i request in every new slot, the result will reverse again and again.

Then i fixed the bug and got the right result:


Forgive my poor English. Thanks!
@disassembler

**Pull request closed without merging**
