### PR TITLE
Add a script to generate package dependency graph

### PR DESCRIPTION
**Pull request by erikd**
As per title.

Please let me know if I have sinned and will be going to $hell.

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
@erikd If interested, this could be complementary to yours:

https://github.com/input-output-hk/cardano-sl/pull/1248

**Comment by mhuesch** [comment]
@erikd I've just opened a PR to your branch adding my text rendering of the current, simplified dep graph. Here's [the commit](https://github.com/input-output-hk/cardano-sl/pull/3184/commits/a4cab24fc88f04dee47c8a606afe87150f08cf32) also, if you want to cherry pick.

**Comment by erikd** [comment]
@mhuesch would be nice to have a command line flag for external deps as well. We *will* need that at some point.

**Comment by erikd** [comment]
Closing in favor of #3227

**Pull request closed without merging**
