### PR TITLE
[CSM-320] Regenerate genesis

### PR DESCRIPTION
**Pull request by georgeee**

### CODE REVIEW

**Comment by gromakovsky** [comment]
Why is it needed btw?

**Comment by georgeee** [comment]
@gromakovsky AFAIK, current master fails to start in prod mode

**Comment by gromakovsky** [comment]
```
cardano-node: Failed to read genesis: Attempted to read too many bytes for StaticSize 28 Data.ByteString.ByteString. Needed 28, but only 22 remain.
GenesisCoreData
CallStack (from HasCallStack):
  error, called at src/Debug.hs:43:11 in universum-0.4.3-CkMiNAiq0KBB5vO0r3nIZM:Debug
```
Okay, indeed.

**Comment by gromakovsky** [comment]
It works!

**Pull request merged**
