### PR TITLE
Fix launching demo for explorer. Add relative paths

### PR DESCRIPTION
**Pull request by akegalj**
Adds relative paths in demo , fixes launching from different path then cardano-sl repo

### CODE REVIEW

**Comment by ksaric** [comment]
There are issues with the CI here. I restarted yesterday but it's failed again.

**Comment by akegalj** [comment]
@ksaric can you try merging latest master to this branch - it should fix the problem as I understood @gromakovsky

**Comment by ksaric** [comment]
Again, a timeout on Mac if I'm not mistaken. I restarted the build.

**Comment by gromakovsky** [comment]
1. Only appveyor timeouts were fixed. MacOS timeouts are still our headache.
2. For this particular PR I find it acceptable to merge already (3 builds passed, including `travis-ci/pr`, only mac os timed out).

**Pull request merged**
