### PR TITLE
[CSL-1655] Ensure public logs contain no sensitive data

### PR DESCRIPTION
**Pull request by pva701**
We don't print the following messages to the public logs anymore:
1. Logs about creating a block by ourselves
2. Our DHT-key
3. CHash of addresses in wallet tracking
4. GodTossing logs

### CODE REVIEW

**Comment by pva701** [comment]
@gromakovsky welcome to diss

**Comment by dcoutts** [comment]
We would need a version of this for the 1.0 branch to consider it for mainnet.

**Comment by pva701** [comment]
@martoon review plz

**Comment by pva701** [comment]
closed due to 
https://github.com/input-output-hk/cardano-sl/pull/1666

**Pull request closed without merging**
