### PR TITLE
[CSL-2154]+ [CSL-2165] 'getHistory' improvements

### PR DESCRIPTION
**Pull request by pva701**
This PR:
1. Speeds up 'getHistoryLimited'. Now we construct `CTx` only for response history entries
2. Adds 'since' parameter to `/api/txs/histories` enpoint, which accepts time in seconds

TESTED

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
Thanks @pva701 !

Just trying to anticipate the review from @dcoutts: Can we have this PR as two separate ones? the fact this PR is fixing two issues but is being bundled into one makes reviewing, merging and cherry picking harder 😉 

May I suggest:

- One single commit PR which fixes [CSL-2154]
- One single commit PR which fixes [CSL-2165]

Thanks a ton!

**Comment by adinapoli-iohk** [comment]
@pva701 Ping? 😉 

I think having these as separate PRs would make more sense. Also be aware that the work @nc6 is doing on the DB consistency is also touching `getHistory`, you guys might find useful to collaborate on the shared goal 😉

**Comment by adinapoli-iohk** [comment]
> regarding two separate PRs: CSL-2165 must be based on CSL-2154 PR, so does it make sense to split them?

It does in my opinion 😉  You can open the second using the first as the base branch. The idea is to do incremental changes, so we can test them in isolation -- this will be very important going forward with the QA team and the work Anatoli is doing 😉 

Thanks a lot @pva701 !

**Comment by pva701** [comment]
so, I closed this PR, and opened two others:
https://github.com/input-output-hk/cardano-sl/pull/2414
https://github.com/input-output-hk/cardano-sl/pull/2415

the first one should be reviewed and merged at first because the second one is based on the first

**Pull request closed without merging**
