### PR TITLE
Hotfix/csl 1031

### PR DESCRIPTION
**Pull request by ksaric**
I don't have rights to push to `cardano-sl-0.4-mid`, this is what should be done.
Alas, it builds!

### CODE REVIEW

**Comment by gromakovsky** [comment]
🤔

**Comment by gromakovsky** [comment]
Okay, it seems I have no chances to understand our workflow in this life.

**Comment by ksaric** [comment]
@gromakovsky Sorry for this, but `explorer` needs to be finished until monday, and I need to have this in order to see if an issue https://issues.serokell.io/issue/CSM-217 is still there.

**Comment by gromakovsky** [comment]
> needs to be finished until monday,

Ok, as I said in #cardano-sl-general this PR shouldn't exist in general, but I don't know how blocked you are (which implies that if you are blocked then exception can be made).

> I need to have this in order to see if an issue https://issues.serokell.io/issue/CSM-217 is still there.

This reasoning is strange though. If you needed to test something, why couldn't you just point explorer to some temporary branch which is merge of `cardano-sl-0.4-mid` and this PR?

**Comment by ksaric** [comment]
Honestly, it didn't even occur to me. :disappointed: Also, there seem to be a lot of issues, and I think it's somehow safer to merge it on the "right" branch and test it from there? Again, I understand the workflow, sorry for messing things up.

**Comment by gromakovsky** [comment]
> Also, there seem to be a lot of issues, and I think it's somehow safer to merge it on the "right" branch and test it from there?

Well, the point is that CSL-1031 will be eventually merged to `cardano-sl-0.4` and it in turn will be eventually merged to `cardano-sl-0.4-mid`.

> Again, I understand the workflow

It's good for you if you understand, because I am afraid I don't :)
Actually I see nothing bad in this merge except that it adds some mess to git history (some commits are merged now and then other commits with same changes will be merged later). It shouldn't be done if it's not necessary, but it seems to be necessary now, so I think it's ok.

**Comment by gromakovsky** [comment]
And also I don't like when PRs are merged before checks finish :rage1:

**Comment by ksaric** [comment]
> And also I don't like when PRs are merged before checks finish :rage1:

I agree. Won't happen again.

**Pull request merged**
