### PR TITLE
[CSL-1766] Update stylish-haskell config to decrease diffs and conflicts and apply it

### PR DESCRIPTION
**Pull request by gromakovsky**
Stylish-haskell config we use nowadays has a drawback: it formats imports in a way that adding 1 import can change all imports which makes diffs cumbersome (which is especially annoying when only one line is changed) and complicates merges (which is especially annoying when you need to wait for CI again only because of merge conflicts in imports section).

This is how imports look with new config:
```
import           Control.Lens (makeLensesFor, makePrisms)
import           Control.Monad.Except (MonadError (throwError))
import           Crypto.Hash (Blake2b_224)
import           Data.Char (isAscii)
import           Data.Data (Data)
import           Data.Hashable (Hashable (..))
import           Data.Ix (Ix)
import qualified Data.Text as T
import qualified Data.Text.Buildable as Buildable
import           Data.Time.Units (Millisecond)
import           Formatting (Format, bprint, build, formatToString, int, ords, shown, stext, (%))
import qualified PlutusCore.Program as PLCore
import qualified Prelude
import           Serokell.AcidState ()
import           Serokell.Data.Memory.Units (Byte)
import           Serokell.Util.Base16 (formatBase16)
import           System.Random (Random (..))

import           Pos.Core.Fee (TxFeePolicy)
import           Pos.Core.Timestamp (TimeDiff (..), Timestamp (..))
import           Pos.Crypto.Hashing (AbstractHash, Hash)
import           Pos.Crypto.HD (HDAddressPayload)
import           Pos.Crypto.Signing.Types (ProxySecretKey, ProxySignature, PublicKey,
                                           RedeemPublicKey)
import           Pos.Data.Attributes (Attributes)
```
And this is how they looked before:
```
import           Control.Lens               (makeLensesFor, makePrisms)
import           Control.Monad.Except       (MonadError (throwError))
import           Crypto.Hash                (Blake2b_224)
import           Data.Char                  (isAscii)
import           Data.Data                  (Data)
import           Data.Hashable              (Hashable (..))
import           Data.Ix                    (Ix)
import qualified Data.Text                  as T
import qualified Data.Text.Buildable        as Buildable
import           Data.Time.Units            (Millisecond)
import           Formatting                 (Format, bprint, build, formatToString, int,
                                             ords, shown, stext, (%))
import qualified PlutusCore.Program         as PLCore
import qualified Prelude
import           Serokell.AcidState         ()
import           Serokell.Data.Memory.Units (Byte)
import           Serokell.Util.Base16       (formatBase16)
import           System.Random              (Random (..))

import           Pos.Core.Fee               (TxFeePolicy)
import           Pos.Core.Timestamp         (TimeDiff (..), Timestamp (..))
import           Pos.Crypto.Hashing         (AbstractHash, Hash)
import           Pos.Crypto.HD              (HDAddressPayload)
import           Pos.Crypto.Signing.Types   (ProxySecretKey, ProxySignature, PublicKey,
                                             RedeemPublicKey)
import           Pos.Data.Attributes        (Attributes)
```

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
@gromakovsky Thanks! I guess all is left for us then is to grab the new `.stylish-haskell.yaml` and use it when modify the code?

**Comment by dcoutts** [comment]
Hurrah!

**Comment by georgeee** [comment]
@adinapoli-iohk yes, please configure local stylish haskell

**Comment by gromakovsky** [comment]
@adinapoli-iohk it should just work if you pull, because `.stylish-haskell.yaml` is in the root of the repository. See https://github.com/jaspervdj/stylish-haskell#configuration

**Comment by georgeee** [comment]
Nice!

**Comment by adinapoli-iohk** [comment]
Nice indeed!

**Pull request merged**
