### PR TITLE
Devops 105

### PR DESCRIPTION
**Pull request by deepfire**
This is wrt. https://issues.serokell.io/issue/DEVOPS-105

cc @domenkozar, @int-index

### CODE REVIEW

**Comment by domenkozar** [comment]
At least if fails now :)

**Comment by int-index** [comment]
I already did it here: https://github.com/input-output-hk/cardano-sl/pull/330

Now the problem is that Travis fails with Out of Memory while building `ether`.

**Comment by domenkozar** [comment]
@int-index if you're working on one of our issues, please assign yourself and leave a comment so we don't duplicate work :)

**Comment by int-index** [comment]
Sorry, I'm still new to YouTrack, I thought that an open GitHub pull request would be noticeable enough. Next time I'll leave a comment when I open a PR.

**Comment by domenkozar** [comment]
Closing as #330 was merged

**Pull request closed without merging**
