### PR TITLE
[DEVOPS-565]  Appveyor fixes

### PR DESCRIPTION
**Pull request by deepfire**
Sister PR of https://github.com/input-output-hk/cardano-sl/pull/2125

### CODE REVIEW

**Comment by deepfire** [comment]
cc @gromakovsky

**Comment by gromakovsky** [comment]
There is a conflict.

**Comment by gromakovsky** [comment]
Note that I merged #2126 recently.

**Comment by domenkozar** [comment]
Superseeded by https://github.com/input-output-hk/cardano-sl/pull/2155

**Pull request closed without merging**
