### PR TITLE
add explorer endpoint for fetching raw transaction bodies

### PR DESCRIPTION
**Pull request by refi93**
## Description

I added an endpoint to be able to fetch the raw transaction body from the explorer. This is needed for example to verify the integrity of unspent outputs in a transaction assembled by a light wallet that has only access to the list of unspent outputs. With this endpoint you can verify that the txHash included in the unspent input referenced in the newly assembled transaction belongs indeed to the transaction with an input with the same amount of coins and with the same address that are in the unspent output. I recommend reading this [issue](https://github.com/input-output-hk/cardano-sl/issues/3097) to understand the motivation behind this PR.

I considered also returning the transaction in a structured way (i.e. extending the already existing tx summary endpoint with the data needed to serialize the transaction as it was submitted to the blockchain), but imho this approach would not be as future proof - e.g. in the case that new types of transaction inputs/outputs appear, a legacy client would probably have trouble serializing the transaction for the purpose of hash verification and it would be imho quite hard/cumbersome to come up with such a future proof serialization algorithm/transaction summary structure.

## Linked issue

https://github.com/input-output-hk/cardano-sl/issues/3097

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

I would be thankful if you point me at the place where to include the test for this endpoint, if needed. I just added an entry to the TestServer.
- [x] All new and existing tests passed.

## QA Steps
If synchronized with mainnet, the explorer endpoint `api/txs/raw/ea9a299210651fe1e4b097fed8ea6031683d0f09543fbe3a4c7f7723ca4fd478` should return the raw transaction body (as a CBOR encoded hex string, without the witnesses) for the transaction  with the respective hash, i.e.:

`{"Right":"839f8200d81858248258201e561e7a214b163cf530975ab0cc161c29cb20f7c10304c5ddb9fa1409fe699f00ff9f8282d818584283581cb7ad59fbfbb34df88f8e3a93ebec03e1a5077ae79df01a040f31366fa101581e581cea1425ccdd649bd63454c77eecdbee20a64f23299deb0b02a0e84b8c001a380603af1b000001e46cca151c8282d818584283581cc0ed966738a3b8b76d2614990085ab949c75dd0df6e868a6ccb2c686a101581e581ca8a675510be4634625797448bbd6379cac7cadf95dd7c4a67e33e307001aa83081341a73846ef88282d818584283581c4402b0c630941bb4bc10709a0e9a4f0aad94fa6a1e7b60164bfbe29ba101581e581cca3e553c9c63c59a87f14643a43e451f991d6d42758801be8f7aa31e001a3cdb64ed1b0000000325262a008282d818584283581c4f386e763eeeee0dfd3790ec17d67260e20a220059c63dbd92a34c38a101581e581c5fcd73e9878694d94863314b29aeadbc8768261900dabff229bb8db5001aa8ef1c221b00000007210e30088282d818584283581c964af58fcce68f39b2d3b54d63543cb5b6c203d043c3576b3671c6bfa101581e581c07a92009757f32c555d9a956151b0fcf1189b4a6f8d5013fab8331f7001a5d955a901ab3e306808282d818584283581c479448bb68428d8ccc9fe24ec84f901a32cdafafa45b215be76725aaa101581e581cd22ea3c67fbc162d2bb57fcaa4ec7dbf1ef112055a06f7f9794d9524001a56ded1ad1a5958ecc08282d818584283581c4be3f7ceae80b3c0f4dc7e12b8451c22b0452a568a5b90bf60f63750a101581e581c80f5433d7d19cc295eb1990fd01b82f850f4e48207174909896fd347001a767c443d1a407cba608282d818584283581c81fbbcfd9985c5575980495785d1a0d0a6f35bdf48a6c6fe780d7548a101581e581c1afbc57540db15064d2554d72fe315cf88eef90fdeae89f66824d2b4001a7c4ab90a1b0000003710a4788c8282d818584283581c30997d66ff9fce30e6d1c20b8222f1f7776d797c8fa6d93bf81eac60a101581e581cb57aa09da0689daaa1d0ae28fa882a2e888262eb65a33e4a571df434001aad291a8c1a03ca460a8282d818584283581cd0f720912201573f8e41c92ebb442d6934554c98b968484c953d94fea101581e581cc306c8ccb0bbe3dfc011cd50d78260c50c67123f50590c6c3faa4574001a0a8233361a483a63108282d818584283581c030a0bddb9065021c475d458414061268a149470cd5ea2b8af0c153aa101581e581c1afbc57540db152f7e0fe5d79c208b5eb8bc9873c91dbc05ef25a4db001a8a72c45a1b000000114231bd408282d818584283581c70f5e6700e0c8d0f7c26dab17f8e0e7e77f9169e11b62639bd26b3b6a101581e581c1afbc57540db156c73563cd7e1f68ffc858a6e2202d443ef7095ae78001a72d463a01b00000035e4fc32c08282d818584283581cb075829b980e4c1bf3b904ccde7af228276d5d556df15b975ff00613a101581e581cfa50263d66a37ff2b1098a63309bd44da1f82ee207d95bd30e6caa65001a0ef9f7f41ad0ad05408282d818584283581c16eb1cdbc3478d8ccd0b67e082ecf6c65dbcc4b6bf2f869b55d6c8d5a101581e581c1afbc57540db150ff59fa1d772ac06384f8f1cd26141e1e621a889ac001a0a04a8e11b00000009ae8a39c08282d818584283581cac0251cbb896f5a4704154b7c371b1c9f9f679baf7fe01deb7baf270a101581e581c8ee46672b9149bea9155d66be2da24ae429b7b60b5c7c787887d4afc001aaea79fee1a826750e88282d818584283581cd9d37a1d6ccd3769123c7d8fd2cb7a5c31a06d9874d8fdde67853b91a101581e581cd9273503e469fcb4ba09b3cca9ee29eef3d05170f2693163e4343e7f001a581e45921b0000000e040553408282d818584283581c64c24a0da3d88e4794d14ac204a3c3c2d20bf832f08f8211390b00c3a101581e581c0cc34d7bd202e52df6af0d91a637f25421d4788a04bfd28640b93cb6001a431473bd1a3c70bf708282d818584283581c4402b0c630941bb4bc10709a0e9a4f0aad94fa6a1e7b60164bfbe29ba101581e581cca3e553c9c63c59a87f14643a43e451f991d6d42758801be8f7aa31e001a3cdb64ed1b0000000348da2dc08282d818584283581c795b9e864b3fb4d3787d4da0826e6483f2c52122a2f21b7204dc9bcfa101581e581ceeb3c063adf8512676b52ee2eb37ab25c8127535e2a6f9423ff73275001ae490d81a1a002dc6c08282d818584283581cab491c526cad1e57362bb9c62b093cf61c17e0284cd207982804da3ea101581e581c1afbc57540db155d5ffd05d71436980ee276f9516a1b5c629af7cfef001a10b2a22f1b000000054b781f408282d818584283581c22098f84101500742c5a50b19d6f8ef009ed30be9f7a4956c1c8b6c4a101581e581c1afbc57540db151018b369d77d181f6e91d006da286e710785f03d50001a768873ba1b000000174867a5c08282d818584283581c9791d0211a9eb2d14aa12e7b2d289bb64a97653460b3f55001fecdbba101581e581c1afbc57540db156857055cd77f3fef88f8fa46237d9a0c1840e6268d001ade7110f01ad5c442288282d818584283581c86cb38f2c345504e9a6a1ba6a8eeb7dbd5724b4ab8a00d756855fd57a101581e581c1afbc57540db1500407c02d79829f68cb9e73177c0cf44d887414802001ae347929b1a5a528f008282d818584283581cecf1951fdbcc4925cf2f3c10296b63a05716f53d28960808be6f8ff7a101581e581c4e4f8ff4439731babd2edbd0df621f06b3453152a5f965ddcb32b472001a1fb201dc1a270fbd988282d818584283581cdc4d40b2971494c216974639a71feddaa4fe32f0c95e12c0f7460246a101581e581ce3977c040561ddd7f1b523db4bb716342b8f698543478e4932fa5f90001a1cdb21a71a159d62e08282d818584283581cef4e83e0ad2bb29f5ff4d02fd22404cf21f6946c61c1aa80fa11fab4a101581e581c1afbc57540db155199ed7ed7806c319d9ddbb508272d97af6c94cd20001a8cb711ae1b00000010fa15944bffa0"}`

### CODE REVIEW

**Comment by ksaric** [comment]
@refi93 Why do you need the internal representation? This seems kind of weird.

**Comment by refi93** [comment]
@ksaric because the wallet client before submitting the transaction needs to be sure that the transaction inputs it is going to include into the submitted transaction weren't tampered with. Therefore it needs to verify that the transactions containing those inputs as outputs have the claimed amount of coins, the addresses and their hashes are ok. And the hash is computed from the raw transaction body.

Of course, you can send the transaction as a JSON or in other format, but there is the risk that the client has a  slightly different serialization algorithm (or does not know how to serialize some new field that appeared in the transactions) and therefore it will compute a different transaction hash, although it was probably able do parse the relevant part of the transactions, i.e. the outputs, which has a relatively fixed format.

But I'm not sure why exactly are you asking, so maybe I did not answer your question. If you think so, don't hesitate to explain what you mean.

**Comment by refi93** [comment]
@akegalj just a bump, would you have time to look at this issue?

**Comment by jcmincke** [comment]
@akegalj : What do we do with this PR?

**Comment by akegalj** [comment]
@jcmincke 
leave it for today for me to revew it

**Comment by akegalj** [comment]
@refi93 
I am not able to go deep with this issue as we are spending time atm as it doesn't align with my current priorities. I have started reading https://github.com/input-output-hk/cardano-sl/issues/3097 and BIP-143 . From the abstract I can extract:

> minimize redundant data hashing in verification, and to cover the input value by the signature

redundant hashing is not problem which I see worth solving atm - where covering input value with signature seems something plausable investing time in. 

Also from the quick skim over the BIP-143 proposal my immediate intution is telling me this is something that should be part of the core stuff (also affecting cardano-node, not only explorer). So I think BIP-143 makes sense implementing but I believe it should be part of core logic, not on-the-edge code that Explorer handles.

Currently Explorer gets less love then we would like to as we are prioritizing other things on the list and we are planning on redesigning Explorer for ground up. That said, we are avoiding of adding adhoc features to the current Explorer design.

I am going to close this PR and rise a discussion with team about BIP-143 and https://github.com/input-output-hk/cardano-sl/issues/3097 . We might reopen this PR if team decides this is the way to implement the feature.

**Pull request closed without merging**
