### PR TITLE
[DEVOPS-91] Separate hlint phase to spare some build time

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by domenkozar** [comment]
Sigh, macOS just takes too long.

**Comment by domenkozar** [comment]
Appveyor counterpart: https://github.com/input-output-hk/cardano-sl/pull/314

**Comment by neongreen** [comment]
NB. this conflicts with #314 because things were moved into travis.sh

**Comment by domenkozar** [comment]
That's fine, I'll rebase once it's merged.

**Pull request merged**
