### PR TITLE
[CBR-348] log-config defines Loggername - Severity mapping

### PR DESCRIPTION
**Pull request by CodiePP**
## Description

provide a mapping of LoggerName -> Severity, and apply it in filtering messages in katip's scribes
* log-config defines minimum severity for a named logging context
turning off specific logging messages has been done in the current log configuration to prevent massive log creation.
with these changes for the new "structured logging" we provide the same functionality. 

## Linked issue(s)

CBR-97 (user story)
CBR-348
CBR-402
RCD-32

## Type of change

- [~] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🛠 New feature (non-breaking change which adds functionality)
- [~] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [~] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [x] 🔨 New or improved tests for existing code
- [~] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [~] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [~] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [~] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## QA Steps

see test at the end of the file `util/src/Pos/Util/Log.hs`
and the new test in `util/test/Test/Pos/Util/LogSpec.hs`

### CODE REVIEW

**Comment by CodiePP** [comment]
rebased on `develop` again, so after `CI` is happy we can merge.

**Comment by CodiePP** [comment]
@adinapoli-iohk  this PR should implement the same behaviour that was done in reducing the logging output. Can we have a look at it this week?

**Comment by adinapoli-iohk** [comment]
@CodiePP let's do it 😉

**Comment by CodiePP** [comment]
rebased on `develop` again, with the change of PR #3537 that let's pass `tests.walletIntegration`

**Pull request merged**
