### PR TITLE
Tests/csl620 add to mem pool

### PR DESCRIPTION
**Pull request by rockbmb**

### CODE REVIEW

**Comment by gromakovsky** [comment]
I am waiting for @pva701.

**Comment by gromakovsky** [comment]
I think there should be also tests that applying `pm1` to some state and then `pm2` to some state is same as applying `pm1 <> pm2` to this state.

However, it's not easy, so I think it should be a separate task. I will create two new issues.

**Comment by rockbmb** [comment]
>However, it's not easy
What do you mean, isn't it just a couple of lines of code?

**Comment by gromakovsky** [comment]
@rockbmb take a look at CSL-979. I expect it to take more than hour. And I think CSL-980 should be done after that. And I want this PR to merged now while I am at it.

**Pull request merged**
