### PR TITLE
[DEVOPS-267] cardano docker image

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @darko-mijic for once it's ready

**Comment by darko-mijic** [comment]
Can't wait. 🎉

**Comment by domenkozar** [comment]
It should be rebased on top of `cardano-sl-1.0-genesis-json2` and let's build the docker image in part of `release.nix` :)

**Comment by domenkozar** [comment]
We also need full relay list from https://github.com/input-output-hk/cardano-sl/blob/cardano-sl-0.6/scripts/launch/connect-to-cluster/testnet-0.6.sh and tls certs, etc

**Comment by domenkozar** [comment]
Docker image size is 350MB: https://hydra.iohk.io/build/36369#tabs-details

@cleverca22 can you write instructions how it's used?

**Comment by cleverca22** [comment]
```
[clever@amd-nixos:~/iohk/cardano-sl3]$ nix-build default.nix -A dockerImage -Q -j 8
[root@amd-nixos:/home/clever/iohk/cardano-sl3]# docker load < result 
[root@amd-nixos:/home/clever/iohk/cardano-sl3]# docker run -i cardano-container-testnet-1.0:latest
cardano-node: InvalidYaml (Just (YamlException "Yaml file not found: /nix/store/ggvd68yif3mdzqqvrmsq02f7dkiyh4b7-node/../scripts/log-templates/log-config-qa.yaml"))
[Attention] We are in PRODUCTION mode
[Attention] Software is built with wallet part
ConfigurationOptions {cfoFilePath = "/nix/store/ggvd68yif3mdzqqvrmsq02f7dkiyh4b7-node/configuration.yaml", cfoKey = "mainnet_wallet_macos64", cfoSystemStart = Just 1504820421000000}
System start time is 1506084057000000
Current time is 1506168253175760
Found no VSS keypair in keyfile, generating random one...
Found no signing keys in keyfile, generating random one...
Wallet is enabled!
Using configs and genesis:
ConfigurationOptions {cfoFilePath = "/nix/store/ggvd68yif3mdzqqvrmsq02f7dkiyh4b7-node/configuration.yaml", cfoKey = "mainnet_wallet_macos64", cfoSystemStart = Just 1504820421000000}
walletServeImpl initWsConnection

[root@amd-nixos:/home/clever/iohk/cardano-sl3]# echo $?
1
```

**Pull request closed without merging**
