### PR TITLE
[CBR-413] rely on WalletLayer.createHdAccount in wallet creation

### PR DESCRIPTION
**Pull request by adinapoli-iohk**
## Description

This PR fixes an embarrassing bug I have left when working on CBR-413. I did all that work to refactor things away to allow the `WalletLayer.Wallets.createWallet` function to reuse the `WalletLayer.Accounts.createHdAccount` function, but I didn't actually _plug it_.

Note that this PR (and that part of code) suffers from the same maladies @edsko reported in the original PR. I have opened CBR-416 to tackle that specifically.

## Linked issue

https://iohk.myjetbrains.com/youtrack/issue/CBR-413

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [x] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by KtorZ** [comment]
Ah, 

```
[2 of 9] Compiling Cardano.Wallet.WalletLayer.QuickCheck ( test/Cardano/Wallet/WalletLayer/QuickCheck.hs, dist/build/wallet-new-specs/wallet-new-specs-tmp/Cardano/Wallet/WalletLayer/QuickCheck.o )

test/Cardano/Wallet/WalletLayer/QuickCheck.hs:109:10: error:
    Duplicate instance declarations:
      instance Arbitrary CreateAccountError
        -- Defined at test/Cardano/Wallet/WalletLayer/QuickCheck.hs:109:10
      instance Arbitrary CreateAccountError
        -- Defined in ‘Cardano.Wallet.WalletLayer’
    |
109 | instance Arbitrary CreateAccountError where
```

GHC isn't happy.

**Comment by adinapoli-iohk** [comment]
@KtorZ aye, also the tests which tests pagination are now busted as they need to take into account (no pun intended!) the extra address.

Will amend and re-issue. Thanks for reviewing it!

**Comment by adinapoli-iohk** [comment]
@nikolaglumac this is now on `develop`!

**Comment by nikolaglumac** [comment]
Thanks @adinapoli-iohk :)

**Pull request merged**
