### PR TITLE
[CBR-102] - Wallet v1 documentation

### PR DESCRIPTION
**Pull request by KtorZ**
This addresses:

Task | Description
-- | -- 
CSL-2273 | Expand introduction with install instructions and curl example
CSL-2274 | Extend error handling table
CSL-2277 | Document V1 exchange endpoints
CSL-2359 | Serve API documentation through dedicated endpoints

Note that 

Task | Description
-- | -- 
CSL-2339 | Servant.Swagger.Test integration

was already addressed (and merged earlier) in #2630

### CODE REVIEW

**Comment by akegalj** [comment]
I am not sure is this merged correctly. I see error table in `develop` https://editor.swagger.io/?url=https://raw.githubusercontent.com/input-output-hk/cardano-sl/develop/wallet-new/spec/swagger.json# : 
look

is not the one that was produced as a part of https://iohk.myjetbrains.com/youtrack/issue/CSL-2274 (as stated in the description of this PR) https://github.com/input-output-hk/cardano-sl/pull/2500 : 
look

Looks like a mistake - but maybe it was intentional. 

cc @KtorZ

**Comment by KtorZ** [comment]
Hmmmm... the swagger file shouldn't even be on develop in a first place as it was removed by this PR.

See the [working tree](https://github.com/input-output-hk/cardano-sl/tree/f5f3ea1cf759572a9fd2a6d672dee737ab4a2872/wallet-new) right after the merge. I see it indeed now on develop, probably brought by some commits from... someone after a merge conflict resolution that didn't go well I suppose.

**Comment by KtorZ** [comment]
Note that the latest version of that spec file (or what it should be) can be seen here: 

https://cardanodocs.com/technical/wallet/api/v1/#section/Errors/Existing-wallet-errors

**Comment by akegalj** [comment]
> Note that the latest version of that spec file (or what it should be) can be seen here:

didn't know that - looks nice!

> Funny what happened here, I am not even in the file's history.

yes, strange that its left in a tree. 

So my understanding is that `swagger.json` will now be produced by CI and pushed on cardanodocs. So  https://cardanodocs.com/technical/wallet/api/v1/# is already automated and synced with `develop` ?

If ^ is true - is README out of date then https://github.com/input-output-hk/cardano-sl/tree/f5f3ea1cf759572a9fd2a6d672dee737ab4a2872/wallet-new#the-api ?

**Comment by KtorZ** [comment]
> So my understanding is that swagger.json will now be produced by CI and pushed on cardanodocs. So https://cardanodocs.com/technical/wallet/api/v1/# is already automated and synced with develop ?

We haven't been that far yet. We have to update manually cardanodocs.com until we have the specs generated as a build artefact by the CI. 

> If ^ is true - is README out of date then

README is indeed out-to-date anyway. No file is generated anymore but rather served by the wallet-backend on a dedicated endpoint. I'll open a ticket not to forget about this one. :+1:

**Pull request merged**
