### PR TITLE
Fix lint warnings

### PR DESCRIPTION
**Pull request by Pastafarianist**

### CODE REVIEW

**Comment by Pastafarianist** [comment]
I'd like to merge this before merging #204 so that the travis build for #204 doesn't fail.

**Comment by jagajaga** [comment]
If you push commits after PR creation, then write in title that it is WIP.

**Comment by Pastafarianist** [comment]
@jagajaga it was a hotfix for a GHC warning I hadn't noticed while creating the PR.

**Comment by jagajaga** [comment]
Okay, thank you.

On 10 April 2017 15:17:24 GMT+03:00, Dmitry Nikulin <notifications@github.com> wrote:
>@jagajaga it was a hotfix for a GHC warning I hadn't noticed while
>creating the PR.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/input-output-hk/cardano-sl/pull/205#issuecomment-292932462

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
