### PR TITLE
[TW-161] MsgRequestBlockHeaders parameter

### PR DESCRIPTION
**Pull request by avieth**
Use a ~~(currently non-master)~~ time-warp-nt revision which includes a fix in the outbound queue, and a change to the `MsgRequestBlockHeaders` constructor. When requesting headers for an alternate chain in the block retrieval worker, use the `MsgRequestBlockHeaders` constructor, because that's in fact what the conversation does.

### CODE REVIEW

**Comment by avieth** [comment]
default policy change looks good. I'll update the example policy yamls to match

**Comment by dcoutts** [comment]
> default policy change looks good. I'll update the example policy yamls to match

Thanks!

**Comment by avieth** [comment]
Appveyor logs are simply not readable for me. The web page grinds to a halt. Will wait for travis to finish.

**Comment by deepfire** [comment]
Travis: some Purescript failure: https://travis-ci.org/input-output-hk/cardano-sl/jobs/266150097#L7365
`Aug 18 23:36:21 bower ECONFLICT     Unable to find suitable version for purescript-functions`
Appveyor: some different-but-similar purs failure:
`bower ECONFLICT Unable to find suitable version for purescript-console`

We're getting that because cardano-explorer was merged.

**Comment by dcoutts** [comment]
Strange, the npm stuff is still failing for some of these builds, though #1375 was already merged.

**Comment by deepfire** [comment]
@dcoutts, I see that the PR's (merged) pass, but the branch don't.  So this suggests that the fix from #1375 is later in the master progression than the base of this PR.

I would suggest rebasing.

But there's also the merge conflicts..

**Comment by dcoutts** [comment]
Rebased on master. Lets see if this works now.

**Pull request merged**
