### PR TITLE
[CSL-953] Use blake2b instead of blake2s as the main hashing algorithm

### PR DESCRIPTION
**Pull request by gromakovsky**

### CODE REVIEW

**Comment by neongreen** [comment]
Can you say who decided on this change and why? (I'm fine with merging it but I wonder why it's being done.)

**Comment by gromakovsky** [comment]
I decided after I read
```
BLAKE2 comes in two flavors:

    BLAKE2b (or just BLAKE2) is optimized for 64-bit platforms—including NEON-enabled ARMs—and produces digests of any size between 1 and 64 bytes
    BLAKE2s is optimized for 8- to 32-bit platforms and produces digests of any size between 1 and 32 bytes 
```

I think 64-bit platforms are more popular nowadays and their popularity constantly increases.

**Comment by neongreen** [comment]
okay, but fix tests compilation :wink:

**Comment by neongreen** [comment]
> Makal

won't merge makal

**Comment by gromakovsky** [comment]
I've fixed makal, let's wait for CI.

**Comment by neongreen** [comment]
Three checks passed and the fourth failed due to the time limit (but all stack tests passed), so I'm going to merge it.

**Pull request merged**
