### PR TITLE
CSE-162 Explorer slow blocks, merge to master.

### PR DESCRIPTION
**Pull request by ksaric**
Merge to master, resolve conflicts.
I'm guessing switching from `encodeString` to `encode` has some benefits (lazy behavior, so memory usage?) but don't really know what they are.

### CODE REVIEW

**Comment by gromakovsky** [comment]
But where is merge commit? 😕

**Comment by ksaric** [comment]
What merge commit? If you mean the conflicts merge commit, it's all in this branch.

**Comment by gromakovsky** [comment]
All commits from `cardano-sl-0.5-rc` must be in `master`. So the idea was that you do `git merge 75f7c7f8a` from `master`, resolve conflicts, push the result into some branch and make a PR from this branch to master.

But you did something different. What did you do? Cherry-pick?

**Comment by ksaric** [comment]
I did:
```
git checkout master
git pull
git pull origin CSE-162-Explorer-slow-blocks -- this pulls those changes in master, I restored the branch
-- resolved conflicts
git checkout ksaric/cardano-sl-0.5-merge
git add --all
git commit -am "CSE-162 Explorer slow blocks, merge to master."
git push origin ksaric/cardano-sl-0.5-merge
```

**Comment by ksaric** [comment]
But I can merge if you want, I found this a bit less noisy for history.

**Comment by gromakovsky** [comment]
> But I can merge if you want, I found this a bit less noisy for history.

The point is that commits from rc branch (their hashes), must be predecessors of master. Otherwise it's barely possible to keep track of what is merged and what is not.

**Comment by gromakovsky** [comment]
@ksaric so the goal is to have a commit which has `75f7c7f8a` and some recent commit from `master` as predecessors. Can you do it?

**Comment by ksaric** [comment]
@gromakovsky Sure, I'll do it now.

**Comment by ksaric** [comment]
@gromakovsky Closed this in favor of https://github.com/input-output-hk/cardano-sl/pull/1077

**Pull request closed without merging**
