### PR TITLE
safer version of the script

### PR DESCRIPTION
**Pull request by CodiePP**
Signed-off-by: Alexander Diemand <codieplusplus@apax.net>

## Description

* checking for a GNU version of `sed` in the header of the script
* appease `shellcheck`

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by CodiePP** [comment]
I am not going to change the files `stylishHaskell` complains about.
They are not related to this PR.
Can you nevertheless agree to this small change?
(`shellcheck` is happy now)

**Comment by erikd** [comment]
@CodiePP if you rebase against develop, and then forse push, the stylish-haskell thing will almost certainly be fixed.

**Comment by erikd** [comment]
Although now that I think about it, I think @disassembler fixed this in #3206 .

**Comment by CodiePP** [comment]
fixed in PR #3206

**Pull request closed without merging**
