### PR TITLE
[CSL-911] Refactor re-exporting modules with 'autoexporter' package

### PR DESCRIPTION
**Pull request by rockbmb**

### CODE REVIEW

**Comment by rockbmb** [comment]
@georgeee This helps when adding/removing modules to the project because it's done automatically. Only drawback is that this only works when ALL sub files are exported, otherwise it still needs to be manual.

**Comment by gromakovsky** [comment]
@rockbmb appveyor CI failed and I don't understand the reason: http://i.imgur.com/0HtzEgP.png
Can you check whether it works on Windows?

**Comment by rockbmb** [comment]
@gromakovsky do Windows builds work yet? In any case, I haven't been able to build it, but I can't tell if it's because of this build, or some other problem.

**Comment by rockbmb** [comment]
@gromakovsky Fixed warnings. I really cannot understand the Windows error, and it happens in `master` as well, I can't do anything about that (in this issue). If you agree to this, please merge the PR.

**Comment by gromakovsky** [comment]
@rockbmb do I understand correctly that you fixed warnings by removing auto export in some places? I think it would be better to just suppress them there using pragma.

**Comment by rockbmb** [comment]
@gromakovsky That is indeed the case. I wasn't sure what the warning supression policy for this project was, so I preferred to be on the safe side. Can you tell me what the flag is?

**Comment by gromakovsky** [comment]
@rockbmb well, usually warning should not be suppressed, but if there are strong reasons why
• warning is inevitable;
• warning doesn't signify anything erroneous
then I think it's fine to suppress.

These pragmas are your friends for this task:
```
{-# OPTIONS_GHC -Wno-unused-imports #-}
{-# OPTIONS_GHC -Wno-dodgy-exports #-}
``

**Comment by gromakovsky** [comment]
@rockbmb I see that at least this build https://ci.appveyor.com/project/jagajaga/pos-haskell-prototype/build/0.2.3057 passed. Let's wait for @domenkozar's comments about appveyor.

**Comment by domenkozar** [comment]
Appveyor fails due to too long path. Since then the projects has been renamed from `pos-haskell-prototype` to `cardano-sl`. This will save us 10 chars.

If you can force-push this will trigger a new build and we can see if it got resolved.

travis-ci fails due to master being broken and unable to build haddock:

```
  haddock: internal error: spliceURL UnhelpfulSpan
    CallStack (from HasCallStack):
      error, called at utils/haddock/haddock-api/src/Haddock/Backends/Xhtml/Utils.hs:79:9 in main:Haddock.Backends.Xhtml.Utils
```

cc @denisshevchenko

**Comment by rockbmb** [comment]
@gromakovsky AppVeyor is failing because `'curl' is not recognized as an internal or external command`, I don't think this is an issue for this PR. Can you merge and close the PR if all else is acceptable?

**Comment by domenkozar** [comment]
`curl` should be fixed with https://github.com/input-output-hk/cardano-sl/pull/127

**Comment by gromakovsky** [comment]
I really want to test it works on Windows.
I think the are two possible scenarios:
1. Let's wait a little, maybe #127 will be ready for merge soon. In this case everything is good, we'll merge master into #125 and will see CI result.
2. Otherwise I propose to split #127 into smaller pull requests: one to fix appveyor stuff (which is fixed already) and another one to fix travis.

**Comment by domenkozar** [comment]
#127 is merged, please rebase :)

**Comment by rockbmb** [comment]
@gromakovsky can you

**Comment by rockbmb** [comment]
@gromakovsky it's been a while since I did this. Can you point me the right way?

**Comment by gromakovsky** [comment]
I find it much easier to merge master into this branch, given that there are already two merges into it. That's what I did. Let's wait for CI result.

**Comment by rockbmb** [comment]
@gromakovsky Cool, AppVeyor seems to work.

**Pull request merged**
