### PR TITLE
[WIP] Improve build (fix appveyor)

### PR DESCRIPTION
**Pull request by domenkozar**
Superseeds https://github.com/input-output-hk/cardano-sl/pull/107

### CODE REVIEW

**Comment by domenkozar** [comment]
Linux:

```
treaming-commons-0.1.17: configure
/home/travis/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

MacOS:

```
-  While building package log-warper-1.0.3 using:
      /Users/travis/.stack/setup-exe-cache/x86_64-osx-nix/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx-nix/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/travis/build/input-output-hk/cardano-sl/.stack-work/logs/log-warper-1.0.3.log
    Configuring log-warper-1.0.3...
    Building log-warper-1.0.3...
    Preprocessing library log-warper-1.0.3...
    [ 1 of 17] Compiling System.Wlog.Severity ( src/System/Wlog/Severity.hs, .stack-work/dist/x86_64-osx-nix/Cabal-1.24.2.0/build/System/Wlog/Severity.o )
    
    <no location info>: error:
        ghc: panic! (the 'impossible' happened)
      (GHC version 8.0.2 for x86_64-apple-darwin):
    	Dynamic linker not initialised
    
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
    
    [ 2 of 17] Compiling System.Wlog.MemoryQueue ( src/System/Wlog/MemoryQueue.hs, .stack-work/dist/x86_64-osx-nix/Cabal-1.24.2.0/build/System/Wlog/MemoryQueue.o )
    
    <no location info>: error:
        <command line>: can't load .so/.DLL for: /Users/travis/.stack/snapshots/x86_64-osx-nix/lts-8.2/8.0.2/lib/x86_64-osx-ghc-8.0.2/libHSdouble-conversion-2.0.2.0-FB9lbzCS3eNEibeP1aq5Xr-ghc8.0.2.dylib (dlopen(/Users/travis/.stack/snapshots/x86_64-osx-nix/lts-8.2/8.0.2/lib/x86_64-osx-ghc-8.0.2/libHSdouble-conversion-2.0.2.0-FB9lbzCS3eNEibeP1aq5Xr-ghc8.0.2.dylib, 5): Library not loaded: /nix/store/9h1nrgsnd15yi6zf703561zvbza0p7y5-libc++-3.7.1/lib/libc++.1.0.dylib
      Referenced from: /Users/travis/.stack/snapshots/x86_64-osx-nix/lts-8.2/8.0.2/lib/x86_64-osx-ghc-8.0.2/libHSdouble-conversion-2.0.2.0-FB9lbzCS3eNEibeP1aq5Xr-ghc8.0.2.dylib
      Reason: image not found)
    [ 3 of 17] Compiling System.Wlog.LoggerName ( src/System/Wlog/LoggerName.hs, .stack-work/dist/x86_64-osx-nix/Cabal-1.24.2.0/build/System/Wlog/LoggerName.o )
    
    <no location info>: error:
        ghc: panic! (the 'impossible' happened)
      (GHC version 8.0.2 for x86_64-apple-darwin):
    	Dynamic linker not initialised
```

**Comment by gromakovsky** [comment]
Now OS X build contains more than 10000 lines :(
https://travis-ci.org/input-output-hk/cardano-sl/jobs/212971985

**Comment by domenkozar** [comment]
Fixing that as we speak.

**Comment by gromakovsky** [comment]
Should it be WIP then (this PR)?

**Comment by domenkozar** [comment]
Still need to get all nixpkgs on same version so we don't fetch system deps twice.

**Comment by rockbmb** [comment]
@domenkozar Is this ready for merge? I can't really tell just from the review.

**Comment by domenkozar** [comment]
Nope, macOS still takes too long (1h20m).

**Comment by rockbmb** [comment]
@domenkozar So, does this mean #125 is blocked by long macOS builds?

**Comment by domenkozar** [comment]
All CI stuff is blocked due to too long macOS builds.

**Comment by domenkozar** [comment]
OK, this is good to go. MacOS still fails sometimes but not much I can do until https://github.com/NixOS/nixpkgs/issues/21200#issuecomment-288345915 is fixed to save us some time (or we remove some dependencies from cardano-sl.

Until then macOS builds are allowed to fail.

**Pull request merged**
