### PR TITLE
[CSL-1706] Discard duplicate tasks in recovery queue

### PR DESCRIPTION
**Pull request by akegalj**
a port of #2210 for the master branch

Seems like sync problem is being fixed here: https://iohk.myjetbrains.com/youtrack/issue/CSL-2126#comment=93-16655 

at least I was unable to reproduce it.

@sectore @ksaric can you confirm ?

### CODE REVIEW

**Comment by ksaric** [comment]
@akegalj I can confirm it works, yes.

**Comment by ksaric** [comment]
@volhovm I think you can see most of the tests and comments about them on https://iohk.myjetbrains.com/youtrack/issue/CSL-2126

**Comment by volhovm** [comment]
@ksaric Alright, do we need anybody else's approval before it can be merged?

**Comment by ksaric** [comment]
@volhovm @akegalj I updated the comment, please take a look at - https://iohk.myjetbrains.com/youtrack/issue/CSL-2126#comment=93-16674

**Pull request merged**
