### PR TITLE
WIP: [Do not merge] Merge release/1.3.1 into develop

### PR DESCRIPTION
**Pull request by erikd**
I really do not think I did this correctly.

On top of which the faucet package currently does not build and has been disabled. Will need @boothead to fix that.

### CODE REVIEW

**Comment by rvl** [comment]
I ported faucet from develop branch to release/1.3.1 and can help with porting it back again.

**Comment by erikd** [comment]
Thanks @rvl , but no need. @boothead helped me sort it out.

**Comment by boothead** [comment]
I've prepared branch https://github.com/input-output-hk/cardano-sl/tree/faucet which is all the commits in the faucet PR for issue DEVOPS-834 squashed to one commit and then an additional commit to take care of an api change for the `getNodeInfo` function.

**Comment by rvl** [comment]
I think but am not 100% sure that because this branch does not contain a merge commit, next time release/1.3.1 is merged into develop there will be merge conflicts again.

**Comment by rvl** [comment]
This PR does not contain a merge commit. It looks like there was a `git rebase` done which erased that.

I have remade it and pushed to a new branch [rvl/merge-release-1.3.1](https://github.com/input-output-hk/cardano-sl/tree/rvl/merge-release-1.3.1).

Reset this PR branch to that and it will look like a normal merge. (`git reset --hard rvl/merge-release-1.3.1; git push --force-with-lease`).

**Comment by erikd** [comment]
I think it would be a bad idea to merge this and hence I am closing it.

Will follow this up elsewhere.

**Pull request closed without merging**
