### PR TITLE
[CBR-366] Adding test for partial getters

### PR DESCRIPTION
**Pull request by paweljakubas**
## Description

Adding test for partial getters

## Linked issue

https://iohk.myjetbrains.com/youtrack/issue/CBR-366

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [x] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [x] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## QA Steps
Unit tests:
```stack test --ta "-m GetAccountBalance" cardano-sl-wallet-new:wallet-unit-tests```
```stack test --ta "-m GetAccountAddresses" cardano-sl-wallet-new:wallet-unit-tests```
Integration tests:
```nix-build release.nix -A tests.walletIntegration```

### CODE REVIEW

**Comment by paweljakubas** [comment]
yes, in the integration test added the following is taken place:
1. Genesis wallet and random wallet with 5 accounts are created
2. Balances as obtained by getAccounts and by getAccountBalances are compared (here zero balances)
3. Money is transferred from genesis wallet to random wallet's accounts
4. delayThread is adopted to confirm transactions in the blockchain
5. Point 2 is repeated, this time for accounts with nonzero balances

**Comment by edsko** [comment]
> Money is transferred from genesis wallet to random wallet's accounts

You mean in `wallet-new/integration/AccountSpecs.hs` right?

**Comment by paweljakubas** [comment]
yes

```            let payment amount toAddr = Payment
                    { pmtSource =  PaymentSource
                        { psWalletId = walId genesis
                        , psAccountIndex = accIndex fromAcct
                        }
                    , pmtDestinations = pure PaymentDistribution
                        { pdAddress = addrId toAddr
                        , pdAmount = V1 (Core.mkCoin amount)
                        }
                    , pmtGroupingPolicy = Nothing
                    , pmtSpendingPassword = Nothing
                    }
            amounts <- generate $ shuffle [1..5]
            let addrAndAmount = zip (map (\(addr : _) -> addr) $ map accAddresses accs) amounts
            forM_  addrAndAmount $ \(addr, amount) ->
                postTransaction wc (payment amount addr)```

**Comment by edsko** [comment]
Ok, sounds good. Ideally we'd modify the wallet tests themselves to be able to do something similar, perhaps hook it up to our blockchain infrastructure, but for now, this will do just fine :) Thanks!

**Pull request merged**
