### PR TITLE
Updated LICENCE file

### PR DESCRIPTION
**Pull request by amias-iohk**
The licence file didn't actually contain a licence , this was causing github not to show the project as open source.
This text is from the daedalus repo where this is working correctly.
This is NOT a change to the content of the licence per se , although its possible the licence might not have applied before having not been explicitly mentioned in this file.

This is also the case in a few other repos of ours including Icarus which is getting a lot of attention at the moment.

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by amias-iohk** [comment]
@KtorZ @kantp

**Comment by rvl** [comment]
> The licence file didn't actually contain a licence , this was causing github not to show the project as open source.

The `LICENSE` file is was symlink. Maybe GitHub doesn't read these properly.

The project is clearly open source because it's on GitHub.

There are quite a few `LICENSE` files in the repo -- one for each cabal project. You might be able to put the MIT license text in the top-level file and make all the rest symlinks to the top-level file.

**Comment by disassembler** [comment]
Yeah, flipping it so the project licenses that are the same as the main one might make more sense since github doesn't follow the symlink properly... I'd also update some links in documentation to the one not in `lib` if you do this. do a `git grep` for LICENSE and should be able to find anything. Ignore anything in a cabal file.

**Comment by jcmincke** [comment]
@amias-iohk Do we need to keep this PR open?

**Comment by rvl** [comment]
It would be good to solve the problem identified and also only have one LICENSE file in the repo.

Amias, if you just delete all the `LICENSE` files except the top-level one then remove all the `license-file` lines from all the cabal files, then update the link in `wallet-new/src/Cardano/Wallet/API/V1/Swagger.hs`, then it should be good (I decided symlinks aren't necessary).

**Comment by erikd** [comment]
> I decided symlinks aren't necessary

I'm pretty sure cabal requires a `LICENSE` file.

If we can't have single `LICENSE` file at the top level and symlink all the others to it, then we should just have multiple copies.

**Comment by amias-iohk** [comment]
i think the issue is that git doesn't support symlinks on filesystems that don't support them.  So we can't rely on using them in our code bases unless we accept the limitation of never checking out on FAT which seems too much to accept.

there are some git.core options around symlinks:
"core.symlinks
If false, symbolic links are checked out as small plain files that contain the link text. git-update-index(1) and git-add(1) will not change the recorded type to regular file. Useful on filesystems like FAT that do not support symbolic links.

The default is true, except git-clone(1) or git-init(1) will probe and set core.symlinks false if appropriate when the repository is created."

"core.preferSymlinkRefs
Instead of the default "symref" format for HEAD and other symbolic reference files, use symbolic links. This is sometimes needed to work with old scripts that expect HEAD to be a symbolic link."

The problem with using these options is that everyone will need them set including the CI.

Given that everything we produce seems to be licenced with the same licence and the file is small i think copying the file to each location seems to be the most reliable fix.  Especially as its content won't change any time soon.

We have done this in several of our repositories including Icarus and the same solution should apply to some other repos.

**Comment by amias-iohk** [comment]
This is the only line i can see that refers to the licence file in the swagger file , i'm really not sure what is being done here as i don't know the significance of this LICENCE file in sub folders or why we even duplicate this info. I feel this is beyond what a QA should be doing and needs to be addressed by a developer.

  & info.license ?~ ("MIT" & url ?~ URL "https://raw.githubusercontent.com/input-output-hk/cardano-sl/develop/lib/LICENSE")

**Comment by erikd** [comment]
Closing this in favor of #3572

**Pull request closed without merging**
