### PR TITLE
Enable custom configuration when starting demo cluster

### PR DESCRIPTION
**Pull request by Sam-Jeston**
## Description

It can be convenient to start the cardano-sl demo cluster with a custom configuration file, rather than the default file defined at `lib/configuration.yaml`.

I've updated the demo cluster nix tooling such that:
- `./scripts/launch/demo-nix.sh` behaves as it used to
- `./scripts/launch/demo-nix.sh -c config_file_name.yaml` will use the corresponding file in the top level configurations folder

## Type of change
Non-breaking extension to existing nix behaviour

## How to merge

Send the message `bors r+` to merge this PR. For more information, see
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/bors.md).

### CODE REVIEW

**Comment by Sam-Jeston** [comment]
Do you guys see any issues with this change @rvl @disassembler ?

**Comment by Sam-Jeston** [comment]
@rvl it's a duplicate of this: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/http-bridge/test/data/cardano-node-simple/configuration.yaml

So it allows Daedalus to connect to a demo cluster, using the genesis setup used in the tests of cardano-wallet, which we know the mnemonics for. In general I considered it a place where alternate configurations could be placed. Not sure of the history of confusion in this regard, I don't mind where the files live.

**Comment by rvl** [comment]
The configuration system is just really confusing in general, so adding another file which isn't actually used within `cardano-sl` is going to confuse things more. If you could add a readme in the configurations directory to explain it that would help.

Does the `demo-nix.sh -c` option need to refer to something within `${configFiles}/configurations`, or could it more simply be an absolute path?

**Comment by Sam-Jeston** [comment]
@rvl you're right, absolute path is cleaner. It does remove confusion from the repo

**Pull request merged**
