### PR TITLE
Merge/csl1531 csl0.5 into master

### PR DESCRIPTION
**Pull request by volhovM**

### CODE REVIEW

**Comment by volhovM** [comment]
@akegalj please check if `yarn.lock` is sane, i don't know what is it.

**Comment by akegalj** [comment]
>  please check if yarn.lock is sane, i don't know what is it.

@volhovM I don't actually understand nor use it as well. 

@sectore can you take a look at it

**Comment by akegalj** [comment]
@volhovM 
@sectore says yarn.lock is ok

**Comment by sectore** [comment]
@volhovM https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control

**Pull request merged**
