### PR TITLE
[WIP] [CSL-1994] Move test modules to a new package

### PR DESCRIPTION
**Pull request by hithroc**

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
> I don't like the idea of putting all the tests in one package.

I agree with @ksaric here, but maybe I'm missing some tremendous advantage of doing things this way. What does this refactoring buys us?

**Comment by dcoutts** [comment]
Same here. On the face of it this is the wrong direction. Is there something we're missing?

**Comment by gromakovsky** [comment]
> I don't like the idea of putting all the tests in one package.

We don't put all tests into one package. The issue name (CSL-1994 Move all tests into one package) is outdated. We are only moving some tests to the new package.

> What does this refactoring buys us?

The main goal is to reduce amount dependencies of the main code. Currently there are some testing modules in `cardano-sl` library as well as in some other libraries.
Main code (by _main_ I mean used in production, so `cardano-node-simple`, `cardano-node`, etc.) currently depends on these modules, but doesn't use it.

`cardano-sl-tests` package is only for tests which depend on these modules (e. g. `Test.Pos.Block.Logic.Mode`, `Test.Pos.Block.Logic.Emulation`, etc.). We are not going to move **all** tests there.

Also this PR is WIP.

**Comment by gromakovsky** [comment]
I updated https://iohk.myjetbrains.com/youtrack/issue/CSL-1994.

**Comment by gromakovsky** [comment]
>  For example, if I just want to run the tests for explorer, I have to filter the rest.

I think you confused putting tests in one package and in one test-suite. There can be multiple test-suites in one package.

**Comment by ksaric** [comment]
> There can be multiple test-suites in one package.

I currently see multiple tests grouped in `cardano-tests-test` test-suite - https://github.com/input-output-hk/cardano-sl/pull/2369/files#diff-70a440254038fb657b646f43dc6f84c5R109

**Comment by hithroc** [comment]
Yes, this branch is a little bit out of date now. The upcoming changes that follow the new task plan will be split into several different PRs, so I'm closing this one.

**Pull request closed without merging**
