### PR TITLE
Enable -Werror

### PR DESCRIPTION
**Pull request by gromakovsky**

### CODE REVIEW

**Comment by domenkozar** [comment]
Can we just put that into stack.yaml?

**Comment by gromakovsky** [comment]
We want it only in CI, not during development

**Comment by domenkozar** [comment]
Sure, let's then wait for the CI.

**Comment by domenkozar** [comment]
This fails now since the flag is passed to all packages due to https://github.com/input-output-hk/cardano-sl/blob/master/stack.yaml#L80, which we need to speed up builds for travis-ci.

**Comment by domenkozar** [comment]
@gromakovsky https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-options

**Comment by gromakovsky** [comment]
https://issues.serokell.io/issue/CSL-929

**Pull request merged**
