### PR TITLE
Merge 0.3

### PR DESCRIPTION
**Pull request by gromakovsky**
Here I merged `cardano-0.3` into `master`. Someone else had to do it, but I did instead which wasn't a pleasant experience, so in future please merge `cardano-sl-0.3` into `master` as soon as you push something there.

### CODE REVIEW

**Comment by akegalj** [comment]
@gromakovsky thanks. In future we will be merging `cardano-sl-0.3` first to `cardano-sl-0.3-mid` and then `cardano-sl-0.3-mid` to `master`

**Comment by gromakovsky** [comment]
I think changes in release branch must be applied to corresponding `mid` branch **and** to `master` ASAP. Cc @georgeee to confirm.

If you merge it only to `mid`, then `master` and release branch will be diverged for a long time and it's very bad with our workflow.

**Comment by akegalj** [comment]
@gromakovsky yes, that's how I see it as well

**Comment by gromakovsky** [comment]
Ok, cool

**Pull request merged**
