### PR TITLE
[CSL-1575] Rewrite embed-config

### PR DESCRIPTION
**Pull request by neongreen**
Now we have a `no-embed` flag which makes CSL load constants.yaml and genesis at runtime, and we also have two environment variables that are read when `no-embed` is on:

* `CSL_RES_PATH` says where to look for the config and genesis files.
* `CSL_CONFIG_NAME` says which section to take from the config file.

### CODE REVIEW

**Comment by domenkozar** [comment]
Nice :) cc @cleverca22

**Comment by georgeee** [comment]
BTW, we should pass these params from CLI, env variables are hard from Windows

**Comment by domenkozar** [comment]
@volhovM what's the status on this, can we prioritize it?

**Comment by neongreen** [comment]
@domenkozar I'm working on fixing @georgeee's comments now.

**Comment by dcoutts** [comment]
@neongreen @georgeee can we keep the `CSL_RES_PATH`. We want this for the benchmarking setup. For the benchmarking the current approach with using the dev mode and generating the genesis block on the fly is not working well at all (it takes up all memory and fails when using several thousand addresses). We want to generate an external genesis block using the normal tool and pass that in at runtime.

**Comment by georgeee** [comment]
@dcoutts it was later decided to use flags to node, following set:

`--custom-config-file=constants_new.yaml`
`--custom-config-name=devnet_shortep`
`--custom-genesis-core-bin=..`
`--custom-genesis-gt-bin=..`

**Comment by dcoutts** [comment]
Great. I prefer flags vs env vars anyway!

**Comment by domenkozar** [comment]
@neongreen needs a rebase on top of master

**Comment by neongreen** [comment]
Okay, @georgeee @domenkozar this is ready for re-review. Will rebase in the morning.

**Comment by domenkozar** [comment]
I will test this today - please don't merge yet.

**Comment by neongreen** [comment]
@domenkozar Travis tests are failing, I'm investigating

**Comment by domenkozar** [comment]
@neongreen ready for testing?

**Comment by neongreen** [comment]
@domenkozar should be, yes

**Comment by neongreen** [comment]
@domenkozar you were planning to test this

**Comment by domenkozar** [comment]
Will do tomorrow.

**Comment by domenkozar** [comment]
@georgeee I asked not to merge, why did you merge it?

**Pull request merged**
