### PR TITLE
[CSL-2343] Remove wallet/node directory

### PR DESCRIPTION
**Pull request by gromakovsky**
It's not used anymore, so I suppose it should be removed as part of CSL-2343.

### CODE REVIEW

**Comment by hithroc** [comment]
Should `scripts/launch/demo-with-new-wallet-api.sh` also be removed? Asking here because seems like relevant pull request.

**Comment by gromakovsky** [comment]
Hm, yes, I think so.

**Comment by gromakovsky** [comment]
Actually no, I don't think so, because there is `--new-wallet` flag in it. So probably it should be left for now.

**Comment by adinapoli-iohk** [comment]
@KtorZ @parsonsmatt I think this PR is worthwhile reviving, as we removed the `executable` flag from `wallet.cabal` but we are still keeping the content inside `wallet/node/*` alive for no good reason.

Would you resurrect this one and give it another spin?

**Comment by akegalj** [comment]
Closed in favour of https://github.com/input-output-hk/cardano-sl/pull/3104

**Pull request closed without merging**
