### PR TITLE
[CSL-2343] Remove wallet/node dir

### PR DESCRIPTION
**Pull request by akegalj**
## Description

Remove unused source files

old PR: https://github.com/input-output-hk/cardano-sl/pull/2643

## Linked issue

Possibly https://iohk.myjetbrains.com/youtrack/issue/CSL-2343

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by akegalj** [comment]
@adinapoli-iohk 
got it, will revert it. But note that that script was actually not working properly (as there is no `--new-wallet` flag, so essentially it was the same as `scripts/launch/demo-with-wallet-api.sh` + not working)

will revert

**Comment by adinapoli-iohk** [comment]
> as there is no --new-wallet

Uhm, this doesn't sounds right -- the new wallet definitely used to have such `--new-wallet` flag (cc @edsko , who originally implemented it), so either we screwed up and we removed it from the new `cardano-node`, or maybe you were referring to the old `cardano-node` executable? 😉

**Comment by akegalj** [comment]
I see it is in `wallet-new/src/Cardano/Wallet/Server/CLI.hs` now. I was unable to launch that script (launch the cluster with it - `cardano-node` was complaining there is no such flag. 

Anyway - possibly I did something wrong. Reverting. Will put PR here

**Comment by akegalj** [comment]
New PR here https://github.com/input-output-hk/cardano-sl/pull/3111

**Pull request merged**
