### PR TITLE
WIP: [CBR-226] Evaluate input selection policies

### PR DESCRIPTION
**Pull request by edsko**
## Description

Study of input selection policies.

## Linked issue

https://iohk.myjetbrains.com/youtrack/issue/CBR-226
https://iohk.myjetbrains.com/youtrack/issue/CBR-241
https://iohk.myjetbrains.com/youtrack/issue/CBR-251
https://iohk.myjetbrains.com/youtrack/issue/CBR-252

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by edsko** [comment]
So far this PR defines some infrastructure for writing input selection policies (in terms of the DSL), has a first version of a random input selection policy (as yet untested), and provides some infrastructure for testing these against input streams. For now I wrote a very simple input stream that generates a bunch of outputs of increasing size, and then uses them in the exact same order; wrote this primarily so that I can test the analysis output, which looks something like this:

exact

**Comment by parsonsmatt** [comment]
That graphic is awesome!

**Comment by edsko** [comment]
@parsonsmatt Glad you like it too :) I'm looking forward to evaluating some actual policies and see the UTxO animated. This particular graphic is only the start, many more to come :)

**Comment by edsko** [comment]
Much awesomer graphics posted internally :) PR is now in decent state but haven't rebased or dealt with CI issues, and anyway need to extent the tests with additional event streams etc. But the code that is there now is not work in progress code, but "production" ready.

**Pull request closed without merging**
