### PR TITLE
[CSL-1968] Implement GET /api/v1/user-profile

### PR DESCRIPTION
**Pull request by adinapoli-iohk**
This PR implements what was called `/api/v1/profile` in the old API.

@DominikGuzei you will see I have made a precise choice: the default in case no locale is set is `en-US`, as taken from:

https://github.com/input-output-hk/daedalus/blob/master/translations/translation-runner.js#L7

I hope that's correct! This is how it looks like in Swagger:

screen shot 2017-11-28 at 17 43 46

### CODE REVIEW

**Comment by DominikGuzei** [comment]
@adinapoli-iohk to be honest: i don't think we are using any `profile` server endpoint in Daedalus as we are saving that locally on the user's machine 😟 

@nikolaglumac that's right isn't it?

**Comment by adinapoli-iohk** [comment]
If that's the case guys, even better -- the best code is the one you don't have to write 😉 

Just let me know, and will scrap these for good!

**Comment by nikolaglumac** [comment]
@DominikGuzei that is correct. The problem was that saving or fetching info such as user locale from the backend was too slow - e.g. when application is starting we need to have this information straight away in order to show loading message in user's locale so we decided to save all profile info to the local storage layer.

**Comment by adinapoli-iohk** [comment]
Even better guys. Case closed 😉 

Cheers!

**Comment by akegalj** [comment]
@nikolaglumac that's even better.

Can we improve this communication in future for request removal if Daedalus UI decides not to use some endpoints (or features). That would help us maintain clean codebase

**Comment by nikolaglumac** [comment]
@akegalj of course we can and of course we should 👍

**Pull request closed without merging**
