### PR TITLE
[CSM-320] Create wallet accounts & addresses using hardened keys

### PR DESCRIPTION
**Pull request by Martoon-00**
Link to new genesis archive: https://drive.google.com/open?id=0B5lxtpMYMfwKLVVvbUtmcThSWTg

### CODE REVIEW

**Comment by Martoon-00** [comment]
To be debugged, currently generated keys deliver no money when imported

**Comment by Martoon-00** [comment]
1, Tested in dev mode
2. Tested by @georgeee in `qa`, works fine

**Comment by flyingleafe** [comment]
Not merging until @georgeee or @fersel gives feedback about possible issues with redeployment (due to change of genesis)

**Comment by flyingleafe** [comment]
@pva701 commented instead, it's safe

**Pull request merged**
