### PR TITLE
[CSM-363, CSM-364] Fix bugs in JSON import/export (version for 0.5 branch)

### PR DESCRIPTION
**Pull request by flyingleafe**
Copy of https://github.com/input-output-hk/cardano-sl/pull/1152 for to provide fix for 0.5 release

### CODE REVIEW

**Comment by domenkozar** [comment]
@flyingleafe can you rebase on top of master?

**Comment by flyingleafe** [comment]
@domenkozar the same PR but to master is here: https://github.com/input-output-hk/cardano-sl/pull/1152
or did I misunderstood what do you want me to do?

**Comment by domenkozar** [comment]
Sorry about the confusion, you're right :) I think we'll just have to wait for https://github.com/travis-ci/travis-build/pull/1112 to be merged first.

**Comment by gromakovsky** [comment]
@flyingleafe please make a PR which merges it to master. You should use `-s ours` I suppose.

**Comment by gromakovsky** [comment]
@flyingleafe ping

**Comment by gromakovsky** [comment]
@flyingleafe ping, it's quite important as it blocks everyone else who commits to 0.5.

**Comment by gromakovsky** [comment]
@flyingleafe ping

**Comment by flyingleafe** [comment]
@gromakovsky how about https://github.com/input-output-hk/cardano-sl/pull/1152?

**Comment by gromakovsky** [comment]
Yes, but these commits are not in master. See this guide: https://serokell.slack.com/archives/G3JSNBZDY/p1498916165937939

**Comment by gromakovsky** [comment]
`8d3b70a3f` should be parent of master but it's not.
```
gromak ~/Work/cardano-sl (cardano-sl-0.5|…) % git branch --contains 8d3b70a3f                                                                                                                                                                                           141 :(
* cardano-sl-0.5
```

The easiest way to resolve it is to do `git merge 8d3b70a3f -s ours` from master.

**Comment by flyingleafe** [comment]
@gromakovsky the thing is that `master` is protected, so I cannot do it in such an easy way. I, of course, can make another PR and trigger CI and so on, but it seems like it would be much easier if some developer with _rights_ merge it to master directly that way ;)

**Comment by gromakovsky** [comment]
@flyingleafe I can do it in this particular case because we started this discussion already and because we have problems with CI anyway.
But in general workflow is that after your commits appear in release branch, you are responsible for making sure they will appear in master.
1. It won't take more than a minute to make a PR.
2. Other people may be not sure whether it's ok to merge with `-s ours`. Even if there is a twin PR, it can be the case that you suddenly realized something new during migration to the release branch. Or there is another reason not to use `-s ours`. Moreover, other people shouldn't check whether there are some changes in release branch which can be merged with `-s ours`.
So you should notify someone else about it.
3. That being said, if you ask someone explicitly to merge your commits, it's a bit distractive, but if you make a PR, it's a regular flow. Someone will approve and merge it later. If you really don't want to wait or load CI, you can make a PR and ask someone to merge it w/o passing checks (which is fine when there are no changes). But again, it should be done when PR is ready, because sometimes it's inconvenient for others to stop their work, switch to another branch, merge, etc.

**Comment by gromakovsky** [comment]
Ok, done, but that's exceptional case.

**Pull request merged**
