### PR TITLE
[CBR-470] Ensure 600 file permission on generated x509 certificates and keys

### PR DESCRIPTION
**Pull request by KtorZ**
## Description

It is of the utmost importance that those files aren't readable by anyone but the user generating them.
Files are generated upon start and used to secure the communication between cardano-sl and its clients (e.g. Daedalus)

Note that, we do assume that users are able to secure their own environment from potential adversary services,
so this is really about preventing one user to have access to certificates of another user.

## Linked issue

[[CBR-470]](https://iohk.myjetbrains.com/youtrack/issue/CO-434)

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## QA Steps

```
$ stack exec -- cardano-x509-certificates --server-out-dir /tmp/tls --ca-out-dir /tmp/tls --clients-out-dir /tmp/tls -k dev -c lib/configuration.yaml
$ ls -lh /tmp/tls
total 108K
-rw------- 1 ktorz ktorz 1,2K oct.  22 17:20 ca.crt
-rw------- 1 ktorz ktorz 1,7K oct.  22 17:20 ca.key
-rw------- 1 ktorz ktorz 2,9K oct.  22 17:20 ca.pem
-rw------- 1 ktorz ktorz 1,2K oct.  22 17:20 client.crt
-rw------- 1 ktorz ktorz 1,7K oct.  22 17:20 client.key
-rw------- 1 ktorz ktorz 2,9K oct.  22 17:20 client.pem
-rw------- 1 ktorz ktorz 1,3K oct.  22 17:20 server.crt
-rw------- 1 ktorz ktorz 1,7K oct.  22 17:20 server.key
-rw------- 1 ktorz ktorz 3,0K oct.  22 17:20 server.pem
```

### CODE REVIEW

**Comment by KtorZ** [comment]
@dcoutts Went for your nice trick :) 
Works fine -- as expected -- on unix.

```
$ ls -lh tls/
total 108K
-rw------- 1 ktorz ktorz 1,2K oct.  25 14:52 ca.crt
-rw------- 1 ktorz ktorz 1,7K oct.  25 14:52 ca.key
-rw------- 1 ktorz ktorz 2,9K oct.  25 14:52 ca.pem
-rw------- 1 ktorz ktorz 1,2K oct.  25 14:52 client.crt
-rw------- 1 ktorz ktorz 1,7K oct.  25 14:52 client.key
-rw------- 1 ktorz ktorz 2,9K oct.  25 14:52 client.pem
-rw------- 1 ktorz ktorz 1,3K oct.  25 14:52 server.crt
-rw------- 1 ktorz ktorz 1,7K oct.  25 14:52 server.key
-rw------- 1 ktorz ktorz 3,0K oct.  25 14:52 server.pem
```

**Comment by KtorZ** [comment]
Yes. I've double-checked in the source code actually:

https://hackage.haskell.org/package/base-4.12.0.0/docs/src/System.IO.html#openBinaryTempFile

```hs
-- | Like 'openTempFile', but opens the file in binary mode. See 'openBinaryFile' for more comments.
openBinaryTempFile :: FilePath -> String -> IO (FilePath, Handle)
openBinaryTempFile tmp_dir template
    = openTempFile' "openBinaryTempFile" tmp_dir template True 0o600
```

A bit ad-hoc, but if it buys us some extra "security" on windows as well, why not.

**Comment by amias-iohk** [comment]
This looks like it fixes the permissions to lock them down a bit further.
there is a test failure here but it is known to be broken for reasons not related to this code or build.

lets merge it

**Comment by KtorZ** [comment]
@rvl 

This was an oversight and should have landed in `develop` before the cut-off. 
I've warned QA it won't be in RC1 but should make it in RC2. 

May I merge that in the release branch now or should I wait a bit?

**Pull request merged**
