### PR TITLE
[never merge] testnet staging

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by domenkozar** [comment]
@georgeee Let me elaborate why this is needed. Staging environment needs a different magic number, so cardano-sl needs to be compiled with correct constants, so that daedalus picks that binary up. It's the same constants that match with `testnet_staging` name deployed on staging.

If I should be doing things otherwise, let me know.

**Comment by domenkozar** [comment]
@pva701 why did you merge this? It says *never merge* in the pr?

**Comment by gromakovsky** [comment]
I guess it happened automatically when he merged #1198 which contains the commit from this PR. So the problem is with #1198, it shouldn't have this commit.

**Comment by pva701** [comment]
@domenkozar ^ this

**Comment by domenkozar** [comment]
Why did it pass the review then? :( I'll revert and reopen this PR.

**Comment by gromakovsky** [comment]
It was approved only by @pva701 and he didn't have enough context. I wrote about this problem in comments, but didn't reject (and didn't approve) because I wasn't strict enough. Next time I will be more strict, noted.

**Pull request merged**
