### PR TITLE
[CSE-244] Cherry pick

### PR DESCRIPTION
**Pull request by sectore**
of PR #1764 into `cardano-sl-1.0`.

_How to test:_
1. [Build](https://github.com/input-output-hk/cardano-sl/tree/master/explorer/frontend#short-version-of-installation) and [run](https://github.com/input-output-hk/cardano-sl/tree/master/explorer/frontend#4-build-in-development-mode-and-run-w-webpack-dev-server-locally) `Explorer` locally.
1. Run `scripts/launch/explorer-with-nodes.sh` in a `tmux` session.
1. Open http://localhost:3100/ in your browser
1. In root folder of `cardano-sl` you will find following `*.log` files of Explorer: 
* explorer-node.log
* explorer.log
* socket-io.log

### CODE REVIEW

**Comment by dcoutts** [comment]
Resolved conflicts and merged via the CLI (but github doesn't notice).

**Comment by dcoutts** [comment]
Hmm, getting windows CI failure due to OpenSSL download 404 failure.

**Comment by akegalj** [comment]
> Hmm, getting windows CI failure due to OpenSSL download 404 failure.

I have restarted CI - if it doesn't fix the problem (maybe the server was down for some reason) I will ping @iohk-devops to check it out

**Comment by gromakovsky** [comment]
See #1865 probably.

**Pull request merged**
