### PR TITLE
R120 4/unicode characters support

### PR DESCRIPTION
**Pull request by KtorZ**
## Description

Force lang locales to UTF-8 to avoid runtime error described in [R120-4](https://iohk.myjetbrains.com/youtrack/issue/R120-4).

I'd like to add a regression test here though I am not sure if it's worth the pain. Ideally, we'd have to start a node with incompatible locales (for instance `LC_ALL=POSIX`) and verify that a request containing out-of-range unicode characters would fail... Sounds quite cumbersome to setup.

Any opinion?

## Linked issue

[[R120-4]](https://iohk.myjetbrains.com/youtrack/issue/R120-4)

## Type of change

- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [x] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## QA Steps
- We should be able to create, rename and view wallets with names with characters in any unicode ranges (like: 漢字)

### CODE REVIEW

**Comment by KtorZ** [comment]
Good point @adinapoli-iohk, I completely forgot ^.^ 

Misdeed repaired.

**Comment by adinapoli-iohk** [comment]
Wot! Hydra failed with `Kernel panic - not syncing: Out of memory: compulsory panic_on_oom is enabled` but I suspect that's a red herring -- alas I don't have permission to restart it: @KtorZ , maybe we can ask our lovely devops to do so? 😀

**Comment by jmitchell** [comment]
I saved a full copy of the log and restarted the Hydra build.

**Comment by adinapoli-iohk** [comment]
Yay, that's all green now -- thanks @jmitchell !

@KtorZ merging this -- you know what to do next 😁

**Pull request merged**
