### PR TITLE
[DO NOT MERGE] Binaries for `mainnet` installers

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by gromakovsky** [comment]
What is `mainnet-base`?

**Comment by deepfire** [comment]
@gromakovsky, you need to specify a base branch, when you make a PR, so `mainnet-base` is just such 
a stub branch.

**Comment by gromakovsky** [comment]
This PR was needed for 1.0.3 release, this release was done, so I am closing it.

**Comment by deepfire** [comment]
@gromakovsky, we'll need this PR for the next mainnet update.  Will reopen then.

**Pull request closed without merging**
