### PR TITLE
CBR-27: Add hdRootsFromWalletStorage

### PR DESCRIPTION
**Pull request by k0001**
## Description

Most data that will end up in the new `TxMeta` and `HdWallet` will come from wallet recovery. However, some details need to be migrated from `WalletStorage` explicitly since they are not available in the blockchain. Here, the data that goes in the new `HdRoot`, which correspond to details previously given at `WalletStorage` creation time, is handled by `hdRootsFromWalletStorage`.

## Linked issue

https://iohk.myjetbrains.com/youtrack/issue/CBR-27

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [x] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [x] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [x] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## QA Steps

[ ] Test against real world `WalletStorage`s.
[ ] Still need to check whether `hdRootIdFromCIdWal` is correct.

### CODE REVIEW

**Comment by k0001** [comment]
@edsko this is probably OK to merge now, as soon as CI passes. I am going to be needing this in the wallet restoration work.

**Comment by k0001** [comment]
Also, we will only be using `cIdWalToHashPublicKey` right away. It will be some time until we actually use `hdRootsFromWalletStorage`. If necessary, I can split these changes into two PR.

**Comment by edsko** [comment]
> @edsko The comment here in the PR is incidental. The purpose of the function is to obtain all of the HdRoots in a WalletStorage as it says in its documentation. Saying anything more than that would be a distraction, I think. When the time comes to connect this function with the rest of the “migration system”, higher level documentation as the one mentioned in this PR will be due there.

@k0001 we need a conclusion somewhere tangible that says "this is the bit that we need to take care of during migration; everything else we can recover fromt he blockchain". Right now the purpose of this function is very obscure.

**Comment by k0001** [comment]
@adinapoli-iohk I'm closing this until the comments are addressed.

**Pull request closed without merging**
