### PR TITLE
[WIP] nix-tools

### PR DESCRIPTION
**Pull request by angerman**
## Description

This PR replaces the `stack2nix` logic with the `stack-to-nix` logic from `nix-tools`.  This results in the use of translations of cabal to nix expressions retaining flag and os conditionals; and is the foundation for the cross compilation logic.

We do not add cross compilation logic yet, only the infrastructure on which it is based.

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by angerman** [comment]
Note: this won't compile; I sill need to solve a solver issue in `stack-to-nix`; however it might provide a basis for preliminary discussions.

**Comment by angerman** [comment]
Note to self: `lib.nix` needs to be fixed.

**Comment by rvl** [comment]
The general approach looks good to me. :+1:

I know this is an initial version but I would like to minimise the "footprint" of the auto-generated expressions and hide the implementation details as much as possible.

This would mean hiding things under the `nix/` subdirectory -- things such as  `.stack-to-nix.cache`, `.stack.nix`, `stack-pkgs.nix`.

In `pkgs.nix`:
 - The choice of `lts-11_13` attribute should be generated/derived from `stack.yaml`.
 - Maybe this file can be auto-generated as well, because it's really boilerplate code.
 - Do `fetchHackage`, etc, need to be in `localLib`? Maybe they could be inlined here. This would also remove the need to have `.json` files because we would be kept inline.
 - If this file is auto-generated, it could include a `regenerate` attribute which provides a script to regenerate itself from `stack.yaml`.

With the external repos `hackage.nix`, `haskell.nix`, `stackage.nix`:
 - before releasing, these would need a short readme file explaining what they are and how they are generated.
 - `hackage.nix` has a lot of directories at the top level. When viewed in github, things such as `default.nix` can't be seen. Maybe the hackage expressions could be in a subdirectory to help with that.
 - The files which contain overrides should be mentioned in docs.

The overlays `broken-tests.nix`, `dont-haddock.nix`, `rec-breaker.nix` kind of belong to `stackage.nix`, rather than the repo which uses stackage. However I can see that this would be a pain to maintain (because they would potentially be different for each LTS), so I guess it's OK to keep them in `cardano-sl`.

**Comment by angerman** [comment]
@rvl thanks for the review.

Yes, auto generating the `pkgs.nix` file is something I always wanted to have. Ideally the `stack-to-nix` tool would generate that file; probably instead of the `stack-pkgs.nix` file to STDOUT.

Pulling hackage/stackage/haskel nix in the `pkgs` file is probably better than the `lib.nix` abused. That would also contain it to that specific file. I'll rework that.

**Comment by angerman** [comment]
alright, so I've moved the repo / infra fetching into the `pkgs.nix`.

I'll move the `.stack-to-nix.cache`, `.stack.nix`, `stack-pkgs.nix` into `nix` and have `stack-to-nix` generate the `pkgs.nix` file to STDOUT.

With the recursion breaker; don't check and don't haddock overlays. I see the temptation to have the hidden in in some other nix infra; but I think we should be very well aware of the package for which we exclude tests.

Note however:
- Recursion breaking should not be required once we have a component builder.
- Don't haddock should be unnecessary if the builder would check for sensible haddocks first; or ensure that haddocks that don't exist do not necessarily constitute a failure.

**Comment by angerman** [comment]
This is superseded by #3868.

**Pull request closed without merging**
