### PR TITLE
[DEVOPS-157] naturalise cardano-keygen:  number generated key files from 0, instead of 1

### PR DESCRIPTION
**Pull request by deepfire**
This caught people off-guard numerous times.

Seems like humans are better trained to deal with natural numbers.

### CODE REVIEW

**Comment by deepfire** [comment]
cc @domenkozar

**Comment by deepfire** [comment]
@gromakovsky, there's still a problem with OpenSSL:
```
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:101
+ ... eb.com/download/Win64OpenSSL-1_0_2L.exe', "$($env:USERPROFILE)\Win64O ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Command executed with exception: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
```

**Comment by cleverca22** [comment]
@deepfire  its fixed on master: https://github.com/input-output-hk/cardano-sl/pull/1865

**Comment by deepfire** [comment]
..problem is, I need the fix in `cardano-sl-1.0`..

**Comment by cleverca22** [comment]
@deepfire  https://github.com/input-output-hk/cardano-sl/pull/1872 and also on cardano-sl-1.0

**Comment by deepfire** [comment]
@dcoutts, CI has passed, ready for your re-approval.

**Comment by domenkozar** [comment]
I hope we have fixed all the code that relys on current numbering before this comes into effect.

**Comment by deepfire** [comment]
@domenkozar, as to DevOps -- I'm not aware of any code, except a single place in `iohk-ops`, that relies on it.

For the developer side, I think we have their approval.

**Comment by gromakovsky** [comment]
Right, I am not aware of any code on our side which relies on it.

**Comment by deepfire** [comment]
@domenkozar, done.

**Comment by domenkozar** [comment]
@deepfire needs to run pkgs/generate.sh

**Comment by deepfire** [comment]
@domenkozar, I used to think this is better to done in the base branch + a rebase -- otherwise we're getting a conflict.

Rebased.

**Comment by domenkozar** [comment]
@deepfire doesn't seem like you've pushed?

**Comment by deepfire** [comment]
@domenkozar, indeed, thank you!

**Comment by deepfire** [comment]
@dcoutts it appears that in the latest `cardano-sl-1.0` we still need a PR to rerun `pkgs/generate.sh` -- to make `stack2nix` happy. How should we coordinate it?  I can do it in this branch -- but then we'd have to move quickly, before someone else does that and suffers conflicts..

**Comment by deepfire** [comment]
@domenkozar, a run of `pkgs/generate.sh` fails like this:
```
pdating deps from ./..
stack2nix: FAILED: stack list-dependencies
Warning: addDependentFile path (Template Haskell) listed in /home/deepfire/cardano-sl/core/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Pos/Core/Class.dump-hi does not exist: /nix/store/shv5yba4ns4ax38gvrd36rfynm9yms4i-ghc-8.0.2/lib/ghc-8.0.2/include/ghcversion.h
Warning: addDependentFile path (Template Haskell) listed in /home/deepfire/cardano-sl/core/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Pos/Core/Constants.dump-hi does not exist: /nix/store/shv5yba4ns4ax38gvrd36rfynm9yms4i-ghc-8.0.2/lib/ghc-8.0.2/include/ghcversion.h
Warning: addDependentFile path (Template Haskell) listed in /home/deepfire/cardano-sl/core/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Pos/Crypto/AsBinary.dump-hi does not exist: /nix/store/shv5yba4ns4ax38gvrd36rfynm9yms4i-ghc-8.0.2/lib/ghc-8.0.2/include/ghcversion.h
Warning: addDependentFile path (Template Haskell) listed in /home/deepfire/cardano-sl/core/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Pos/Binary/Class.dump-hi does not exist: /nix/store/shv5yba4ns4ax38gvrd36rfynm9yms4i-ghc-8.0.2/lib/ghc-8.0.2/include/MachDeps.h
Warning: addDependentFile path (Template Haskell) listed in /home/deepfire/cardano-sl/core/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Pos/Binary/Class.dump-hi does not exist: /nix/store/shv5yba4ns4ax38gvrd36rfynm9yms4i-ghc-8.0.2/lib/ghc-8.0.2/include/ghcautoconf.h
Warning: addDependentFile path (Template Haskell) listed in /home/deepfire/cardano-sl/core/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Pos/Binary/Class.dump-hi does not exist: /nix/store/shv5yba4ns4ax38gvrd36rfynm9yms4i-ghc-8.0.2/lib/ghc-8.0.2/include/ghcversion.h
Warning: addDependentFile path (Template Haskell) listed in /home/deepfire/cardano-sl/core/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/Pos/Binary/Crypto.dump-hi does not exist: /nix/store/shv5yba4ns4ax38gvrd36rfynm9yms4i-ghc-8.0.2/lib/ghc-8.0.2/include/ghcversion.h
Didn't see ekg-core-0.1.1.3 in your package indices.
Updating and trying again.
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Updating index
Exception /home/deepfire/.stack/indices/Hackage/hackage-security-lock: createDirectory: already exists (File exists) when using mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Selected mirror http://hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Updating index
Exception /home/deepfire/.stack/indices/Hackage/hackage-security-lock: createDirectory: already exists (File exists) when using mirror http://hackage.fpcomplete.com/
Selected mirror http://objects-us-west-1.dream.io/hackage-mirror/
Downloading timestamp
Downloading snapshot
Updating index
/home/deepfire/.stack/indices/Hackage/hackage-security-lock: createDirectory: already exists (File exists)


CallStack (from HasCallStack):
  error, called at src/Stack2nix.hs:167:15 in stack2nix-0.1.3.0-Chf2P9JnCB4H9SzIPAPiJD:Stack2nix
```

**Comment by cleverca22** [comment]
@deepfire the travis job was still able to gist the diff: https://gist.github.com/b13035e745d7bf4d725171a6339d8091

**Comment by deepfire** [comment]
Nuking `~/.stack` helped, as usual.. : -)

**Comment by deepfire** [comment]
@domenkozar, CI has happened.

**Pull request merged**
