### PR TITLE
[DEVOPS-652] remove all usage of import-from-derivation in release.nix when nix 1.12 is present

### PR DESCRIPTION
**Pull request by cleverca22**
this has been tested on both nixpkgs `61fbdb47a69f78998f55207e64122a0798047b5d`

and also the `5c09cdc187b014143302551e62d4973b5bf52814` where the problem originally occured

### CODE REVIEW

**Comment by cleverca22** [comment]
and the usage of `builtins.fetchTarball` requires nix-daemon to be running version 1.12 to solve
```
imported archive of ‘/nix/store/pwyqgvdswd4yaffsdsg09vv99a2swx45-61fbdb47a69f78998f55207e64122a0798047b5d.tar.gz’ lacks a signature
```

**Comment by domenkozar** [comment]
I'm not super keen on this solution. We could just bail out of hydra-eval-jobset and use nix-instantiate and switch to Nix 2.0 fully once it's ready.

**Comment by domenkozar** [comment]
The overhead of supporting both will bring too much overhead. I think we'll have to make the transition big-bang once it's out there.

**Comment by domenkozar** [comment]
We decided to use older nixpkgs for now to get hydra - matching Hydra in nixpkgs.

**Comment by akegalj** [comment]
@cleverca22 can this be closed?

**Comment by jcmincke** [comment]
Closed because this PR is just too old.

**Pull request closed without merging**
