### PR TITLE
Clear reset failures on SIGHUP

### PR DESCRIPTION
**Pull request by edsko**
Needs https://github.com/serokell/time-warp-nt/pull/88 .

### CODE REVIEW

**Comment by dcoutts** [comment]
PR serokell/time-warp-nt#88 has been merged, so we can adjust this to point to the commit on TW master.

**Comment by edsko** [comment]
Force-pushed to use latest time-warp-nt master.

**Comment by dcoutts** [comment]
Feel free to merge once CI is green.

**Comment by edsko** [comment]
Ran the magic nix incantation.

**Comment by edsko** [comment]
Rebased and re-ran the Magic Incantiation, in the hope that it'll fix the CI problem on OSX:

```
Aug 10 14:58:21 error: build of '/nix/store/j1dvqvzifd70iqgs1w6fnhwdnb3m4sz3-stdenv-darwin.drv' failed
Aug 10 14:58:21 /nix/var/nix/profiles/default/bin/nix-shell: failed to build all dependencies
```

**Pull request merged**
