### PR TITLE
[CSLD-108] How to connect node to the cluster

### PR DESCRIPTION
**Pull request by denisshevchenko**

### CODE REVIEW

**Comment by deepfire** [comment]
@denisshevchenko, @domenkozar, this raises an important question -- do we want to support the `stack` way of building `cardano-sl` for the external community?

This is an important decision with far-reaching consequences, AFAICT.

**Comment by domenkozar** [comment]
Deveopers use stack, I think that's fine.

**Comment by denisshevchenko** [comment]
@domenkozar Agree. This script is for developers, so `stack exec` looks good here.

**Comment by gromakovsky** [comment]
These files are ignored by CI ⇒ merging.

**Pull request merged**
