### PR TITLE
CSL v0.6.2 candidate: Merge changes from `master` to `cardano-sl-0.6

### PR DESCRIPTION
**Pull request by georgeee**
Change set

| PR | Issue | Necessity for 0.6.2 | Necessity for 0.6.3/mainnet (team lead) | Necessity for mainnet (Duncan)
| ---- | ----- |  ----- | ----- | ---- |
| #1463 | [CSL-1575](https://issues.serokell.io/issue/CSL-1575) Allow to use runtime configuration for constants | **Slightly desirable** (operationing builds) | **Yes** | **Yes** |
| #1477 | [CSL-1555](https://issues.serokell.io/issue/CSL-1555) Simple versioning for Node DB | **Not practical** (too much time needed to deploy this change to the RC) | - | **Yes** |
| #1483 | [CSM-435](https://issues.serokell.io/issue/CSM-435) Wallet ready flag | Unnecessary | **Desirable** (it improves user experience and helps to prevent possible bugs related to not finished wallet sync) | **Yes** |
| #1495 | [CSL-1578](https://issues.serokell.io/issue/CSL-1578) Finish efforts on concurrency code refinement | Unnecessary | Desirable, shutdown of nodes in cluster will become robust | No |
| #1503 | [CSM-442](https://issues.serokell.io/issue/CSM-442) Improvements in unit tests for transaction creation | Unnecessary | No, but safe | No |
| #1504 | [CSL-1608](https://issues.serokell.io/issue/CSL-1608) Heavyweight delegation is not idempotent | Unnecessary | **Yes**, a minor bug in heavyweight delegation | TBD |
| #1505 | [CSL-1613](https://issues.serokell.io/issue/CSL-1613) Don't use the state lock when checking for genesis block necessity | Unnecessary and dangerous, change in genesis block creation which happens every epoch on every node including users | No (performance improvement) | No |
| #1508 | [CSL-803](https://issues.serokell.io/issue/CSL-803) Find a way for light wallet to correctly work with older chain | Unnecessary (operational tooling) | No, operational tooling to be delivered separately | No |
| #1511, #1520 | [CSL-1610](https://issues.serokell.io/issue/CSL-1610) "SSC couldn't compute seed" on current staging | Unnecessary: logging + sanity check for ssc, deadlock fix from the issue is already [merged to 0.6](https://github.com/input-output-hk/cardano-sl/commit/4098a146a81cc6824d2b5d969ad4862f45ddbe55) | Desirable, logging is useful if some bug will be discovered | #1511 TBD, perhaps a simpler version of this PR, #1520 No |
| #1512 | [CSE-211](https://issues.serokell.io/issue/CSE-211) Explorer ''dev'' start scripts not working | Unnecessary | - | No |
| #1514 | [CSL-1618](https://issues.serokell.io/issue/CSL-1618) Nodes stopped producing blocks after the 0th epoch | Unnecessary (merge from 0.6 to master) | **Yes** | **Yes** |
| #1518 | [CSM-448](https://issues.serokell.io/issue/CSM-448) Catch errors in `getTxFee` endpoint correctly. | Slightly desirable | **Yes** | **Yes** |
| #1519 | [CSE-212](https://issues.serokell.io/issue/CSE-212) Downcase Since time description | **Slightly desirable** | - | **Yes** |
| #1524 | [CSL-1624](https://issues.serokell.io/issue/CSL-1624) Always fail in compile-time if CSL_SYSTEM_TAG isn't set | Unnecessary (dev env adjustments) | No, but safe | No |
| #1525 | Delete peer options (cosmetic change to codebase) | Unnecessary | No, but safe | No |
| #1527 | [CSL-1621](https://issues.serokell.io/issue/CSL-1621) Rework lwallet | Unnecessary (operational tooling)  | No, operational tooling to be delivered separately  | No |
| #1528 | [CSM-341](https://issues.serokell.io/issue/CSM-341) Race condition on newWallet | Unnecessary | **Yes** | **Yes** |
| #1529 | [CSL-1598](https://issues.serokell.io/issue/CSL-1598) Get rid of address/listen/topology/kademlia duplicates | Unnecessary | No, but safe | No |
| #1531 | Merge csl-0.6 to master  | Unnecessary (merge from 0.6 to master) | **Yes** | N/A |
| #1533 | Remove import (cosmetic change to codebase) | Unnecessary, safe | No, but safe | No |
| #1539 | [CSL-1637](https://issues.serokell.io/issue/CSL-1637) Initialze StateLock during creation, not in scenario | Unnecessary (something needed for auxx) | No, operational tooling to be delivered separately  | No |
| #1544 | [CSL-1553](https://issues.serokell.io/issue/CSL-1553) Block rollback tooling (lwallet) | Unnecessary (operational tooling)  | No, operational tooling to be delivered separately  | No |
| #1545 | [CSL-1648](https://issues.serokell.io/issue/CSL-1648) cardano-auxx: thread blocked indefinitely in an MVar operation | Unnecessary (operational tooling)  | No, operational tooling to be delivered separately  | No |
| #1547 | [CSL-1633](https://issues.serokell.io/issue/CSL-1633) Revise usage of `recoveryCommGuard` in `reportRollback` (`Pos.Block.Network.Logic`) | **Desirable**, change in error reporting for block rollback (safe) | **Yes** | No |
| #1548 | Cosmetic change to codebase | Unnecessary, safe | No, but safe | No |
| #1551 | Change in docs | Unnecessary, safe | No, but safe | No |

In master, but not in this PR (incompatible with 0.6)

| PR | Issue | Necessity for mainnet (team lead) | Necessity for mainnet (Duncan) |
| ---- | ----- |  ----- | ----- |
|#1543|[CSL-1568](https://issues.serokell.io/issue/CSL-1568) Review the CBOR encoding of `Address`|Yes, important protocol improvement| Yes |

### CODE REVIEW

**Comment by gromakovsky** [comment]
It requires to write DB migration due to CSL-1555.

**Comment by fersel** [comment]
I don't think we'll need all of these in TN0.6. Will discuss during the day.

**Comment by georgeee** [comment]
@gromakovsky good point, yes, we should not miss it

**Comment by georgeee** [comment]
* For cluster nodes my plan is to provide accurate procedure on how to deploy new version
* For user nodes we'll simply change names for DBs (users would need to retrieve chain from scratch, but this is ok way to go)

From sl-devops (by me):

> Later we would need to try a procedure to migrate from tn0.6 to this one
> 
> Several things would have to be taken into account:
> * nodes to be updated and restarted not all at once
>      * node dbs would have to be wiped on newly deployed nodes, but old versioned nodes would have to be running with old DBs and allow old chain to transfer from old nodes to newly updated nodes
> * apply change with flag for config name

**Comment by georgeee** [comment]
> I don't think we'll need all of these in TN0.6. Will discuss during the day.

@fersel I really think we should try including all of these. B/c our idea was to deploy master and these are there
If some particular fixes look bad for you, please comment their issue ids here

**Comment by fersel** [comment]
@georgeee I understand this point, of course, but the more changes - the more unknowns and possible flows there are introduced. The initial plan was to include as few changes as possible. We're not just doing another iteration of "push the current master for an update", we're picking the neccesary ones only. If we want to push the whole master, we can do that with another update the following week.

**Pull request closed without merging**
