### PR TITLE
[CSL-947] Fix public key parsing

### PR DESCRIPTION
**Pull request by rockbmb**

### CODE REVIEW

**Comment by rockbmb** [comment]
@volhovM Misha, take a look at the line I changed, you made a little mistake that broke tests. `guard` confused me too.

**Comment by rockbmb** [comment]
@georgeee ran it on my machine, it worked fine. It's safe to merge, but you can wait for CI to be sure.

**Comment by volhovM** [comment]
@rockbmb omg yes. I guess i did a change and then merged it incorrectly. What a shame.

**Comment by rockbmb** [comment]
@volhovM it's cool, it was tricky to spot.

**Pull request merged**
