### PR TITLE
[CSL-1957] Merge feature branch `alfredo/wallet-new` into `master`

### PR DESCRIPTION
**Pull request by adinapoli-iohk**
@gromakovsky Apologies for another humongous PR, I think I have learnt the lesson that squashed merges and feature branches do not go along well. I have tried to cherry pick the commits which was produced after https://github.com/input-output-hk/cardano-sl/pull/1918, but I've got into painful conflict-resolution due to the refactoring which happened in core lately, so the path of least resistance seems to simply re-do the merging, this time the classic way, so that next merges are much, much smaller. Apologies 😞 

EDIT: ah, looks like that luckly despite all the commits are still shown (due to the wrong merging stategy) at least the diff looks all-right, "just" 1646 SLOC 😉 

It's still backward-compatible code, so reviewing it can be skipped or done very lightly.

### CODE REVIEW

**Comment by gromakovsky** [comment]
@adinapoli-iohk 
1. I see that you created https://iohk.myjetbrains.com/youtrack/issue/CSL-1957 for this merge. Thank you for doing that, I appreciate it, it's an essential part of our workflow. Can you please also update this PR's title and put `[CSL-1957]` there (and do it for all other PRs corresponding to issues)? Otherwise it's almost impossible to associate PRs and issues.
2. There is a cabal warning when I build wallet-new:
```
Warning: The following modules should be added to exposed-modules or other-modules in /home/gromak/Work/cardano-sl/wallet-new/cardano-sl-wallet-new.cabal:
    - In wallet-new-specs component:
        Cardano.Wallet.API.V1.Handlers.Info
        Cardano.Wallet.API.V1.Handlers.Settings
```
Can you fix them please? I am tolerant to code style in wallet-new, but I want all warnings to be fixed, because all devs need to build wallet-new to check they didn't break it and nobody wants to see warnings.

Apart from that looks good to me, almost no changes outside `wallet-new`, which is a good sign 😉

**Comment by adinapoli-iohk** [comment]
Thanks @gromakovsky , all excellent points, let me address those 😉

**Comment by adinapoli-iohk** [comment]
@gromakovsky This PR and this feature branch become bloated. I have decided to keep using this open PR as a guinea pig to get at the bottom of the CI failure, at which point I will close it and reopen a new PR where I will branch off from this one but will squash _all_ the commits in a nice & clean commit labeled `[CSL-1957] Merge wallet-new (Dec 2017)`.

Apologies for the mess!

**Comment by adinapoli-iohk** [comment]
Ok, CI finally passes on Win, so going to close and reopen.

**Pull request closed without merging**
