### PR TITLE
[CSL-873] Add endpoint for daedalus to report init time

### PR DESCRIPTION
**Pull request by volhovM**
Endpoint to report init time was added. Someone on the frontend must now implement logic that sends http request to the backend after sync with 2 timestamps.

### CODE REVIEW

**Comment by akegalj** [comment]
@volhovM I don't understand why UI has to provide this https://issues.serokell.io/issue/CSLREQ-41 informations back to the backend? Both of these:
```
1) How much time it took to connect to network
2) How much time it took to synchronize with blockchain (download all blocks)
```
can be calculated in ws thread that notifies UI about these events https://github.com/input-output-hk/cardano-sl/blob/026312aecec3dbbdb2a84993fb2a2158e48ee8d4/src/Pos/Wallet/Web/Server/Methods.hs#L191

**Comment by flyingleafe** [comment]
@akegalj I think idea is these values should be provided by frontend, to represent end user experience more precisely. Another reason is probably that @volhovM doesn't know a thing about how WS thread work.

**Comment by volhovM** [comment]
@akegalj because there's a certain way frontend switches between "connecting to network" and "sync" states itself so storing this logic on the backend would be code duplication. Moreover, implementing the feature this way is more robust to changes on the frontend.

**Comment by akegalj** [comment]
@volhovM ok, yes that makes sense. I will add purescript boilerplate code to this PR which exposes this to the frontend (~10min task). We can merge after that

**Comment by akegalj** [comment]
@volhovM ok, yes that makes sense. I will add purescript boilerplate code to this PR which exposes this to the frontend (~10min task). We can merge after that

**Pull request merged**
