### PR TITLE
[CSL-2165] Add `since=<timestamp>` parameter to tx history endpoint

### PR DESCRIPTION
**Pull request by pva701**
Add 'since' parameter to /api/txs/histories enpoint, which accepts time in seconds

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
@pva701 Ops, CI is failing: we should apply the diff [here](https://gist.github.com/6d92f5c27173e4de3408e3e7aa2448af) and fix the hlint suggestions.

**Comment by adinapoli-iohk** [comment]
@Martoon-00 @pva701 Can I ask you guys to handle the conflicts, before I review? 😉

**Comment by Martoon-00** [comment]
Done!

**Comment by adinapoli-iohk** [comment]
@pva701 @Martoon-00 As much as I have seeing good work go to waste, I think this PR is largely superseded by now by the upcoming V1 API and the work Konstantin is doing on https://github.com/input-output-hk/cardano-sl/pull/2602, as that has the same outcome: we can now limit the amount of results based on creation time by calling `/api/transactions?created_at=GT[xxx]`.

Shout if you guys disagree and if there is any extra feature this PR provides that #2602 does not, in which case we can backport to `develop`.

**Comment by adinapoli-iohk** [comment]
Closing for now, we can always reopen later.

**Pull request closed without merging**
