### PR TITLE
[CSM-148] All transactions have the same date and time

### PR DESCRIPTION
**Pull request by ajnsit**
Initialise the transaction history metadata for a particular wallet, if it didn't exist previously.

### CODE REVIEW

**Comment by ajnsit** [comment]
@Martoon-00 Yeah I had to use `non'` instead of `non` because it complained about a missing `Eq` instance otherwise.

**Comment by Martoon-00** [comment]
Could you explain why it fixes CSM-148?

**Comment by ajnsit** [comment]
@Martoon-00 It fixes atleast a part of the problem. When we send some money, we store the time of the transaction in the metadata in the wallet storage and not on the blockchain. However, it would fail if the wallet id was not pre-initialised in the store. This edit initialises the wallet storage to an empty hashmap if it didn't already exist.

**Comment by Martoon-00** [comment]
Thanks, makes sense

**Comment by Martoon-00** [comment]
By the way, it's not the only place there `wsTxHistory . ix cWalId` is encountered )
How do you think about fixing `addWalletTxHistory` as well?

**Pull request merged**
