### PR TITLE
[CSM-336] Do not traverse blockchain on `newWallet`

### PR DESCRIPTION
**Pull request by Martoon-00**
Do it only on wallet restore.

Tested with daedalus and postman. 
Wallet restoration still takes 20-60 sec

### CODE REVIEW

**Comment by akegalj** [comment]
@Martoon-00 we still have to rewire restoreWallet and newWallet to proper endpoints in client-api (the bridge)

**Comment by Martoon-00** [comment]
That's true :man_facepalming:

**Comment by Martoon-00** [comment]
@akegalj Wait a sec, that's not true. In bridge they are also different, with `TODO` to unite them one day

**Comment by akegalj** [comment]
@Martoon-00 yes, I just checked. You are right. Approving

**Pull request merged**
