### PR TITLE
[DEVOPS-168] Fix macOS CI

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by deepfire** [comment]
@domenkozar, both now time out: https://travis-ci.org/input-output-hk/cardano-sl/builds/247554770?utm_source=github_status&utm_medium=notification

**Comment by deepfire** [comment]
@domenkozar, given this dire situation, we might need an urgent push to Hydra-based caching..

**Comment by deepfire** [comment]
The windows build fails thusly:

```
There were multiple candidates for the Cabal entry "hlint.hs" (C:\w\.w\downloaded\XTTklt4ROs4T\hlint.hs), picking C:\w\.w\downloaded\XTTklt4ROs4T\tests\hlint.hs
plutus-prototype-0.1.0.0: build (lib)
store-0.4.3.1: configure
store-0.4.3.1: build
wai-app-static-3.1.6.1: configure
wai-app-static-3.1.6.1: build
wreq-0.5.0.1: configure
Package wreq uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
wreq-0.5.0.1: build
Package wreq uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
--  While building package wreq-0.5.0.1 using:
      C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wreq-0.5.0.1\.w\dist\ca59d0ab\setup\setup --builddir=.w\dist\ca59d0ab build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\w\.w\logs\wreq-0.5.0.1.log
    [1 of 2] Compiling Main             ( C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wreq-0.5.0.1\Setup.hs, C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wreq-0.5.0.1\.w\dist\ca59d0ab\setup\Main.o )
    
    C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wreq-0.5.0.1\Setup.hs:63:15: warning: [-Wdeprecations]
        In the use of type constructor or class `InstalledPackageId'
        (imported from Distribution.Package):
        Deprecated: "Use UnitId instead"
    [2 of 2] Compiling StackSetupShim   ( C:\s\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wreq-0.5.0.1\.w\dist\ca59d0ab\setup\StackSetupShim.o )
    Linking C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wreq-0.5.0.1\.w\dist\ca59d0ab\setup\setup.exe ...
    Configuring wreq-0.5.0.1...
    Building wreq-0.5.0.1...
    Preprocessing library wreq-0.5.0.1...
    [ 1 of 15] Compiling Paths_wreq       ( .w\dist\ca59d0ab\build\autogen\Paths_wreq.hs, .w\dist\ca59d0ab\build\Paths_wreq.o )
    [ 2 of 15] Compiling Network.Wreq.Lens.Machinery ( Network\Wreq\Lens\Machinery.hs, .w\dist\ca59d0ab\build\Network\Wreq\Lens\Machinery.o )
    [ 3 of 15] Compiling Network.Wreq.Internal.Types ( Network\Wreq\Internal\Types.hs, .w\dist\ca59d0ab\build\Network\Wreq\Internal\Types.o )
    [ 4 of 15] Compiling Network.Wreq.Internal.OAuth1 ( Network\Wreq\Internal\OAuth1.hs, .w\dist\ca59d0ab\build\Network\Wreq\Internal\OAuth1.o )
    [ 5 of 15] Compiling Network.Wreq.Internal.Lens ( Network\Wreq\Internal\Lens.hs, .w\dist\ca59d0ab\build\Network\Wreq\Internal\Lens.o )
    ghc.EXE: unable to load package `foundation-0.0.10'
    ghc.EXE: C:\s\snapshots\f4677c28\lib\x86_64-windows-ghc-8.0.2\foundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB\HSfoundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB.o: unknown symbol `clock_getres'
--  While building package wai-app-static-3.1.6.1 using:
      C:\s\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.w\dist\ca59d0ab build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\w\.w\logs\wai-app-static-3.1.6.1.log
    Configuring wai-app-static-3.1.6.1...
    Building wai-app-static-3.1.6.1...
    Preprocessing library wai-app-static-3.1.6.1...
    [1 of 9] Compiling WaiAppStatic.Types ( WaiAppStatic\Types.hs, .w\dist\ca59d0ab\build\WaiAppStatic\Types.o )
    [2 of 9] Compiling Util             ( Util.hs, .w\dist\ca59d0ab\build\Util.o )
    [3 of 9] Compiling WaiAppStatic.Listing ( WaiAppStatic\Listing.hs, .w\dist\ca59d0ab\build\WaiAppStatic\Listing.o )
    
    C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wai-app-static-3.1.6.1\WaiAppStatic\Listing.hs:67:34: warning: [-Wname-shadowing]
        This binding for `pieces' shadows the existing binding
          bound at WaiAppStatic\Listing.hs:27:16
    
    C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wai-app-static-3.1.6.1\WaiAppStatic\Listing.hs:120:24: warning: [-Wunused-local-binds]
        Defined but not used: `isFile'
    [4 of 9] Compiling WaiAppStatic.Storage.Filesystem ( WaiAppStatic\Storage\Filesystem.hs, .w\dist\ca59d0ab\build\WaiAppStatic\Storage\Filesystem.o )
    [5 of 9] Compiling WaiAppStatic.Storage.Embedded.Runtime ( WaiAppStatic\Storage\Embedded\Runtime.hs, .w\dist\ca59d0ab\build\WaiAppStatic\Storage\Embedded\Runtime.o )
    [6 of 9] Compiling WaiAppStatic.Storage.Embedded.TH ( WaiAppStatic\Storage\Embedded\TH.hs, .w\dist\ca59d0ab\build\WaiAppStatic\Storage\Embedded\TH.o )
    
    C:\Users\appveyor\AppData\Local\Temp\1\stack2532\wai-app-static-3.1.6.1\WaiAppStatic\Storage\Embedded\TH.hs:10:1: warning: [-Wunused-imports]
        The import of `Control.Applicative' is redundant
          except perhaps to import instances from `Control.Applicative'
        To import instances alone, use: import Control.Applicative()
    [7 of 9] Compiling WaiAppStatic.Storage.Embedded ( WaiAppStatic\Storage\Embedded.hs, .w\dist\ca59d0ab\build\WaiAppStatic\Storage\Embedded.o )
    [8 of 9] Compiling Network.Wai.Application.Static ( Network\Wai\Application\Static.hs, .w\dist\ca59d0ab\build\Network\Wai\Application\Static.o )
    ghc.EXE: unable to load package `foundation-0.0.10'
    ghc.EXE: C:\s\snapshots\f4677c28\lib\x86_64-windows-ghc-8.0.2\foundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB\HSfoundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB.o: unknown symbol `clock_getres'
--  While building package store-0.4.3.1 using:
      C:\s\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.w\dist\ca59d0ab build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\w\.w\logs\store-0.4.3.1.log
    Configuring store-0.4.3.1...
    Building store-0.4.3.1...
    Preprocessing library store-0.4.3.1...
    [ 1 of 11] Compiling System.IO.ByteBuffer ( src\System\IO\ByteBuffer.hs, .w\dist\ca59d0ab\build\System\IO\ByteBuffer.o )
    
    C:\Users\appveyor\AppData\Local\Temp\1\stack2532\store-0.4.3.1\src\System\IO\ByteBuffer.hs:59:1: warning: [-Wunused-imports]
        The qualified import of `Foreign.C.Error' is redundant
          except perhaps to import instances from `Foreign.C.Error'
        To import instances alone, use: import Foreign.C.Error()
    
    C:\Users\appveyor\AppData\Local\Temp\1\stack2532\store-0.4.3.1\src\System\IO\ByteBuffer.hs:60:1: warning: [-Wunused-imports]
        The import of `Foreign.C.Types' is redundant
          except perhaps to import instances from `Foreign.C.Types'
        To import instances alone, use: import Foreign.C.Types()
    
    C:\Users\appveyor\AppData\Local\Temp\1\stack2532\store-0.4.3.1\src\System\IO\ByteBuffer.hs:61:1: warning: [-Wunused-imports]
        The import of `System.Posix.Types' is redundant
          except perhaps to import instances from `System.Posix.Types'
        To import instances alone, use: import System.Posix.Types()
    [ 2 of 11] Compiling Data.Store.Streaming.Internal ( src\Data\Store\Streaming\Internal.hs, .w\dist\ca59d0ab\build\Data\Store\Streaming\Internal.o )
    [ 3 of 11] Compiling Data.Store.Impl  ( src\Data\Store\Impl.hs, .w\dist\ca59d0ab\build\Data\Store\Impl.o )
    [ 4 of 11] Compiling Data.Store.TH.Internal ( src\Data\Store\TH\Internal.hs, .w\dist\ca59d0ab\build\Data\Store\TH\Internal.o )
    [ 5 of 11] Compiling Data.Store.Internal ( src\Data\Store\Internal.hs, .w\dist\ca59d0ab\build\Data\Store\Internal.o )
    ghc.EXE: unable to load package `foundation-0.0.10'
    ghc.EXE: C:\s\snapshots\f4677c28\lib\x86_64-windows-ghc-8.0.2\foundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB\HSfoundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB.o: unknown symbol `clock_getres'
--  While building package plutus-prototype-0.1.0.0 using:
      C:\s\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.w\dist\ca59d0ab build lib:plutus-prototype --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\w\.w\logs\plutus-prototype-0.1.0.0.log
    Preprocessing library plutus-prototype-0.1.0.0...
    [19 of 24] Compiling Elaboration.Elaborator ( src\Elaboration\Elaborator.hs, .w\dist\ca59d0ab\build\Elaboration\Elaborator.o )
    ghc.EXE: unable to load package `foundation-0.0.10'
    ghc.EXE: C:\s\snapshots\f4677c28\lib\x86_64-windows-ghc-8.0.2\foundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB\HSfoundation-0.0.10-JGhHXvcRrtp6mVId9fjHXB.o: unknown symbol `clock_getres'
Sorry, we tried running command for 5 times and all attempts were unsuccessful!
```

**Comment by deepfire** [comment]
@domenkozar says we have to disable AppVeyor cache temporarily

**Comment by domenkozar** [comment]
@deepfire using xcode8 helps, we will see SSL issues again, but at least most of the time it will build.

**Comment by domenkozar** [comment]
@georgeee 

```
Jul 06 17:08:10     /home/travis/build/input-output-hk/cardano-sl/core/Pos/Util/Config.hs:245:15: error:
Jul 06 17:08:10         • Couldn't find config "wallet" in /home/travis/build/input-output-hk/cardano-sl/core/constants.yaml
Jul 06 17:08:10         • In the untyped splice:
Jul 06 17:08:10             $(do { TH.qAddDependentFile cslConfigFilePath;
Jul 06 17:08:10                    either fail TH.lift =<< TH.runIO getCslConfig })
```

**Pull request merged**
