### PR TITLE
Batch Import Addresses to 1.5.0

### PR DESCRIPTION
**Pull request by KtorZ**
## Description

Backporting input-output-hk/cardano-wallet#259 to 1.5.0

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## How to merge

Send the message `bors r+` to merge this PR. For more information, see
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/bors.md).

### CODE REVIEW

**Comment by deepfire** [comment]
@KtorZ, do you think it might make sense getting the property tests into the same PR as well?

**Comment by deepfire** [comment]
cc @cleverca22

**Comment by KtorZ** [comment]
@cleverca22 If ever, don't trigger bors. I'd like to add some bits to the CHANGELOG and the API doc before merging.

**Comment by tatyanavych** [comment]
Please add the CHANGELOG entry

**Comment by KtorZ** [comment]
I hate you bors. You're not my friend anymore.

**Comment by disassembler** [comment]
bors ping

**Pull request merged**
