### PR TITLE
Move to LTS Haskell 8.2

### PR DESCRIPTION
**Pull request by kantp**
Using GHC 8.0.2 with LTS-7.16 made it difficult to install some
packages (namely intero).

### CODE REVIEW

**Comment by denisshevchenko** [comment]
> Using GHC 8.0.2 with LTS-7.16

Sorry? I see that LTS Haskell 7.16 (https://www.stackage.org/lts-7.16) uses ghc-8.0.1, not ghc-8.0.2.

**Comment by denisshevchenko** [comment]
Since LTS Haskell 8.0 we're using ghc-8.0.2 (https://www.stackage.org/lts-8.0).

**Comment by kantp** [comment]
Sorry for the confusion, I should have been more explicit.

Previously, in `stack.yaml`, we had `-resolver: lts-7.16`, but also set the GHC version explicitly to 8.0.2 via `-compiler: ghc-8.0.2`. That caused problems when trying to install packages such as `ghci` or `intero`. Moving to LTS Haskell 8, we automatically use GHC 8.0.2, and don't need to set it explicitly.

**Comment by vincenthz** [comment]
cryptonite-openssl can be dropped from extra packages too, it's part of lts 8 now.

**Comment by kantp** [comment]
Oh, thanks, I didn't notice that!

**Comment by kantp** [comment]
Ah, there are some more packages we can drop from `extra-deps`

**Comment by domenkozar** [comment]
Bridge fails to build (huh, why doesn't it exit correctly?): https://travis-ci.org/input-output-hk/cardano-sl/jobs/204508858#L2868

**Comment by domenkozar** [comment]
@kantp pushed commit to bail on bridge build error.

**Comment by kantp** [comment]
Thanks, @domenkozar!

**Comment by kantp** [comment]
Ah, merge conflicts. I'll rebase to the current master, resolving conflicts.

**Comment by domenkozar** [comment]
@kantp we still need to fix bridge building, I can look into this after lunch :)

**Comment by domenkozar** [comment]
With `--bail` we actually get the CI to fail, but the errors become cryptic: https://github.com/webpack/webpack/issues/711

**Comment by jmitchell** [comment]
I'm digging into this. Nearly finished doing a clean-slate local build against this branch.

**Comment by akegalj** [comment]
@domen I think i know why it fails. Will check it tonight when i get home

**Comment by jmitchell** [comment]
@akegalj, there are errors with the generated Purescript code:

```
[1/3 UnknownImport] src\Generated\Pos\Types\Core.purs:4:19

  4  import Data.Lens (Lens', Prism', lens, prism')
                       ^^^^^

  Cannot import type Lens' from module Data.Lens
  It either does not exist or the module does not export it.

[2/3 UnknownImport] src\Generated\Pos\Util\BackupPhrase.purs:4:19

  4  import Data.Lens (Lens', Prism', lens, prism')
                       ^^^^^

  Cannot import type Lens' from module Data.Lens
  It either does not exist or the module does not export it.

[3/3 UnknownImport] src\Generated\Pos\Wallet\Web\Error.purs:4:19

  4  import Data.Lens (Lens', Prism', lens, prism')
                       ^^^^^
```

I'm getting familiar with when/how generation occurs to diagnose further.

**Comment by akegalj** [comment]
@jmitchell the reason for that is because new `lts` made some breaking changes with new `purescript-bridge`. I am going to rollback to the old now. To use new `purescript-bridge` we have to bump PureScript for daedalus bridge (client-api) and this wasn't ready few weeks ago.

Will have to talk to @sectore to see what is the state of this.

I will follback to old `purescript-bridge` for now so that this can be merged. We already have issue opened for bumping PureScript that can be addressed some times later.

**Comment by domenkozar** [comment]
Good work everyone :)

**Pull request merged**
