### PR TITLE
[CSL-1490] eliminate get block deadlock

### PR DESCRIPTION
**Pull request by avieth**
The maximum in-flight conversations, as given by the default dequeue
policy, for a relay to a core, is 1. When in recovery mode, a relay
requests headers and then, within that same conversation, attempts to
pull in the blocks by enqueueing a MsgGetBlocks. That's all fine except
that it waits, within that conversation, on the results of the
MsgGetBlocks conversation(s). That's the deadlock: those MsgGetBlocks
conversation(s) push the in flight over 1 and so are never dequeued and
the requestHeaders conversation never finishes.

This patch has us enqueue the MsgGetBlocks and not wait on the results.
I'm not sure if this breaks any block logic assumptions, but at the very
least it solves the deadlock.

### CODE REVIEW

**Comment by edsko** [comment]
So @kantp and I tried to confirm this theory, by running the tests again with higher `MaxInFlight`:

```
defaultDequeuePolicy :: NodeType -- ^ Our node type
                     -> DequeuePolicy
defaultDequeuePolicy NodeCore = go
  where
    -- Dequeueing policy for core nodes
    go :: DequeuePolicy
    go NodeCore  = Dequeue NoRateLimiting (MaxInFlight 2)
    go NodeRelay = Dequeue NoRateLimiting (MaxInFlight 1) -- SEE NOTE BELOW
    go NodeEdge  = error "defaultDequeuePolicy: core to edge not applicable"
defaultDequeuePolicy NodeRelay = go
  where
    -- Dequeueing policy for relay nodes
    go :: DequeuePolicy
    go NodeCore  = Dequeue (MaxMsgPerSec 1) (MaxInFlight 2) -- INCREASED
    go NodeRelay = Dequeue (MaxMsgPerSec 3) (MaxInFlight 2)
    go NodeEdge  = Dequeue (MaxMsgPerSec 1) (MaxInFlight 1)
defaultDequeuePolicy NodeEdge = go
  where
    -- Dequeueing policy for edge nodes
    go :: DequeuePolicy
    go NodeCore  = error "defaultDequeuePolicy: edge to core not applicable"
    go NodeRelay = Dequeue (MaxMsgPerSec 1) (MaxInFlight 2) -- INCREASED
    go NodeEdge  = error "defaultDequeuePolicy: edge to edge not applicable"
```

With this policy the tests pass, confirming the theory. So this may be an alternative approach, if the changes higher up the chain are not okay (I don't understand exactly what it's meant to do).

As @kantp points out, we'll probably also want to change the line marked "NOTE" above, or else core nodes won't be able to recover by talking to other core nodes. In fact, we may wish to be a little bit more permissive in our `MaxInFlight` generally.

Incidentally, there is also still this comment in the code (`cardano-sl/src/Pos/Block/Network/Retrieval.hs`) 

``` haskell
-- | Be careful to run this in the same thread that ends recovery mode
-- (or synchronise those threads with an MVar), otherwise a race
-- condition can occur where we are caught in the recovery mode
-- indefinitely.
updateRecoveryHeader
```

which is worrying me, as I am not at all convinced that these things _are_ in the same thread, with both the outbound queue (in the dequeue thread) as well as the lower level `time-warp-nt` library (in `withInOutChannel`) spawn new threads that run conversations.

Pinging @dcoutts .

**Comment by edsko** [comment]
There are more policy changes that we'd have to make. Still investigating.

**Comment by edsko** [comment]
See https://github.com/serokell/time-warp-nt/pull/89 .

**Comment by dcoutts** [comment]
@gromakovsky or perhaps @volhovM or @neongreen, we could really do with your review on this one. It's subtle.

**Comment by volhovM** [comment]
@int-index please take a look at it. I looked through the code and it makes sense for me, but i do not remember which concurrency issue were you fixing with that `endedRecoveryVar`.

**Comment by avieth** [comment]
Since bringing in the outbound queue there is a new case that we have to deal with (but currently don't): suppose we're in recovery mode and we try to get headers/blocks from a given peer, but the outbound queue determines that there's no room and so enqueues nothing. What then? The `retrievalWorkerImpl` just isn't set up for that case.

**Comment by dcoutts** [comment]
> Since bringing in the outbound queue there is a new case that we have to deal with (but currently don't): suppose we're in recovery mode and we try to get headers/blocks from a given peer, but the outbound queue determines that there's no room and so enqueues nothing. What then? The retrievalWorkerImpl just isn't set up for that case.

Ideally, we can change the logic so that instead of deciding to get headers/blocks from a given peer, it can select *all* the possible peers and then let the new networking code select one that actually is available. Then if that fails, then we've definitely really failed because we considered them all.

**Comment by int-index** [comment]
A few lines below you can see this comment:

```
        -- Block until the conversation has ended.
        whenM (readMVar endedRecoveryVar) $
            logInfo "Recovery mode exited gracefully"
```

It's intentional and important that we block here. The initial version of the code didn't have this line (because I assumed everything was happening synchronously), and it led to concurrency bugs.

In particular, the bug was that we got caught in the recovery mode indefinitely. It's mentioned in this comment:

```
-- | Be careful to run this in the same thread that ends recovery mode
-- (or synchronise those threads with an MVar), otherwise a race
-- condition can occur where we are caught in the recovery mode
-- indefinitely.
updateRecoveryHeader
    :: WorkMode ssc ctx m
    => NodeId
    -> BlockHeader ssc
    -> m ()
updateRecoveryHeader nodeId hdr = do
```

Now, I don't remember what exactly was happening, but it's not hypothetical and I observed the bad behavior when testing.

**Comment by int-index** [comment]
In a listener, when we receive an unsolicited header, and it's not a continuation of our chain, we put it into the queue:

```
handleUnsolicitedHeader header nodeId = do
    ...
        CHAlternative -> do
            logDebug $ sformat alternativeFormat hHash
            addHeaderToBlockRequestQueue nodeId header False
```

Since there are multiple listeners and multiple peers, we can often get a queue like this:

1. (node1, `BlockRetrievalTask someHeader False`)
2. (node2, `BlockRetrievalTask someHeader False`)
3. (node3, `BlockRetrievalTask someHeader False`)

The `False` flag means that `someHeader` is not a continuation of our chain, and we may need to request more headers rather than simply ask for a block. The `retrievalWorker` performs this tasks one by one.

Now, when we get to handle a task in the `retrievalWorker`, it might have become outdated. Even if the flag is `False`, by the time we get to handle the task it might be the case that we already have the relevant block in our DB (from performing earlier tasks, even). This is why the first thing we do is that we check that we actually need to ask for more headers:

```
    handleAlternative nodeId header = do
        mhrr <- mkHeadersRequest (headerHash header)
        case mhrr of
            MhrrBlockAdopted ->
                logDebug "Block already adopted, nothing to be done"
            MhrrWithCheckpoints mgh -> do
                logDebug "Checkpoints available, headers request assembled"
                handleHeadersRequest nodeId header mgh
```

In case the block referenced by the header is already adopted, the task can be discarded — there's nothing to be done. In case we do need to ask for more headers, we do it in `handleHeadersRequest`.

Now, `handleHeadersRequest` assumes that it's invoked when we're missing multiple headers (the check above ensures that), so the first thing it does is that it initiates the recovery mode (using `updateRecoveryHeader`). There are three possible options here:

* We're not in recovery mode. Then we start it.
* We're in recovery mode, but `someHeader` has more chain difficulty than the old `recoveryHeader`. Then we shift the recovery mode to a new goal, setting `recoveryHeader` to `someHeader`
* We're in recovery mode, but the received `someHeader` is not more difficult than the `recoveryHeader` we already know. Fine, so we remain in the recovery mode, nothing needs to be changed.

Then `handleHeadersRequest` needs to do its job:

* ask for missing headers
* ask for the blocks

Let's say it fails to do that (because an exception is thrown, or the connection is interrupted). We drop the recovery header since we're no longer sure we'll be able to successfully finish recovery at all, and then we try to trigger it again (we know we need it) with `triggerRecovery`. After we do this, the `retrievalWorker` can proceed to handle other tasks in the queue. 

Now, let's say that `handleHeadersRequest` doesn't fail. We get the headers, get the blocks, adopt them, and end the recovery mode. Hooray.

Three observations:

* we start the recovery mode only when we need to
* we end the recovery mode in case of failure
* we end the recovery mode in case of success

These two observations guarantee that the recovery mode will end eventually, right? Well, there's a third possibility of neither success nor failure:

* we've downloaded and adopted only a chunk of the blocks, and remained in the recovery mode

It might happen that there's just too much blocks to download all at once, so we download some, adopt them, but we still know that there's a more difficult block available, and we haven't recovered yet. In this case we just let it slip, because on the next iteration the `retirevalWorker` will see that we're in recovery mode and ask for more headers, again. (Even when there's no task in the queue, it does so).

Assuming `retrievalWorker` is synchronous, we can make the following observations:

* we start the recovery mode only when we need to
* we end the recovery mode in case of failure
* we end the recovery mode in case of success
* in case of neither success or failure (but some progress was made), a later iteration will end recovery mode

<hr>

Now that I described it all, I was about to tell you how making `retrievalWorker` asynchronous breaks this reasoning, but it doesn't. What actually breaks this reasoning is if we have a case where we didn't succeed, didn't fail, didn't make any progress, but still remained in the recovery mode. Adding this `MVar` synchronization probably covered part of this concern, but there's still no good guarantee.

What we actually need is to make it asynchronous:

* be prepared for TOCTOU at any time. Even if we determined that we need to download headers/blocks, this assumption can be violated by another thread that might be adding the blocks to the DB. 
* guarantee that if we make no progress, we treat the current iteration as a failure. Since downloading is happening in a different thread even now, throwing an exception will be simply ignored, so even now the logic is broken.
* remove this `endedRecovery` variable, apparently it doesn't serve its purpose well.

**Comment by int-index** [comment]
Another thing that occurred to me while reading the code is that we no longer use all of the headers from `requestHeaders`:

```
        let cont (headers :: NewestFirst NE (BlockHeader ssc)) =
                let firstHeader = headers ^. _Wrapped . _neLast
                in handleCHsValid enqueueMsg endedRecoveryVar nodeId
                                  firstHeader (headerHash header)
```

We're just taking the `firstHeader` here! Maybe we could simplify the logic by requesting only this header instead of the exponential distribution? @volhovM — it's your code, what do you think?

**Comment by volhovM** [comment]
I've read through @int-index's explanation and I agree with the last paragraph summary, current implementation won't work.

Regarding the last question about `cont` type: I do not clearly understand how you suggest it to be related to `MsgGetHeaders`. Continuation input is indeed redundant since all the checks on headers list are done inside `requestHeaders` and `handleRequestedHeaders`. Remember that in order to request blocks we need to know the `[from,to]` range explicitly so we can't get rid of the scheme with checkpoints without complicating processing logic even more than it is complex now.

**Comment by int-index** [comment]
I spent some more time looking at what's going on and now I think that we shouldn't remove the `endedRecovery` variable because it guarantees that `retrievalWorker` isn't attempting multiple tasks at once.

**Comment by avieth** [comment]
New relevant ticket created https://issues.serokell.io/issue/CSL-1515

> I spent some more time looking at what's going on and now I think that we shouldn't remove the endedRecovery variable because it guarantees that retrievalWorker isn't attempting multiple tasks at once, which would be sound but undesired.

A related question: as far as I can tell, the program will enter recovery mode whenever it receives a header of greater difficulty than its current tip that doesn't continue it. That's to say, sending it such a header will make it stop doing any useful work while it tries to catch up. Seems like this could be a devastating attack https://issues.serokell.io/issue/CSL-1514

**Comment by avieth** [comment]
Issue has been resolved. See also #1393

**Pull request closed without merging**
