### PR TITLE
Wallet spec input selection

### PR DESCRIPTION
**Pull request by edsko**
This is Duncan's thoughts on input selection, submitted just before going on holidays (cutting it so short he wasn't able to create a PR :grin: ).

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
haha, excellent, @edsko ! Will give it a look later today, if that's OK with you 😉

**Comment by denisshevchenko** [comment]
Why TeX? We're using Markdown, right?

**Comment by edsko** [comment]
> Why TeX? We're using Markdown, right?

Markdown? No, we're not.

**Comment by edsko** [comment]
Typesetting all this math in markdown would be painful :)

**Comment by erikd** [comment]
@denisshevchenko Markdown is the right choice for much of the documentation of how things work conceptually, coding guidelines etc, For the formal specification of the system that @edsko and others are working on, Markdown is not sufficient and hence TeX is being used..

**Pull request merged**
