### PR TITLE
[CSE-204] Add `maybe` tx inputs

### PR DESCRIPTION
**Pull request by sectore**
See https://issues.serokell.io/issue/CSE-204

This PR includes few updates of `README` of Explorers frontend, which are not part of `CSE-204`, but just nice to have.

How to test?
1. Build and run Explorer's frontend as described here: https://github.com/input-output-hk/cardano-sl/tree/master/explorer/frontend#build-in-development-mode

2. Run Explorer's mock server
```
$ cardano-sl » stack exec cardano-explorer-mock
```
3. Open http://localhost:3100/tx/b29fa17156275a8589857376bfaeeef47f1846f82ea492a808e5c6155b450e02 and you should see something like this (note that we have "--" for `Nothing` values of `tx inputs` now)

transaction-maybe

### CODE REVIEW

**Comment by ksaric** [comment]
Thanks for fixing the README.

I run it, seems there were some issues with CSS (look at the image), otherwise code looks good. 

Linux Mint Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

System:    Host: ksaric-H61M-S2V-B3 Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.4 (Gtk 2.24.30) dm: mdm Distro: Linux Mint 18.2 Sonya
Graphics:  Card: NVIDIA Device 128b bus-ID: 01:00.0 chip-ID: 10de:128b
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: GeForce GT 710/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 375.39 Direct Rendering: Yes

Also, seems there were some issues with tests, restarted it - `Test suite cardano-test: FAIL`.

explorer_blown

**Comment by sectore** [comment]
@ksaric What's your screen resolution? Does your browser zoom this page? I can't reproduce the CSS issue you mentioned. Could you try it again or test it with other browser?

**Comment by ksaric** [comment]
@sectore The resolution is written above the image, with the additional details. It's not zoomed in, I'll try it out soon and report.

**Comment by ksaric** [comment]
@sectore Works ok now. Weird. There is some strange behavior there, tried zooming and it's responsive (as opposed to the image above). 1 in a 1000? :confused:

**Pull request merged**
