### PR TITLE
CSLA-25: Fix UserSecret file locking in Windows.

### PR DESCRIPTION
**Pull request by jmitchell**
System.FileLock doesn't support a process writing to a file it previously
locked. Instead the file passed to `withFileLock`/`lockFile` is meant to be an
inter-process mutex (see
https://github.com/takano-akio/filelock/issues/2#issuecomment-275041129).

This change protects multiple writers from concurrently modifying the secret key
file (`secret.key` by default). It does so by using System.FileLock's
inter-process mutexes as intended.

### CODE REVIEW

**Comment by jagajaga** [comment]
We also need this on master branch I suppose.

**Comment by georgeee** [comment]
Cardano-sl-0.1 is to be merged to master eventually, ofc

**Comment by jagajaga** [comment]
> Cardano-sl-0.1 is to be merged to master eventually, ofc
That's not obvious

**Comment by georgeee** [comment]
Well, this is general agreement on release branches. Perhaps I didn't make
this idea clear before (in Slack)

**Comment by jagajaga** [comment]
> Well, this is general agreement on release branches. Perhaps I didn't make this idea clear before (in Slack)

Release branches aren't usually merged into master. Usually commits from master are cherry-picked into release if necessary.

**Comment by gromakovsky** [comment]
We had a discussion in Slack before creating release branch and there everybody agreed that release branches should be merged into master.

**Comment by domenkozar** [comment]
Will also make a PR to master with all packaging changes.

**Comment by domenkozar** [comment]
PR for master: https://github.com/input-output-hk/cardano-sl/pull/18/files

**Comment by domenkozar** [comment]
I tested and confirmed that Daedalus now:

- starts successfully without `secret.key` and the file is created
- starts sucessfully with `secret.key` present
- `secret.key.lock` is created during runtime

Using https://ci.appveyor.com/api/buildjobs/rx3txy9986nad75q/artifacts/installers%2Fdaedalus-win64-0.1.207-installer.exe

**Pull request merged**
