### PR TITLE
[DO NOT MERGE] [CSL-2344] Fix broken appveyor build

### PR DESCRIPTION
**Pull request by Martoon-00**
This is attempt to mitigate broken build in #2541 and similar PRs by renaming `cardano-node-new` executable with `cardano-new`

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
@Martoon-00 oh wow, the diff is huge! Branched not from `develop/HEAD`? 😉

**Comment by Martoon-00** [comment]
I took one of PRs which experiences our problem as base to check that solution works. :slightly_smiling_face:
Although it seems to take too much time to check, so let true PR hang in parallel here: #2609

**Comment by adinapoli-iohk** [comment]
@Martoon-00 I have merged the patch with the fix, I think we can close this one, if you want. 😉

**Comment by Martoon-00** [comment]
Oki, thanks!
Appveyor build hasn't complete yet, I rely on your confidence of that problem is fixed :sunglasses:

**Pull request closed without merging**
