### PR TITLE
wallet-new: Add Setup.hs and default.nix files for easing Cabal usage

### PR DESCRIPTION
**Pull request by k0001**
See `wallet-new/default.nix` documentation.

### CODE REVIEW

**Comment by k0001** [comment]
Actually, wait, the passing of `args` is wrong.

**Comment by k0001** [comment]
Due to #2736 profiling and debugging can't be enabled by default without a deeper investigation, so I am submitting this without those features.

**Comment by adinapoli-iohk** [comment]
Thanks @k0001 ! Sorry for the noob question (I'm relatively new to `nix`) but what would happen if the user doesn't have `nix` and the `nix-shell` available? Would the two new lines in `Setup.hs` cause any disruption to folks building with plain `stack` or even `cabal new-build`?

**Comment by k0001** [comment]
@adinapoli-iohk that's a good question. 

Nothing would happen, shebang lines are always ignored by GHC. Although, more generally, the entire `Setup.hs` is currently ignored because it says `build-type: Simple` in the `.cabal` file.

The intention with this change is that I can run stuff like `./Setup.hs repl` or `nix-shell` in this folder and it works.

**Comment by adinapoli-iohk** [comment]
> Nothing bad would happen; shebang lines are always ignored by GHC. Although, more generally, the entire Setup.hs is currently ignored because it says build-type: Simple in the .cabal file.

@k0001 Crystal clear (and TIL!)

I have restarted the build for Appveyor, which seems to have failed irrespective of your work -- hopefully rebuilding the commit will do the trick.

**Comment by adinapoli-iohk** [comment]
Ah, I have just clarified this with the DevOps team, and indeed the Appveyor failure is a known one, fixed as part of this PR: https://github.com/input-output-hk/cardano-sl/pull/2714

Would you mind rebasing your PR against `develop`  @k0001 ? 😉

**Comment by k0001** [comment]
@adinapoli-iohk rebased as requested.

**Pull request merged**
