### PR TITLE
[DEVOPS-282] Bump stack2nix

### PR DESCRIPTION
**Pull request by jmitchell**

### CODE REVIEW

**Comment by domenkozar** [comment]
I've rebased master to see what Hydra has to say now: https://hydra.iohk.io/jobset/serokell/cardano-pr-1450

**Comment by jmitchell** [comment]
The latest evaluation succeeded: https://hydra.iohk.io/eval/64000

**Comment by domenkozar** [comment]
Blocked on https://github.com/input-output-hk/stack2nix/issues/66

**Comment by gromakovsky** [comment]
@domenkozar I suppose it's now superseded by #2277. Please close if it's correct.

**Comment by domenkozar** [comment]
Yes.

**Pull request closed without merging**
