### PR TITLE
[CSL-754] Factor core out

### PR DESCRIPTION
**Pull request by georgeee**
This commit does the following:

* Split out into cardano-sl-core:

    * some modules from Pos.Crypto.*
    * some modules from Pos.Types.*
    * Pos.Script.Type (under the name of Pos.Types.Script)
    * Pos.Merkle
    * Pos.Data.Attributes
    * Pos.Binary.Class

* Move Pos.Util.Binary into Pos.Binary.Class.

* Get rid of Pos.Crypto.Arbitrary.Hash.

* Get rid of the KeyPair type from Pos.Crypto.Arbitrary.

### CODE REVIEW

**Comment by neongreen** [comment]
Thanks @mention-bot, going to review now

**Comment by georgeee** [comment]
:D

**Comment by neongreen** [comment]
Hmmmm, looks nice

Great job, @neongreen

**Comment by neongreen** [comment]
though in the future please try to keep such changes in separate commits, there's no reason why e.g. “Move Pos.Util.Binary into Pos.Binary.Class” couldn't be in a different commit (and it makes reviewing harder)

**Comment by neongreen** [comment]
ok

**Comment by gromakovsky** [comment]
@neongreen btw, I totally agree with @neongreen 👍

**Pull request merged**
