### PR TITLE
[CSL-1783] Add "api/info" endpoint

### PR DESCRIPTION
**Pull request by gromakovsky**

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
Looks awesome @gromakovsky ! Any chance you could attach an example of how this looks like as a proper JSON payload (aka by performing a request to this new endpoint)? If I understood correctly calling `/api/version` will return:

```
{ "version": "v0"
, "gitRev": ...
}
```

but having a cross-check (especially for who is going to use it) makes eyeballing this way easier. LGTM though!

**Comment by gromakovsky** [comment]
@adinapoli-iohk screenshot from postman: https://i.imgur.com/AmsVnjq.png

**Comment by adinapoli-iohk** [comment]
Excellent, thanks! 😉

**Comment by dcoutts** [comment]
Can I also request that we re-target this for the 1.0 branch rather than the exchanges branch. I don't think this feature is essential to provide outside of the normal release cycle. So it can be included into the 1.0 branch and exchanges will pick that up in due course.

**Comment by adinapoli-iohk** [comment]
What about something along the lines of (feel free to propose changes):

``` yaml
  /api/info:
    get:
      description: Returns general information about this service.
      responses:
        '200':
          schema:
            example:
              gitRevision: 6f1131adca2f0bc6d24c9181cabd2b9e0704fd79
              version: v0
              softwareVersion: 1.0.3.5
              blockchainVersion: 1.0.0.0
            type: object
            properties:
              gitRevision:
                type: string
              softwareVersion:
                type: string
              blockchainVersion:
                type: string
              apiVersion:
                type: string
          description: ''
      produces:
        - application/json;charset=utf-8
```

This Swagger snippet is equivalent to:

screen shot 2017-10-24 at 09 37 43

In a nutshell, I think one way to solve the ambiguity here is to drop `/version` in favour of `/info` to embrace a more "general purpose" endpoint which can return not only the API version but also more useful stuff.

**Comment by gromakovsky** [comment]
I've redone the tasks and changed the base branch. This is how response looks now:
```
{
    "Right": {
        "cabalVersion": "1.0.2",
        "apiVersion": "v0",
        "gitRevision": "8a56eb2b9efeb7a7a431a91a0cb3b50b5f3938fb",
        "softwareVersion": "cardano-sl:0"
    }
}```

The only missing thing is to make swagger documentation correct. I will do it later.

**Comment by adinapoli-iohk** [comment]
@gromakovsky Looks good. The only thing which we might need to have a think about is exposing `cabalVersion` and whether we should give it another name, as we are sort of "leaking" implementation details outside. For what is worth, users of the API shouldn't even need to know what Cabal is and that we are using Haskell under the hood. I would be curious to hear what @dcoutts has to say though 😀

**Comment by adinapoli-iohk** [comment]
I have just noticed that apparently we already have an endpoint which would yield the software version:

https://cardanodocs.com/technical/wallet/api/#path--api-settings-version

I'm wondering whether it might make sense to fuse the two and to deprecate `/api/settings/version`. (this is something we can surely do in the V1 API, question being is that we want the complication here).

**Pull request merged**
