### PR TITLE
make it build with network-3.1.0.1

### PR DESCRIPTION
**Pull request by avieth**
## Description

Some dodgy changes to swagger stuff: had to place .~ with ?~ but I have
no clue what I'm doing here. Judging from resources found on the
internet it seems to be the way forward but I am not at all sure please
review.

ALSO important news: the kademlia dependency is now gone. We never used
it anyway and it was just annoying to maintain (it depends upon old
network). Unforunately this change may break existing configurations. We
shall see.

There's a new network-transport-tcp revision that includes nontrivial changes
necessitated by the new network library interface. Must review that too.
https://github.com/avieth/network-transport-tcp/commit/984386467466d89621eda1cff8bbb435a9b9c0ef

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## How to merge

Send the message `bors r+` to merge this PR. For more information, see
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/bors.md).

### CODE REVIEW

**Comment by angerman** [comment]
See https://github.com/input-output-hk/haskell.nix/issues/404 for the iserv patch to make it build when cross compiling to windows.

**Review by karknu — APPROVED** [review]
LGTM.

**Review by dcoutts — APPROVED** [review]
LGTM.

**Pull request merged**
