### PR TITLE
Move UTxO DSL to its own package

### PR DESCRIPTION
**Pull request by nc6**
## Description

This PR moves the UTxO DSL to its own package, rather than living in the tests for wallet-new. This should allow it to be used outside of the wallet context - in particular, for node-level property tests.

## Linked issue

https://iohk.myjetbrains.com/youtrack/issue/CDEC-380

## Type of change
- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by nc6** [comment]
Looks like I've managed to miss some stuff in extracting this anyway, so needs some fixups.

**Comment by nc6** [comment]
Yeah, I'm currently in a cycle of rebasing this and then hoping desperately that appveyor will mysteriously decide to actually work in order to merge before it needs rebasing again. It feels like a losing battle.

**Comment by edsko** [comment]
Just FYI, I'm making a small modification to `Wallet/Abstract.hs`, but I guess you're not actually moving that, so probably not relevant. Just mentioning it in case :)

**Comment by jcmincke** [comment]
@erikd @nc6 @parsonsmatt Do we merge this PR?

**Comment by parsonsmatt** [comment]
It should be merged at some point, though I'm not sure when or what the status is on this, and it's getting out of date :\

**Comment by nc6** [comment]
Closing this for now; a much bigger change is needed to leave this PR compatible with the nix build system (which handles dependencies slightly differently).

**Pull request closed without merging**
