### PR TITLE
[CSE-211] Fix explorer launch script

### PR DESCRIPTION
**Pull request by sectore**
This PR includes an updated generation of `topology*.yaml` files to have 

```
"explorer":
    type: core
    region: undefined
    static-routes: [["node0"], ["node1"], ["node2"], ["node3"]]
    addr: 127.0.0.1
    port: 3004
```
and start `explorers.sh` with `--node-id explorer`. 

All these ^ changes are suggestions by @ksaric (see https://github.com/input-output-hk/cardano-sl/pull/1476#issuecomment-326910748)

Also `explorer.sh` runs with 4 nodes now to avoid an error of:
```
Error creating TCP transport: Network.Socket.bind: resource busy (Address already in use)
cardano-node: Network.Socket.bind: resource busy (Address already in use)
```

### CODE REVIEW

**Comment by ksaric** [comment]
Explorer is working now as a `relay` node.

**Comment by ksaric** [comment]
I'll need to fix that script at some point in the future because it's pretty bad. 
We need to add some additional parameters to check if the script needs to run explorer, for example.
Or we can switch to Python or Shelly, since this is a pain in the ass.

**Comment by dcoutts** [comment]
@sectore @ksaric as far as I can tell, and from talking to @deepfire, this PR isn't needed by the devops for mainnet. Let me know if you think I've missed something.

**Comment by ksaric** [comment]
@dcoutts Not required.

**Pull request merged**
