### PR TITLE
Prepare 1.0.1

### PR DESCRIPTION
**Pull request by domenkozar**
This pulls in https://github.com/input-output-hk/cardano-sl/pull/1639 and sets cabal version for update system to work.

### CODE REVIEW

**Comment by domenkozar** [comment]
@ksaric @akegalj @sectore we need explorer compile errors here fixes ASAP (today/tomorrow)

**Comment by domenkozar** [comment]
cc @dcoutts ready for review.

**Comment by akegalj** [comment]
@domenkozar @dcoutts 
we don't want to merge https://github.com/input-output-hk/cardano-sl/pull/1639 yet until @Pastafarianist  tests it and gives green light

**Comment by dcoutts** [comment]
The total ada patches are reported not to be ready. I've cherry-picked the version bumps. @akegalj please open a PR against 1.0 when the total ada stuff is ready.

**Pull request closed without merging**
