### PR TITLE
[DEVOPS-424] Rewrite connect scripts in Nix

### PR DESCRIPTION
**Pull request by domenkozar**
- [x] update https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/connect-to-cluster.md

### CODE REVIEW

**Comment by denisshevchenko** [comment]
LGTM.

**Comment by domenkozar** [comment]
@cleverca22 suggests using `writeScriptBin`, I'll look into that.

**Comment by cleverca22** [comment]
`writeScriptBin` has the exact same api as `writeScript`, the only difference is that one puts the script at `$out` and the other puts it at `$out/bin/$name`

**Comment by domenkozar** [comment]
@cleverca22 you mean the other way around?

```
$ nix-build -E 'with (import <nixpkgs> {}); writeScriptBin "asd" "mkdir -p $out"'
these derivations will be built:
  /nix/store/xx6wxqlprvpirybvla71jsmv2xkpj4rc-asd.drv
building path(s) ‘/nix/store/4zgv1ppkc54jhrgwlrjyzw25z7m3l2b1-asd’
/nix/store/4zgv1ppkc54jhrgwlrjyzw25z7m3l2b1-asd

$ ls /nix/store/4zgv1ppkc54jhrgwlrjyzw25z7m3l2b1-asd
bin
```

**Comment by cleverca22** [comment]
ah, i gave the examples in the opposite order that i had named them

**Pull request merged**
