### PR TITLE
[CSL-1998] Remove update tx endpoint

### PR DESCRIPTION
**Pull request by akegalj**
Issue: https://iohk.myjetbrains.com/youtrack/issue/CSL-1998

### CODE REVIEW

**Comment by adinapoli-iohk** [comment]
@akegalj Argh! More CI trouble:

```
    C:\w\wallet\src\Pos\Wallet\Web\Api.hs:55:1: warning: [-Wunused-imports]
        The import of `CTxId, CTxMeta'
        from module `Pos.Wallet.Web.ClientTypes' is redundant
    
    <no location info>: error: 
```

**Comment by akegalj** [comment]
@adinapoli-iohk Strange. It built on my machine. Maybe I have stashed some changes. 

Sorry, will fix

**Comment by akegalj** [comment]
@adinapoli-iohk 
CI failures:
 * The job exceeded the maximum time limit for jobs, and has been terminated.
 * Insufficient memory

I believe we can ignore those ?

**Comment by adinapoli-iohk** [comment]
Yes, as long as 50% of the checks passed (like in this case) I'm fairly happy to merge. Thanks!

**Pull request merged**
