### PR TITLE
use stack lts-11.2

### PR DESCRIPTION
**Pull request by avieth**
*Vast* majority of changes are in the generated `pkgs/default.nix`. Any kind soul willing to review this would only be in for ~450 additions and ~450 deletions, all of which are basically trivial.

### CODE REVIEW

**Comment by avieth** [comment]
@domenkozar I think I need to bump the hackage snapshot but I don't know how to find the right value for it.

**Comment by parsonsmatt** [comment]
@avieth I just bumped the hackage snapshot to get a newer `swagger2` version, and I just modified the day/month value. It worked fine. But it might, in fact, be Wrong

**Comment by avieth** [comment]
> @avieth I just bumped the hackage snapshot to get a newer swagger2 version, and I just modified the day/month value. It worked fine. But it might, in fact, be Wrong

Wow I think it worked. Thanks!

**Comment by avieth** [comment]
As always, appveyor fails. Merging anyway

**Pull request merged**
