### PR TITLE
Cardano sl 0.1 bugfixes

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by jagajaga** [comment]
We need to merge that today @domenkozar @georgeee. Please do that ASAP.

**Comment by domenkozar** [comment]
This is ready for review

**Comment by jagajaga** [comment]
@georgeee please fix https://github.com/input-output-hk/cardano-sl/pull/18/conflicts

**Comment by jagajaga** [comment]
Also @pva701 please fix https://github.com/input-output-hk/cardano-sl/pull/18/conflicts

**Pull request merged**
