### PR TITLE
[CSL-1635] Read own UTXO from DB with streaming in 'aux'

### PR DESCRIPTION
**Pull request by int-index**
to be merged after #1527

### CODE REVIEW

**Comment by gromakovsky** [comment]
#1527 is merged. Please rebase and change base branch.

**Comment by gromakovsky** [comment]
@int-index FYI: you merged it into rubbish branch which probably wasn't intended.
https://github.com/input-output-hk/cardano-sl/pull/1532#issuecomment-328341560

**Comment by int-index** [comment]
Mda, I feel stupid. Going to make another PR now.

**Comment by int-index** [comment]
https://github.com/input-output-hk/cardano-sl/pull/1538

**Comment by int-index** [comment]
This wasn't merged to master anyway.

**Comment by dcoutts** [comment]
@int-index oops, you're quite right I didn't spot that. It got merged in #1525 instead.

**Pull request merged**
