### PR TITLE
Batch Import Addresses  to  1.4.2

### PR DESCRIPTION
**Pull request by KtorZ**
## Description

Backporting input-output-hk/cardano-wallet#259 to 1.4.2

## Type of change

- [ ] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] 🛠 New feature (non-breaking change which adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🏭 Refactoring that does not change existing functionality but does improve things like code readability, structure etc
- [ ] 🔨 New or improved tests for existing code
- [ ] ⛑ git-flow chore (backport, hotfix, etc)

## Developer checklist

- [ ] I have read the [style guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/style-guide.md) document, and my code follows the code style of this project.
- [ ] If my code deals with exceptions, it follows the [guidelines](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/exceptions.md).
- [ ] I have updated any documentation accordingly, if needed. Documentation changes can be reflected in opening a PR on [cardanodocs.com](https://github.com/input-output-hk/cardanodocs.com), amending the inline [Haddock](https://www.haskell.org/haddock/) comments, any relevant README file or one of the document listed in the [docs](https://github.com/input-output-hk/cardano-sl/tree/develop/docs) directory.
- [ ] CHANGELOG entry has been added and is linked to the correct PR on GitHub.

## Testing checklist

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## How to merge

Send the message `bors r+` to merge this PR. For more information, see
[`docs/how-to/bors.md`](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/bors.md).

### CODE REVIEW

**Comment by deepfire** [comment]
@KtorZ, do you think it might make sense getting the property tests into the same PR as well?

**Comment by KtorZ** [comment]
@deepfire Not exactly :confused: 
I've added some integration tests to illustrate some scenarios in input-output-hk/cardano-wallet#268 and this will be backported to `cardano-sl/develop` as part of input-output-hk/cardano-wallet#251. Yet, at the moment, `cardano-sl/develop` doesn't have the necessary tooling (we've completely re-written our integration test framework and that's what need backporting).

**Comment by KtorZ** [comment]
Having said that, we may be able to add a couple of unit tests as part of this PR already.

**Comment by tatyanavych** [comment]
@KtorZ , 1.4.1 is closed; nothing should be merged there.
If there is a need to deliver this in 1.4 then next branch is to be created off master (1.4.2 in this case). 
CC: @deepfire

**Comment by KtorZ** [comment]
@tatyanavych Created a branch `release/2.0.2` and updated the PR base to this :+1:

**Comment by deepfire** [comment]
cc @cleverca22

**Comment by KtorZ** [comment]
@cleverca22 If ever, don't trigger bors. I'd like to add some bits to the CHANGELOG and the API doc before merging.

**Pull request merged**
