### PR TITLE
Update clean_db.sh

### PR DESCRIPTION
**Pull request by ksaric**
Update clean_db.sh

https://input-output-rnd.slack.com/archives/G2FTCSW69/p1492078136251739

### CODE REVIEW

**Comment by ChShersh** [comment]
@ksaric There're some redundancy in scripts now unfortunately. Could you also fix other scripts and, for example, cherry-pick these fixes into `master`? There are no actual need in using both these scripts:
https://github.com/input-output-hk/cardano-sl/blob/c4e4e0bf883dc01fe1dc1d7e9a15f4bd361ae79e/util-scripts/clean-local-data.sh
https://github.com/input-output-hk/cardano-sl/blob/c4e4e0bf883dc01fe1dc1d7e9a15f4bd361ae79e/util-scripts/clean_db.sh
Also I see this script is doing some cleaning data as well:
https://github.com/input-output-hk/cardano-sl/blob/c4e4e0bf883dc01fe1dc1d7e9a15f4bd361ae79e/util-scripts/clean.sh
Maybe those `rm` calls can be replaced with just calling `clean-db.sh` script.
Also I suspect that those scripts are called somewhere. Inside some other scripts. So if you're removing completely `clean-local-data.sh` (which I think should be done) then some other scripts that executes this script should be fixed (i.e. replace `clean-local-data.sh` with `clean_db.hs`)

**Comment by rockbmb** [comment]
@ksaric I second what @ChShersh said.

**Comment by gromakovsky** [comment]
Pull request was closed automatically, because I removed `-rc` branch. Change target branch and reopen if needed. I will delete branch somewhere in future, I don't know if it's still needed.

**Comment by ksaric** [comment]
@gromakovsky It's not needed, I'll reopen a PR when I fix these scripts.

**Pull request closed without merging**
