### PR TITLE
[DEVOPS-565]  appveyor:  restore Daedalus artifacts delivery

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by deepfire** [comment]
cc @gromakovsky

**Comment by deepfire** [comment]
cc @gromakovsky

**Comment by domenkozar** [comment]
Superseeded by https://github.com/input-output-hk/cardano-sl/pull/2155

**Comment by gromakovsky** [comment]
@domenkozar I think it's a mistake to close this PR, because #2155 targets `develop` and this PR targets `release/1.0.4`. We need this fix in release branch, because currently appveyor produces almost empty artifacts.
Last build: https://ci.appveyor.com/project/jagajaga/cardano-sl/build/1.0.18189/artifacts

**Comment by domenkozar** [comment]
@gromakovsky I'll prepare #2155 today to address this

**Pull request closed without merging**
