### PR TITLE
Cardano sl 1.0 genesis json v2

### PR DESCRIPTION
**Pull request by dcoutts**
TODOs:

 * [x] probably need to regenerate nix pkgs
 * [x] not all tests build (the original json genesis were based on master)
 * [x] some tests don't pass: https://gist.github.com/42aa175ed72b3f604b4d0510ef67f126
 * [x] need to disable lwallet and/or import auxx tool
 * [ ] need to rework PR to split & combine changes to make it easier to review

### CODE REVIEW

**Comment by neongreen** [comment]
Surprisingly, stack2nix is up to date. I'm not sure why the stack2nix build on Travis fails then.

**Comment by neongreen** [comment]
> Fix bad merge in pkgs/default.nix

Huh, I was looking at `cardano-sl-1.0` instead of `cardano-sl-1.0-genesis-json2` for some reason. _Mda_

**Comment by avieth** [comment]
> need to disable lwallet and/or import auxx tool

Surely disabling lwallet but *not* bringing in auxx isn't an option. auxx tool is fixed over in #1550 so I can bring those changes in as part of my history editing.

**Comment by neongreen** [comment]
@avieth so you're going to bring in `auxx`, right? By the way, can you explain what exactly “disabling lwallet” means?

**Comment by avieth** [comment]
> @avieth so you're going to bring in auxx, right? By the way, can you explain what exactly “disabling lwallet” means?

Removing it from the build plan I guess. But that seems unacceptable without bringing it its replacement auxx.

We could just drop in the `auxx` directory from master and apply the relevant updates to it from #1550 . Would this be alright for `cardano-sl-1.0`? @dcoutts

**Comment by avieth** [comment]
I've pushed avieth/split_d6029a2db (that sha1 fragment was once relevant but I can't remember why; probably it changed during rebases).

I did much consolidation into commit 2a3c7e85863f7e1ad1acbffd4401188fc512ad6e (rebasing repeatedly on 01432c09da2f17855c29ba2c3c59b5c0a01849d4). There were many changes to the initial commit that I had put out for the configuration mechanism and genesis delivery. They've been squashed into that commit 2a3c7e85863f7e1ad1acbffd4401188fc512ad6e so now you can't see the intermediate positions. Tomorrow I'll split it up into the main change to cardano-sl-core, followed by ancillary changes to dependent modules.

Other commits are independent things like supporting scripts.

I've also updated lwallet so that it builds.

@dcoutts

**Comment by dcoutts** [comment]
> We could just drop in the auxx directory from master and apply the relevant updates to it from #1550 . Would this be alright for cardano-sl-1.0? @dcoutts

Yes that'd be perfect.

**Comment by avieth** [comment]
https://github.com/input-output-hk/cardano-sl/compare/01432c09da2f17855c29ba2c3c59b5c0a01849d4...48c2b156e34a820c687840d611a7c0c2650bdaab

Hopefully this is easier to review. The principal change for JSON genesis can be found in the first commit there 8b109fb, followed by a bunch of commits which update depending modules individually (db, infra, etc.).

Massive but trivial patches have been isolated. These ones for instance just delete or add big yaml files bdf726fa3be20bbf7b2bde5c10121e1522cfc37 7660280938b543e5b84eab9d5630d7d682389075

Later commits are relevant to supporting scripts and so can be reviewed independently.

@dcoutts

**Comment by georgeee** [comment]
Changes from this PR are merged to cardano-sl-1.0

**Pull request closed without merging**
